In [1]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8ad80af0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "29f1d272",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('netflix_titles.csv', lineterminator='\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f343efbc",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>show_id</th>\n",
       "      <th>type</th>\n",
       "      <th>title</th>\n",
       "      <th>director</th>\n",
       "      <th>cast</th>\n",
       "      <th>country</th>\n",
       "      <th>date_added</th>\n",
       "      <th>release_year</th>\n",
       "      <th>rating</th>\n",
       "      <th>duration</th>\n",
       "      <th>listed_in</th>\n",
       "      <th>description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>s1</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Dick Johnson Is Dead</td>\n",
       "      <td>Kirsten Johnson</td>\n",
       "      <td>NaN</td>\n",
       "      <td>United States</td>\n",
       "      <td>September 25, 2021</td>\n",
       "      <td>2020</td>\n",
       "      <td>PG-13</td>\n",
       "      <td>90 min</td>\n",
       "      <td>Documentaries</td>\n",
       "      <td>As her father nears the end of his life, filmm...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>s2</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>Blood &amp; Water</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...</td>\n",
       "      <td>South Africa</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>2 Seasons</td>\n",
       "      <td>International TV Shows, TV Dramas, TV Mysteries</td>\n",
       "      <td>After crossing paths at a party, a Cape Town t...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>s3</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>Ganglands</td>\n",
       "      <td>Julien Leclercq</td>\n",
       "      <td>Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>1 Season</td>\n",
       "      <td>Crime TV Shows, International TV Shows, TV Act...</td>\n",
       "      <td>To protect his family from a powerful drug lor...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>s4</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>Jailbirds New Orleans</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>1 Season</td>\n",
       "      <td>Docuseries, Reality TV</td>\n",
       "      <td>Feuds, flirtations and toilet talk go down amo...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>s5</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>Kota Factory</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...</td>\n",
       "      <td>India</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>2 Seasons</td>\n",
       "      <td>International TV Shows, Romantic TV Shows, TV ...</td>\n",
       "      <td>In a city of coaching centers known to train I...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  show_id     type                  title         director  \\\n",
       "0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   \n",
       "1      s2  TV Show          Blood & Water              NaN   \n",
       "2      s3  TV Show              Ganglands  Julien Leclercq   \n",
       "3      s4  TV Show  Jailbirds New Orleans              NaN   \n",
       "4      s5  TV Show           Kota Factory              NaN   \n",
       "\n",
       "                                                cast        country  \\\n",
       "0                                                NaN  United States   \n",
       "1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   \n",
       "2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   \n",
       "3                                                NaN            NaN   \n",
       "4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   \n",
       "\n",
       "           date_added  release_year rating   duration  \\\n",
       "0  September 25, 2021          2020  PG-13     90 min   \n",
       "1  September 24, 2021          2021  TV-MA  2 Seasons   \n",
       "2  September 24, 2021          2021  TV-MA   1 Season   \n",
       "3  September 24, 2021          2021  TV-MA   1 Season   \n",
       "4  September 24, 2021          2021  TV-MA  2 Seasons   \n",
       "\n",
       "                                           listed_in  \\\n",
       "0                                      Documentaries   \n",
       "1    International TV Shows, TV Dramas, TV Mysteries   \n",
       "2  Crime TV Shows, International TV Shows, TV Act...   \n",
       "3                             Docuseries, Reality TV   \n",
       "4  International TV Shows, Romantic TV Shows, TV ...   \n",
       "\n",
       "                                         description  \n",
       "0  As her father nears the end of his life, filmm...  \n",
       "1  After crossing paths at a party, a Cape Town t...  \n",
       "2  To protect his family from a powerful drug lor...  \n",
       "3  Feuds, flirtations and toilet talk go down amo...  \n",
       "4  In a city of coaching centers known to train I...  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d8daab33",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 8807 entries, 0 to 8806\n",
      "Data columns (total 12 columns):\n",
      " #   Column        Non-Null Count  Dtype \n",
      "---  ------        --------------  ----- \n",
      " 0   show_id       8807 non-null   object\n",
      " 1   type          8807 non-null   object\n",
      " 2   title         8807 non-null   object\n",
      " 3   director      6173 non-null   object\n",
      " 4   cast          7982 non-null   object\n",
      " 5   country       7976 non-null   object\n",
      " 6   date_added    8797 non-null   object\n",
      " 7   release_year  8807 non-null   int64 \n",
      " 8   rating        8803 non-null   object\n",
      " 9   duration      8804 non-null   object\n",
      " 10  listed_in     8807 non-null   object\n",
      " 11  description   8807 non-null   object\n",
      "dtypes: int64(1), object(11)\n",
      "memory usage: 825.8+ KB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a6abcef0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0                                        Documentaries\n",
       "1      International TV Shows, TV Dramas, TV Mysteries\n",
       "2    Crime TV Shows, International TV Shows, TV Act...\n",
       "3                               Docuseries, Reality TV\n",
       "4    International TV Shows, Romantic TV Shows, TV ...\n",
       "Name: listed_in, dtype: object"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['listed_in'].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2f19ff32",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "np.int64(0)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.duplicated().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9dd4519e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>release_year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>8807.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>2014.180198</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>8.819312</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>1925.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>2013.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>2017.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>2019.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>2021.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       release_year\n",
       "count   8807.000000\n",
       "mean    2014.180198\n",
       "std        8.819312\n",
       "min     1925.000000\n",
       "25%     2013.000000\n",
       "50%     2017.000000\n",
       "75%     2019.000000\n",
       "max     2021.000000"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7771c2a7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "show_id         0\n",
       "type            0\n",
       "title           0\n",
       "director        0\n",
       "cast            0\n",
       "country         0\n",
       "date_added      0\n",
       "release_year    0\n",
       "rating          0\n",
       "duration        0\n",
       "listed_in       0\n",
       "description     0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.dropna(inplace=True)\n",
    "df.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "049ba45f",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.rename(columns={'listed_in':'genre'}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6ddfd7e7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>show_id</th>\n",
       "      <th>type</th>\n",
       "      <th>title</th>\n",
       "      <th>director</th>\n",
       "      <th>cast</th>\n",
       "      <th>country</th>\n",
       "      <th>date_added</th>\n",
       "      <th>release_year</th>\n",
       "      <th>rating</th>\n",
       "      <th>duration</th>\n",
       "      <th>genre</th>\n",
       "      <th>description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>s8</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Sankofa</td>\n",
       "      <td>Haile Gerima</td>\n",
       "      <td>Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...</td>\n",
       "      <td>United States, Ghana, Burkina Faso, United Kin...</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>1993</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>125 min</td>\n",
       "      <td>Dramas, Independent Movies, International Movies</td>\n",
       "      <td>On a photo shoot in Ghana, an American model s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>s9</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>The Great British Baking Show</td>\n",
       "      <td>Andy Devonshire</td>\n",
       "      <td>Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-14</td>\n",
       "      <td>9 Seasons</td>\n",
       "      <td>British TV Shows, Reality TV</td>\n",
       "      <td>A talented batch of amateur bakers face off in...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>s10</td>\n",
       "      <td>Movie</td>\n",
       "      <td>The Starling</td>\n",
       "      <td>Theodore Melfi</td>\n",
       "      <td>Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...</td>\n",
       "      <td>United States</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>PG-13</td>\n",
       "      <td>104 min</td>\n",
       "      <td>Comedies, Dramas</td>\n",
       "      <td>A woman adjusting to life after a loss contend...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>s13</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Je Suis Karl</td>\n",
       "      <td>Christian Schwochow</td>\n",
       "      <td>Luna Wedler, Jannis Niewöhner, Milan Peschel, ...</td>\n",
       "      <td>Germany, Czech Republic</td>\n",
       "      <td>September 23, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>127 min</td>\n",
       "      <td>Dramas, International Movies</td>\n",
       "      <td>After most of her family is murdered in a terr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>s25</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Jeans</td>\n",
       "      <td>S. Shankar</td>\n",
       "      <td>Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...</td>\n",
       "      <td>India</td>\n",
       "      <td>September 21, 2021</td>\n",
       "      <td>1998</td>\n",
       "      <td>TV-14</td>\n",
       "      <td>166 min</td>\n",
       "      <td>Comedies, International Movies, Romantic Movies</td>\n",
       "      <td>When the father of the man she loves insists t...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   show_id     type                          title             director  \\\n",
       "7       s8    Movie                        Sankofa         Haile Gerima   \n",
       "8       s9  TV Show  The Great British Baking Show      Andy Devonshire   \n",
       "9      s10    Movie                   The Starling       Theodore Melfi   \n",
       "12     s13    Movie                   Je Suis Karl  Christian Schwochow   \n",
       "24     s25    Movie                          Jeans           S. Shankar   \n",
       "\n",
       "                                                 cast  \\\n",
       "7   Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   \n",
       "8   Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   \n",
       "9   Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   \n",
       "12  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   \n",
       "24  Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...   \n",
       "\n",
       "                                              country          date_added  \\\n",
       "7   United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   \n",
       "8                                      United Kingdom  September 24, 2021   \n",
       "9                                       United States  September 24, 2021   \n",
       "12                            Germany, Czech Republic  September 23, 2021   \n",
       "24                                              India  September 21, 2021   \n",
       "\n",
       "    release_year rating   duration  \\\n",
       "7           1993  TV-MA    125 min   \n",
       "8           2021  TV-14  9 Seasons   \n",
       "9           2021  PG-13    104 min   \n",
       "12          2021  TV-MA    127 min   \n",
       "24          1998  TV-14    166 min   \n",
       "\n",
       "                                               genre  \\\n",
       "7   Dramas, Independent Movies, International Movies   \n",
       "8                       British TV Shows, Reality TV   \n",
       "9                                   Comedies, Dramas   \n",
       "12                      Dramas, International Movies   \n",
       "24   Comedies, International Movies, Romantic Movies   \n",
       "\n",
       "                                          description  \n",
       "7   On a photo shoot in Ghana, an American model s...  \n",
       "8   A talented batch of amateur bakers face off in...  \n",
       "9   A woman adjusting to life after a loss contend...  \n",
       "12  After most of her family is murdered in a terr...  \n",
       "24  When the father of the man she loves insists t...  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5e42992e",
   "metadata": {},
   "source": [
    "Splitting multiple genres into separate rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4dd26140",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['genre'] = df['genre'].str.split(', ')\n",
    "df = df.explode('genre')\n",
    "df.reset_index(drop=True, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "48699d48",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>show_id</th>\n",
       "      <th>type</th>\n",
       "      <th>title</th>\n",
       "      <th>director</th>\n",
       "      <th>cast</th>\n",
       "      <th>country</th>\n",
       "      <th>date_added</th>\n",
       "      <th>release_year</th>\n",
       "      <th>rating</th>\n",
       "      <th>duration</th>\n",
       "      <th>genre</th>\n",
       "      <th>description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>s8</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Sankofa</td>\n",
       "      <td>Haile Gerima</td>\n",
       "      <td>Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...</td>\n",
       "      <td>United States, Ghana, Burkina Faso, United Kin...</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>1993</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>125 min</td>\n",
       "      <td>Dramas</td>\n",
       "      <td>On a photo shoot in Ghana, an American model s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>s8</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Sankofa</td>\n",
       "      <td>Haile Gerima</td>\n",
       "      <td>Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...</td>\n",
       "      <td>United States, Ghana, Burkina Faso, United Kin...</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>1993</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>125 min</td>\n",
       "      <td>Independent Movies</td>\n",
       "      <td>On a photo shoot in Ghana, an American model s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>s8</td>\n",
       "      <td>Movie</td>\n",
       "      <td>Sankofa</td>\n",
       "      <td>Haile Gerima</td>\n",
       "      <td>Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...</td>\n",
       "      <td>United States, Ghana, Burkina Faso, United Kin...</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>1993</td>\n",
       "      <td>TV-MA</td>\n",
       "      <td>125 min</td>\n",
       "      <td>International Movies</td>\n",
       "      <td>On a photo shoot in Ghana, an American model s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>s9</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>The Great British Baking Show</td>\n",
       "      <td>Andy Devonshire</td>\n",
       "      <td>Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-14</td>\n",
       "      <td>9 Seasons</td>\n",
       "      <td>British TV Shows</td>\n",
       "      <td>A talented batch of amateur bakers face off in...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>s9</td>\n",
       "      <td>TV Show</td>\n",
       "      <td>The Great British Baking Show</td>\n",
       "      <td>Andy Devonshire</td>\n",
       "      <td>Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>September 24, 2021</td>\n",
       "      <td>2021</td>\n",
       "      <td>TV-14</td>\n",
       "      <td>9 Seasons</td>\n",
       "      <td>Reality TV</td>\n",
       "      <td>A talented batch of amateur bakers face off in...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  show_id     type                          title         director  \\\n",
       "0      s8    Movie                        Sankofa     Haile Gerima   \n",
       "1      s8    Movie                        Sankofa     Haile Gerima   \n",
       "2      s8    Movie                        Sankofa     Haile Gerima   \n",
       "3      s9  TV Show  The Great British Baking Show  Andy Devonshire   \n",
       "4      s9  TV Show  The Great British Baking Show  Andy Devonshire   \n",
       "\n",
       "                                                cast  \\\n",
       "0  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   \n",
       "1  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   \n",
       "2  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   \n",
       "3  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   \n",
       "4  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   \n",
       "\n",
       "                                             country          date_added  \\\n",
       "0  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   \n",
       "1  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   \n",
       "2  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   \n",
       "3                                     United Kingdom  September 24, 2021   \n",
       "4                                     United Kingdom  September 24, 2021   \n",
       "\n",
       "   release_year rating   duration                 genre  \\\n",
       "0          1993  TV-MA    125 min                Dramas   \n",
       "1          1993  TV-MA    125 min    Independent Movies   \n",
       "2          1993  TV-MA    125 min  International Movies   \n",
       "3          2021  TV-14  9 Seasons      British TV Shows   \n",
       "4          2021  TV-14  9 Seasons            Reality TV   \n",
       "\n",
       "                                         description  \n",
       "0  On a photo shoot in Ghana, an American model s...  \n",
       "1  On a photo shoot in Ghana, an American model s...  \n",
       "2  On a photo shoot in Ghana, an American model s...  \n",
       "3  A talented batch of amateur bakers face off in...  \n",
       "4  A talented batch of amateur bakers face off in...  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6f719004",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 11858 entries, 0 to 11857\n",
      "Data columns (total 12 columns):\n",
      " #   Column        Non-Null Count  Dtype \n",
      "---  ------        --------------  ----- \n",
      " 0   show_id       11858 non-null  object\n",
      " 1   type          11858 non-null  object\n",
      " 2   title         11858 non-null  object\n",
      " 3   director      11858 non-null  object\n",
      " 4   cast          11858 non-null  object\n",
      " 5   country       11858 non-null  object\n",
      " 6   date_added    11858 non-null  object\n",
      " 7   release_year  11858 non-null  int64 \n",
      " 8   rating        11858 non-null  object\n",
      " 9   duration      11858 non-null  object\n",
      " 10  genre         11858 non-null  object\n",
      " 11  description   11858 non-null  object\n",
      "dtypes: int64(1), object(11)\n",
      "memory usage: 1.1+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df9a3520",
   "metadata": {},
   "source": [
    "### What is the ration of Movies vs TV Shows on Netflix?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "015f1244",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      type  count\n",
      "0    Movie  11491\n",
      "1  TV Show    367\n"
     ]
    }
   ],
   "source": [
    "df['type'] = df['type'].astype('category')\n",
    "type_counts = df['type'].value_counts().reset_index()\n",
    "print(type_counts)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "2c409170",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAnYAAAHWCAYAAAD6oMSKAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAP1BJREFUeJzt3Qm8TWX////PMR1T5rmEIlOiKCmRCCmlqESopBIiSqkoTUpxRwPVfYeKou5IKkNUuhEiMmSoFBFHmZV5/x/v6/9d+7f3GTjnOOPl9Xw8tm2vde211h7O3u99TSsmFAqFDAAAANlejsw+AAAAAKQNgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAkU8WKFe22225L9/38+uuvFhMTY2PHjg0v034LFixoGUX7f+KJJzJsf6eKxYsX2yWXXGIFChRwz/GyZcvc86z/Z8Z7Df4h2AGp8PPPP9vdd99tZ511luXNm9cKFSpkl156qY0YMcL++eefdNvv6tWr3ZeAvvjT299//+329dVXX52wrL6E9MV0oktkUMlsl19+efi4cuTI4V7DqlWrWqdOnWzWrFlptp/PPvssywakrHxs6U2hSa/9eeedZ4mdWVPrevbsmaptP/vsszZlypQEyw8fPmw33nij7dixw/71r3/ZO++8YxUqVEjVPoCk5EpyDYBEffrpp+7DOTY21jp37mznnnuuHTp0yP73v//Zgw8+aKtWrbI33ngj3YLd4MGDXShRmErvYKd9ifZ3PC+99JLt27cvKjC899577surRIkS4eWqqchKzjjjDBsyZIj7//79++2nn36yjz76yN5991276aab3HXu3LnD5deuXetCYErouXj11VdTFKD0Za8fCJH7Tg/HOzbtP1cu/78iVqxY4V7ztm3bptk2FezatWtnbdq0SfCD8LfffrM333zT7rzzzuNuIzXvNUD8/6sF0tCGDRusffv27ot3zpw5VrZs2fC6Hj16uGCg4Heqif8FtnXrVhfstDy9A+jJKFy4sN16661Ry5577jm777777LXXXnPH/vzzz4fXKcynpyNHjtixY8csT548riY4M2X2/jNCvnz5rHz58vbkk0/aDTfckKA5NK3FxcW56yJFipywbHq/1+Avfg4AKTB06FBXM/Wf//wnKtQFKleubL179476on7qqafs7LPPdh/UCgqPPPKIHTx4MOp+Wn7NNde4Wr+LLrrIfamqmfftt98Ol1EzpmoKpUmTJuFmxMim0s8//9wuu+wy13/ntNNOs6uvvtrVIEYK+mpt3rzZBS/9v2TJkvbAAw/Y0aNHXRk19WqZqNYu2Fdqm+0ef/xxV/u0ffv2BOvuuusu90V34MCBqOdi5syZVqdOHfdc1KhRw9WqxLdr1y7r06eP+3LW86vnX0FM4Si1cubMaSNHjnT7fOWVV2z37t1J9ntS05qenypVqrjjLF68uDVs2DDclKuyqhGTyCbpyH50L774oqvxDN4jqpVNrI9d4JdffrEWLVq417hcuXIulEQ2Jer9EP99Ebm/YJvHO7ZgWfzX+/vvv7errrrKNVvrfdO0aVP79ttvo8po+7rvvHnzrG/fvu59pGO9/vrrE339E6MfTcH7WO+N6667zn788ceoMkG/NP2Y0mNROQX122+/3dU2J4dqxB577DH74YcfbPLkyScsr79bvZf1PtNrpfdd//79o/6edUyq/R03blz4OdXx6dK4cWNXRn/HWn68mvDI95peX/3N67kMwqGopaBWrVruvaN9AkKwA1Lgk08+cYEruU2Kam4ZNGiQXXDBBa5ZUh/savpTrV98+oJS882VV15pw4YNs6JFi7oP9iCYNWrUyNUkicKh+ufoUr16dbdM/1eQ0xeuws3AgQNdSFDQiN8nTwFO4UBBRMFCx6V9Bk3I+gIZNWqU+7++kIN9qVYjNdRvTSF34sSJUcv1xfThhx+6ZrDIGqL169fbzTff7EKEni81CerLMLLvm768ddxqLlWTuMKY+jkOGDDABYqToXB3yy23uH0obCdF4ULBTl+6CoGPPvqonXnmmbZ06VK3Xv0w9XpK8BzqEmnMmDH28ssvu4Cr16BYsWJJ7k+vW8uWLa106dLuR0bdunVd0NAlpZJzbJH0PlTYWr58uQszen+pBlvhZOHChQnK9+rVy5XVsXXv3t397SSnz9oXX3zh3psKMHp+9VrOnz/fvbaJ9S1Vk/nevXvd+0T/V7AMuhAkR4cOHVwwjx+Q49OPhWuvvdb9vbRu3dq9ZvphpL9rvVcDeg4V+vRcBc+pnmtd9Hcr+jvWcr1fkkMh8K233nI/fu65557wcj23el30HlIIBpwQgGTZvXu3PvVD1113XbLKL1u2zJW/8847o5Y/8MADbvmcOXPCyypUqOCWzZ07N7wsLi4uFBsbG+rXr1942QcffODKffnll1Hb3Lt3b6hIkSKhbt26RS3funVrqHDhwlHLu3Tp4rbx5JNPRpU9//zzQ3Xr1g3f3r59uyv3+OOPh1LqhRdecPfdsGFDeFmDBg1C9evXjyr30UcfJXg8wXPx3//+N+q5L1u2rDvGwFNPPRUqUKBAaN26dVHbfPjhh0M5c+YMbdy48bjH2Lhx41DNmjWTXD958mR3HCNGjIg6Nj1/gdq1a4euvvrq4+6nR48ebjvx6bnR8kKFCrnXOrF1Y8aMSfC69erVK7zs2LFjbv958uRxr5fouUzsPZLYNpM6Non/2rdp08bt5+effw4v27JlS+i0004LNWrUKLxM29d9mzVr5o4vcP/997vXZdeuXcd9vurUqRMqVapU6K+//govW758eShHjhyhzp07h5fp2LSfO+64I+r+119/fah48eKhE9HzqfePjBs3zm1L78fIx6/nJ/DOO++4Y/jmm2+itjN69GhXdt68eeFl2m7k+yQQvDb6O44UPJZI8d9r8vrrr7ty7777bujbb791z2efPn1O+FhxaqHGDkimPXv2uGs1cSa3Y7rErz3q16+fu47fF09Nf/qVH1CtmUZpquntRFSTpWZJ1TL9+eef4YtqnurXr29ffvllgvtE/vIX7Ts5+0ot1aqpZkcdyAPjx493zVlBE1VATYyqKQyo6U/3V1Og+u/JBx984I5ZNZuRj7lZs2auZmvu3LkndbzB1CKqDUqKmv9UY6IaxtRSbWXQ7J0ckbVewchN1Xyqpiu96PlU07hqqFRjHVB3BNV4qVYz+PsIqAYysmlXr5W2o8EDSfnjjz/c9B+qqY6sudTIVdUuBn9TJ3of//XXXwmO53g6dux4wlo7vd9UO16tWrWo99sVV1zh1if2N5bW9JyqNlO1oaoFVxOsBmoAkQh2QDIpXJzoiz6SvsDUh0f9cSKVKVPGBYL4X3BqwotPoWXnzp0n3FcQLPQlo5AQedEXcmS/HFGzZ/wwkdx9pZaaq9REpTAn6rs2bdo096Uav9O6nrP4y8455xx3HTTH6TFPnz49weNVsJP4jzmlglG+xwvyCgIK1Do29XXSqGj110qJSpUqJbus3k+RwSqx5yU9qG+cmqX1QyM+hR01U27atOm472e9v+R477HgbyKp/ShIxe9Llpr9xKcfQOprp1CZ2DQlwftNIT7++y14/k/2/ZZc6t+r10LHo2ZnDQABIjEqFkhBsFNN0sqVK1N0v+SOtNOXS2KO1+8nEAwWUL8dBcf44k9bkdS+0pO+cDUoQsFO/Q7Vt06dzuOPSk0uPWbV4qi/V2KCL9zUCl7n+ME8kvo9qgby448/dgH63//+t+tzNXr06BNOZxFI6y/mpN5vwcCYjHIy7+fM2I9+YGigk8J6/FHewftN4X348OGJ3l81zxlBg2KCwRqaqqVBgwYZsl9kHwQ7IAUUTDTAYMGCBSf8QNWUKPoy0C/rYICDbNu2zdXypGZi0qS+tNUkI6VKlQrXWJ2s9Jj6Qc2pGuGo2fcV8M4//3yrWbNmogNJ9MUceQzr1q1z18H0KXrMqlVLq8cbPwRNmDDB8ufP7wafHI+aDDUSUxcdj8KeOv0HwS4tn0e9n9RcHhla4z8vQY2V3mOREmsCTe6xqWZKz4XmVotvzZo1riYxLYJN8DeR1H40J2J6DRIIau3UDKygHp/ebxoMopHAJ3re0mvaFDVVqxm2efPmbkocjWRX0yyTHCMSTbFACqh2SF8s+tJWQItPtTc6+4S0atXKXWsqi0jBL36NYE2p4Est/pe2PtxVo6j+NpqCI77kTjMRSV/kie3rZGiUq76cNWr366+/TrK2bsuWLVHTT6i/lKZ+0fQnQY2kRkAqYM+YMSPB/XXMGoWb2lCnUYuaXkPXQRN8YtSXK36/PNXwRU5/kdRrlloafRtQ+NVtTSWjwCH6kldIid/HUPPyxZfcY9P2FCYUeCKbfPU3oACs8Hu85ym51GdPr7GmCok8JtWeqkY0+JtKL3o/6vVLbFSt3m+aIkiTCyc2mXNkE7Ge17T8uwl069bNhXs1x+oHpmriu3btmua1oMjeqLEDUkC/2vVFpv5iqoWLPPOEpmRQB+tg7qnatWtbly5d3AewPuQ1QGDRokXuS0tNPZoiI6X0pacvWQUj9VFTnzX1q1NNnaYnUYdqTa2i6VRUy7Jx40Y3SENTRUQGguQ2EWpAh6YoUQ2Raqb0WHVJLQUQHZuOJZhSJDHan76wVLOnqT001YNChKZ1CKg/29SpU10tqp5zTf2hL1c1T6mZVwEk8qwXidFzqOlSRP2WgjNPKKDrONU0dzx6fjTdh/at5+e7775z+44c4KB1opCoAK7Hndh0N8mhvpHqV6j3lQbFaN5Cvb6aRiPoM6m53DQ1jKbjUM2R3rPqy5hYH7CUHNvTTz/tBukoxN17770uVLz++usuxGrqlbTywgsvuB8AqhHXe0ChSY9Fjyu9T3+mx68pSFT7Gp/+tiZNmuQGa2ighP6m9CNANYlarh8Y9erVCz+vGsyiH3HqvqF+lHq9Tobe+3qt1a9OZ0wRPS8Ko/rb12sCOJk9LBfIjjTFhqYQqVixopsCQlM+XHrppaGXX345dODAgXC5w4cPhwYPHhyqVKlSKHfu3KHy5cuHBgwYEFUmmNogsWkzNCWHLpHefPPN0FlnneWmOog/rYX+36JFCzfFSd68eUNnn3126Lbbbgt99913iU7zcKIpF+bPn++mQNFjTMnUJ4lNdxJYtGiRW9e8efNE7xs8FzNmzAidd955bsqXatWqJZgiIpjmRc9n5cqV3TGWKFEidMkll4RefPHF0KFDh457jHpedRzBpWDBgqEqVaqEbr311tDMmTOTPLbIKSiefvrp0EUXXeSmmsmXL587zmeeeSZq30eOHHFTlJQsWTIUExMTfo6D6Uf0XMWX1HQnet003Yieu/z584dKly7tXpOjR49G3V9Tn7Rt29aVKVq0aOjuu+8OrVy5MsE2kzo2Sez1Xrp0qXt/6bnStps0aeLeI5GC6U4WL14ctTypaVgS88UXX7i/Jz2nmg6mdevWodWrVyf6fg2meYm//8Tee5GS+jvQ36z+buJPdyJ6XZ9//nk3TY7el3pu9fehv3FNyRNYs2aNmwJGx6/tBO+Z1E53smnTJvc3rechPk3vosfxyy+/HPfx4tQRo3/IuAAyivopqeZRTauqBYlPfcVUK6haJgBAytDHDkCGUh8l9UVL7VksAABJo48dgAyhU0rpFGfqc6g+aJwCCQDSHsEOQIbQNA0aAKGRjSk5lycAIPnoYwcAAOAJ+tgBAAB4IlODnSbQbN26tZvnR/MtRZ6jT5OsPvTQQ+4ULuqLozKaM0wTl0basWOHOxWMJsfU+Tc171FwjseAzt2oE0NrDijNjp7YnEuaf0wnd1YZ7TOxk00DAABkZZnax06TiWoS1zvuuCPBCDlNFrp06VIbOHCgK6MTOvfu3duuvfZaNwloQKFOp1nRxJkKg5pY8q677nKTyAYz1mvGdJ12SOdv1OSl2p9CoMqJJpbVRKlDhgxxk53qvppAVvtP7mSsmg1coVMnDE+v08kAAIBTTygUsr1797pKLp3C70SFswQdyuTJk49bJpjY9LfffnO3NWFl/IkwP//8czfR5ubNm93t1157zU0iefDgwXCZhx56KFS1atXw7ZtuuinB5LD169d3k3omlyaQjJzslAsXLly4cOHCxdLwoqxxItlqVKxO/6PaMNW2ic4Tqf8Hp3ER1cwpzS5cuNCuv/56V0Yn5dYJkwM6dY5OyaRaQJ0wW2X69u0btS+ViWwajk+n0Yk8H2QwBmXTpk1pcs5EAACAoPVRXcnUKngi2SbYHThwwPW5U5NpEJy2bt3qzpEZSecv1DkbtS4oo/P0RdK5J4N1Cna6DpZFlgm2kRg12yY2ZYOOjWAHAADSWnK6emWLUbHqO3fTTTe5WjGd7DgrGDBggKtBDC6qqQMAAMhMubJLqPvtt99szpw5UbVhZcqUsbi4uKjyR44ccSNltS4oo0lRIwW3T1QmWJ+Y2NhYdwEAAMgqcmSHULd+/Xr74osvrHjx4lHrGzRoYLt27bIlS5aElyn8aYRq/fr1w2U0rYq2FdAI2qpVq7pm2KDM7Nmzo7atMloOAACQXWRqsNN8c8uWLXMX2bBhg/v/xo0bXRBr166dm9pk/PjxdvToUdfnTZdDhw658tWrV7eWLVtat27dbNGiRTZv3jx3Dsr27du7IcHSoUMHN3BC89utWrXKJk6caCNGjIgaLKFpVKZPn27Dhg2zNWvW2BNPPOH2q20BAABkG6FM9OWXXyY6nLdLly6hDRs2JDncV/cL/PXXX6FbbrklVLBgwVChQoVCt99+e2jv3r1R+1m+fHmoYcOGodjY2NDpp58eeu655xIcy6RJk0LnnHNOKE+ePKGaNWuGPv300xQ9lt27d7tj0zUAAEBaSUnG4FyxaTgUuXDhwm4gBaNiAQBAZmSMLN3HDgAAAMlHsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ESuzD4ApM6Hi7Zn9iEAXmp3UcnMPgQASDVq7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwRKYGu7lz51rr1q2tXLlyFhMTY1OmTIlaHwqFbNCgQVa2bFnLly+fNWvWzNavXx9VZseOHdaxY0crVKiQFSlSxLp27Wr79u2LKvPDDz/YZZddZnnz5rXy5cvb0KFDExzLBx98YNWqVXNlatWqZZ999lk6PWoAAAAPg93+/futdu3a9uqrrya6XgFs5MiRNnr0aFu4cKEVKFDAWrRoYQcOHAiXUahbtWqVzZo1y6ZNm+bC4l133RVev2fPHmvevLlVqFDBlixZYi+88II98cQT9sYbb4TLzJ8/32655RYXCr///ntr06aNu6xcuTKdnwEAAIC0ExNStVgWoBq7yZMnu0AlOizV5PXr188eeOABt2z37t1WunRpGzt2rLVv395+/PFHq1Gjhi1evNjq1avnykyfPt1atWplv//+u7v/qFGj7NFHH7WtW7danjx5XJmHH37Y1Q6uWbPG3b755ptdyFQwDFx88cVWp04dFyqTQwGycOHC7hhVe5jePly0Pd33AZyK2l1UMrMPAQBSnTGybB+7DRs2uDCm5teAHlT9+vVtwYIF7rau1fwahDpR+Rw5crgavqBMo0aNwqFOVOu3du1a27lzZ7hM5H6CMsF+EnPw4EH3REdeAAAAMlOWDXYKdaIauki6HazTdalSpaLW58qVy4oVKxZVJrFtRO4jqTLB+sQMGTLEBc3gor57AAAAmSnLBrusbsCAAa5KNLhs2rQpsw8JAACc4rJssCtTpoy73rZtW9Ry3Q7W6TouLi5q/ZEjR9xI2cgyiW0jch9JlQnWJyY2Nta1c0deAAAAMlOWDXaVKlVywWr27NnhZerHpr5zDRo0cLd1vWvXLjfaNTBnzhw7duyY64sXlNFI2cOHD4fLaARt1apVrWjRouEykfsJygT7AQAAyA4yNdhpvrlly5a5SzBgQv/fuHGjGyXbp08fe/rpp23q1Km2YsUK69y5sxvpGoycrV69urVs2dK6detmixYtsnnz5lnPnj3diFmVkw4dOriBE5rKRNOiTJw40UaMGGF9+/YNH0fv3r3daNphw4a5kbKaDuW7775z2wIAAMgucmXmzhWemjRpEr4dhK0uXbq4KU369+/vpiHRvHSqmWvYsKELYJpEODB+/HgXwJo2bepGw7Zt29bNfRfQwIaZM2dajx49rG7dulaiRAk36XHkXHeXXHKJTZgwwR577DF75JFHrEqVKm46lHPPPTfDngsAAABv5rHL7pjHDvAD89gByGq8mMcOAAAAKUOwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE9k6WB39OhRGzhwoFWqVMny5ctnZ599tj311FMWCoXCZfT/QYMGWdmyZV2ZZs2a2fr166O2s2PHDuvYsaMVKlTIihQpYl27drV9+/ZFlfnhhx/ssssus7x581r58uVt6NChGfY4AQAAvA92zz//vI0aNcpeeeUV+/HHH91tBa6XX345XEa3R44caaNHj7aFCxdagQIFrEWLFnbgwIFwGYW6VatW2axZs2zatGk2d+5cu+uuu8Lr9+zZY82bN7cKFSrYkiVL7IUXXrAnnnjC3njjjQx/zAAAAKkVE4qs/spirrnmGitdurT95z//CS9r27atq5l79913XW1duXLlrF+/fvbAAw+49bt373b3GTt2rLVv394Fwho1atjixYutXr16rsz06dOtVatW9vvvv7v7Kzw++uijtnXrVsuTJ48r8/DDD9uUKVNszZo1yTpWhcPChQu7/atmML19uGh7uu8DOBW1u6hkZh8CAKQ6Y2TpGrtLLrnEZs+ebevWrXO3ly9fbv/73//sqquucrc3bNjgwpiaXwN64PXr17cFCxa427pW82sQ6kTlc+TI4Wr4gjKNGjUKhzpRrd/atWtt586dGfZ4AQAATkYuy8JUa6aUWq1aNcuZM6frc/fMM8+4plVRqBPV0EXS7WCdrkuVKhW1PleuXFasWLGoMurHF38bwbqiRYsmOLaDBw+6S0DHCQAAkJmydI3dpEmTbPz48TZhwgRbunSpjRs3zl588UV3ndmGDBniageDiwZcAAAAZKYsHewefPBBV2unvnK1atWyTp062f333+9ClZQpU8Zdb9u2Lep+uh2s03VcXFzU+iNHjriRspFlEttG5D7iGzBggGvrDi6bNm1Ks8cNAADgXbD7+++/XV+4SGqSPXbsmPu/mk8VvNQPL7JJVH3nGjRo4G7reteuXW60a2DOnDluG+qLF5TRSNnDhw+Hy2gEbdWqVRNthpXY2FjXgTHyAgAAkJmydLBr3bq161P36aef2q+//mqTJ0+24cOH2/XXX+/Wx8TEWJ8+fezpp5+2qVOn2ooVK6xz585upGubNm1cmerVq1vLli2tW7dutmjRIps3b5717NnT1QKqnHTo0MENnND8dpoWZeLEiTZixAjr27dvpj5+AAAAbwZPaL46TVB87733uuZUBbG7777bTUgc6N+/v+3fv9/NS6eauYYNG7rpTDTRcED99BTmmjZt6moANWWK5r4LqI/czJkzrUePHla3bl0rUaKE20fkXHcAAABZXZaexy47YR47wA/MYwcgq/FmHjsAAAAkH8EOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADgVA52Z511lv31118Jlu/atcutAwAAQDYJdr/++qsdPXo0wfKDBw/a5s2b0+K4AAAAkEK5UlJ46tSp4f/PmDHDChcuHL6toDd79myrWLFiSo8BAAAAGR3s2rRp465jYmKsS5cuUety587tQt2wYcPS4rgAAACQnsHu2LFj7rpSpUq2ePFiK1GiREr3BwAAgKwQ7AIbNmxI+yMBAABAxgc7UX86XeLi4sI1eYG33nrr5I4KAAAAGRPsBg8ebE8++aTVq1fPypYt6/rcAQAAIBsGu9GjR9vYsWOtU6dOaX9EAAAAyLh57A4dOmSXXHJJ6vYIAACArBPs7rzzTpswYULaHw0AAAAytin2wIED9sYbb9gXX3xh5513npvDLtLw4cNTf0QAAADIuGD3ww8/WJ06ddz/V65cGbWOgRQAAADZKNh9+eWXaX8kAAAAyPg+dgAAAPAk2DVp0sSuuOKKJC9pafPmzXbrrbda8eLFLV++fFarVi377rvvwutDoZANGjTIzaen9c2aNbP169dHbWPHjh3WsWNHK1SokBUpUsS6du1q+/btS9C8fNlll1nevHmtfPnyNnTo0DR9HAAAAFky2Kl/Xe3atcOXGjVquClQli5d6oJXWtm5c6ddeumlbnDG559/bqtXr7Zhw4ZZ0aJFw2UUwEaOHOnm1lu4cKEVKFDAWrRo4QZ4BBTqVq1aZbNmzbJp06bZ3Llz7a677gqv37NnjzVv3twqVKhgS5YssRdeeMGeeOIJN0AEAAAgu4gJqcorjSgMqSbsxRdfTJPtPfzwwzZv3jz75ptvEl2vQy9Xrpz169fPHnjgAbds9+7dVrp0aTeBcvv27e3HH390wXPx4sXuTBkyffp0a9Wqlf3+++/u/qNGjbJHH33Utm7danny5Anve8qUKbZmzZpkHavCYeHChd3+VTOY3j5ctD3d9wGcitpdVDKzDwEAUp0x0rSPnZpM0/I8sVOnTnVh7MYbb7RSpUrZ+eefb2+++WZ4/YYNG1wYU/NrQA+8fv36tmDBAndb12p+DUKdqHyOHDlcDV9QplGjRuFQJ6r1W7t2ras1BAAAyA7SNNgpIKmPWlr55ZdfXG1alSpVbMaMGda9e3e77777bNy4cW69Qp2ohi6SbgfrdK1QGClXrlxWrFixqDKJbSNyH/EdPHjQJejICwAAQLab7uSGG25I0CT6xx9/uEENAwcOTKtjs2PHjrmatmeffdbdVo2d5s1Tf7ouXbpYZhoyZIgNHjw4U48BAADgpGvs1NwZeVHt1+WXX26fffaZPf7445ZWNNJV/eMiVa9e3TZu3Oj+X6ZMGXe9bdu2qDK6HazTdVxcXNT6I0eOuJGykWUS20bkPuIbMGCAa+sOLps2bTrJRwsAAJAJNXZjxoyxjKARsernFmndunVu9KpUqlTJBa/Zs2eHz4ShJlH1nVOzrTRo0MB27drlRrvWrVvXLZszZ46rDVRfvKCMBk8cPnw4fHo0jaCtWrVq1AjcSLGxse4CAADgRR87haV3333XXb7//ntLa/fff799++23rin2p59+sgkTJrgpSHr06BE+fVmfPn3s6aefdgMtVqxYYZ07d3YjXdu0aROu4WvZsqV169bNFi1a5EbZ9uzZ042YVTnp0KGDGzih+e00LcrEiRNtxIgR1rdv3zR/TAAAAFmqxk5NmwpGX331lRtxKqoV08TF77//vpUsmTbTBVx44YU2efJk1+z55JNPuhq6l156yc1LF+jfv7/t37/fzUunY2jYsKGbziRyEMf48eNdmGvatKkbDdu2bVs3911AzckzZ850gVG1eiVKlHCTHkfOdQcAAODlPHY333yzG7H69ttvuxox0eTBGtBQuXJle++99+xUwzx2gB+Yxw5Ads4YqaqxU43YF198EQ51okEOr776qjuDAwAAALJJHzsNPAgGGUTSMq0DAABANgl2V1xxhfXu3du2bNkSXrZ582Y32EH92AAAAJBNgt0rr7zi2nsrVqxoZ599trtoYIOWvfzyy2l/lAAAADihVPWxK1++vC1dutT1s1uzZo1bpv52kedsBQAAQBausdPEvhokoZo5zSF35ZVXWq9evdxFU5PUrFnTvvnmm/Q7WgAAAKRNsNMccproN7GhthqGe/fdd9vw4cNTskkAAABkRrBbvny5O4tDUjTVic5GAQAAgCwe7LZt25boNCeBXLly2fbtTJwLAACQ5YPd6aefbitXrkxy/Q8//GBly5ZNi+MCAABAega7Vq1a2cCBA+3AgQMJ1v3zzz/2+OOP2zXXXJPSYwAAAEBGT3fy2GOP2UcffWTnnHOO9ezZ06pWreqWa8oTnU7s6NGj9uijj6bFcQEAACA9g13p0qVt/vz51r17dxswYICFQiG3XFOftGjRwoU7lQEAAEA2mKC4QoUK9tlnn9nOnTvtp59+cuGuSpUqVrRo0fQ5QgAAAKTfmSdEQU6TEgMAACAbnysWAAAAWQ/BDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBPZKtg999xzFhMTY3369AkvO3DggPXo0cOKFy9uBQsWtLZt29q2bdui7rdx40a7+uqrLX/+/FaqVCl78MEH7ciRI1FlvvrqK7vgggssNjbWKleubGPHjs2wxwUAAHBKBbvFixfb66+/buedd17U8vvvv98++eQT++CDD+zrr7+2LVu22A033BBef/ToURfqDh06ZPPnz7dx48a50DZo0KBwmQ0bNrgyTZo0sWXLlrngeOedd9qMGTMy9DECAAB4H+z27dtnHTt2tDfffNOKFi0aXr579277z3/+Y8OHD7crrrjC6tata2PGjHEB7ttvv3VlZs6caatXr7Z3333X6tSpY1dddZU99dRT9uqrr7qwJ6NHj7ZKlSrZsGHDrHr16tazZ09r166d/etf/8q0xwwAAOBlsFNTq2rUmjVrFrV8yZIldvjw4ajl1apVszPPPNMWLFjgbuu6Vq1aVrp06XCZFi1a2J49e2zVqlXhMvG3rTLBNhJz8OBBt43ICwAAQGbKZVnc+++/b0uXLnVNsfFt3brV8uTJY0WKFIlarhCndUGZyFAXrA/WHa+Mwto///xj+fLlS7DvIUOG2ODBg9PgEQIAAJwCNXabNm2y3r172/jx4y1v3ryWlQwYMMA1BQcXHSsAAEBmytLBTk2tcXFxbrRqrly53EUDJEaOHOn+r1o19ZPbtWtX1P00KrZMmTLu/7qOP0o2uH2iMoUKFUq0tk40elbrIy8AAACZKUsHu6ZNm9qKFSvcSNXgUq9ePTeQIvh/7ty5bfbs2eH7rF271k1v0qBBA3db19qGAmJg1qxZLojVqFEjXCZyG0GZYBsAAADZQZbuY3faaafZueeeG7WsQIECbs66YHnXrl2tb9++VqxYMRfWevXq5QLZxRdf7NY3b97cBbhOnTrZ0KFDXX+6xx57zA3IUK2b3HPPPfbKK69Y//797Y477rA5c+bYpEmT7NNPP82ERw0AAOBhsEsOTUmSI0cONzGxRqpqNOtrr70WXp8zZ06bNm2ade/e3QU+BcMuXbrYk08+GS6jqU4U4jQn3ogRI+yMM86wf//7325bAAAA2UVMKBQKZfZB+EAjaAsXLuwGUmREf7sPF21P930Ap6J2F5XM7EMAgFRnjCzdxw4AAADJR7ADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPJGlg92QIUPswgsvtNNOO81KlSplbdq0sbVr10aVOXDggPXo0cOKFy9uBQsWtLZt29q2bduiymzcuNGuvvpqy58/v9vOgw8+aEeOHIkq89VXX9kFF1xgsbGxVrlyZRs7dmyGPEYAAIBTIth9/fXXLrR9++23NmvWLDt8+LA1b97c9u/fHy5z//332yeffGIffPCBK79lyxa74YYbwuuPHj3qQt2hQ4ds/vz5Nm7cOBfaBg0aFC6zYcMGV6ZJkya2bNky69Onj9155502Y8aMDH/MAAAAqRUTCoVClk1s377d1bgpwDVq1Mh2795tJUuWtAkTJli7du1cmTVr1lj16tVtwYIFdvHFF9vnn39u11xzjQt8pUuXdmVGjx5tDz30kNtenjx53P8//fRTW7lyZXhf7du3t127dtn06dOTdWx79uyxwoULu2MqVKiQpbcPF21P930Ap6J2F5XM7EMAgFRnjCxdYxefHpAUK1bMXS9ZssTV4jVr1ixcplq1anbmmWe6YCe6rlWrVjjUSYsWLdyTtGrVqnCZyG0EZYJtJObgwYNuG5EXAACAzJRtgt2xY8dcE+mll15q5557rlu2detWV+NWpEiRqLIKcVoXlIkMdcH6YN3xyiis/fPPP0n2/1N6Di7ly5dPw0cLAADgcbBTXzs1lb7//vuWFQwYMMDVIAaXTZs2ZfYhAQCAU1wuywZ69uxp06ZNs7lz59oZZ5wRXl6mTBk3KEJ94SJr7TQqVuuCMosWLYraXjBqNrJM/JG0uq127Hz58iV6TBo9qwsAAEBWkaVr7DSuQ6Fu8uTJNmfOHKtUqVLU+rp161ru3Llt9uzZ4WWaDkXTmzRo0MDd1vWKFSssLi4uXEYjbBXaatSoES4TuY2gTLANAACA7CBXVm9+1YjXjz/+2M1lF/SJU5821aTpumvXrta3b183oEJhrVevXi6QaUSsaHoUBbhOnTrZ0KFD3TYee+wxt+2gxu2ee+6xV155xfr372933HGHC5GTJk1yI2UBAACyiyw93UlMTEyiy8eMGWO33XZbeILifv362XvvvedGqmo062uvvRZuZpXffvvNunfv7iYhLlCggHXp0sWee+45y5Xr/+VardOceKtXr3bNvQMHDgzvIzmY7gTwA9OdAMhqUpIxsnSwy04IdoAfCHYAshpv57EDAABA0gh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAncmX2AQAA0teu6S9n9iEAXirSspdlNdTYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgl08r776qlWsWNHy5s1r9evXt0WLFmX2IQEAACQLwS7CxIkTrW/fvvb444/b0qVLrXbt2taiRQuLi4vL7EMDAAA4IYJdhOHDh1u3bt3s9ttvtxo1atjo0aMtf/789tZbb2X2oQEAAJwQwe7/HDp0yJYsWWLNmjULL8uRI4e7vWDBgkw9NgAAgOTglGL/588//7SjR49a6dKlo5br9po1axKUP3jwoLsEdu/e7a737NmTAUdr9ve+vRmyH+BUs2dPrPlmz/5/MvsQAC/lyKDv/CBbhEKhE5Yl2KXSkCFDbPDgwQmWly9fPlOOBwAAZLSHMnRve/futcKFCx+3DMHu/5QoUcJy5sxp27Zti1qu22XKlElQfsCAAW6gReDYsWO2Y8cOK168uMXExGTIMSPr068shf1NmzZZoUKFMvtwAGRxfGYgMaqpU6grV66cnQjB7v/kyZPH6tata7Nnz7Y2bdqEw5pu9+zZM0H52NhYd4lUpEiRDDteZC/6gOZDGkBy8ZmB+E5UUxcg2EVQDVyXLl2sXr16dtFFF9lLL71k+/fvd6NkAQAAsjqCXYSbb77Ztm/fboMGDbKtW7danTp1bPr06QkGVAAAAGRFBLt41OyaWNMrkBpqrteE1/Gb7QEgMXxm4GTFhJIzdhYAAABZHhMUAwAAeIJgBwAA4AmCHZAFaO7DKVOmZPZhAMhCbrvttvD0W0ByEeyAJD5QFbbuueeeBOt69Ojh1qlMWvnjjz/sqquuSrPtATh5+js/3qV169bu+ttvv030/k2bNrUbbrghye2/+eabVrt2bStYsKCbB/X88893ZzUCTgbBDkiCZn9///337Z9//t95Ng8cOGATJkywM888M033pbObMAoOyFr0gyu4aF5TTRgcuey9995zweytt95KcN9ff/3VvvzyS+vatWui29Z9+vTpY/fdd58tW7bM5s2bZ/3797d9+/ZlwCODzwh2QBIuuOACF+4++uij8DL9X6FOv6wDBw8edB/OpUqVsrx581rDhg1t8eLF4bOXnHHGGTZq1KiobX///feWI0cO++233xJtitXphG666Sb3K75YsWJ23XXXuS8KABlHP7iCi2b9199p5DLVtCm4TZw40f7++++o+44dO9bKli1rLVu2THTbU6dOdX/jun/lypWtZs2adsstt9gzzzyToOyLL77otqVTVqrF4PDhw+F1O3futM6dO1vRokUtf/78ruZ//fr1bp0mvShZsqR9+OGH4fKan1XbCvzvf/9zPyrjHz+yL4IdcBx33HGHjRkzJupXdvwzkehX9n//+18bN26cLV261H1It2jRwp07WOFNH9aq5Ys0fvx4u/TSS61ChQoJ9qkPbd3/tNNOs2+++cb9ktcXiL4gDh06lI6PFkBKdezY0f24iwxPClT6PFB3DZ2DPDEKhmrCDX7cJUW1fj///LO71jYVGHUJaB/fffedC4oLFixw+27VqpX7HFEQbdSokX311VfhEPjjjz+6Vog1a9a4ZV9//bVdeOGFLhTCE5rHDkC0Ll26hK677rpQXFxcKDY2NvTrr7+6S968eUPbt29361Rm3759ody5c4fGjx8fvu+hQ4dC5cqVCw0dOtTd/v7770MxMTGh3377zd0+evRo6PTTTw+NGjUqfB/9KU6ePNn9/5133glVrVo1dOzYsfD6gwcPhvLlyxeaMWNGBj4LAAJjxowJFS5cONF17du3DzVu3Dh8e/bs2e5vev369Ulub8uWLaGLL77YlTvnnHPc58nEiRPd50NAyypUqBA6cuRIeNmNN94Yuvnmm93/161b5+4/b9688Po///zTfVZMmjTJ3R45cmSoZs2a7v9TpkwJ1a9f331+BZ8/zZo1Cz3yyCMn8cwgq6HGDjgONWNcffXV7heyau70/xIlSoTX65e0fhmr9i2QO3dud65h/TIOmj6qV68errXTL+S4uDi78cYbE93n8uXL7aeffnI1dqqp00XNserfp/0ByHo1+3Pnzg3/fapmv3Hjxq72PilqDlUN24oVK6x379525MgRd65y1cyrC0dATbSRtX66nz4/RJ8xuXLlsvr164fXq7m2atWq4c8fHcfq1avd6TL12XP55Ze7i2rx9Nk1f/58dxv+INgByfjQVrBTM4j+n9rmmiDY6Vof3voATow6T9etW9d1qI68rFu3zjp06HBSjwVA2tPoV/W91efEnj17XF/cpAZNxHfuuefavffea++++67NmjXLXRTAIn8oRlLzamTwO5FatWq5H4baZmSw0//VF1jh7pJLLknBo0VWR7ADTiDo2xb0fYt09tlnW548eVw/uIDK6QOzRo0a4WUKZCtXrrQlS5a4vjgKescbtKHOzxqMoV/8kRd14AaQtagvrfre6seffrjpM6Fdu3Yp3k7wmbF///5klVdLgGr6Fi5cGF72119/2dq1a8PbUhC87LLL7OOPP7ZVq1a5wV3nnXee6xf4+uuvW7169axAgQIpPlZkXQQ74ATUDKJmDTVnxO8IrQ/E7t2724MPPmjTp093Zbp16+ZGmEX+Yq9YsaL7VaxlR48etWuvvTbJ/Sn0qblXI2E1eGLDhg2u2UQjb3///fd0fawAUkfBbvPmzfbII4+4AVP58uU7bnl9bjz11FPuR6EGUGgghUa3qvtHgwYNkrXPKlWquM8JfeZodKu6cdx66612+umnu+UB1dBpahZ1C1HXDgVRDarQIC411cIvBDsgGTR/lS6Jee6556xt27bWqVMnV9um/nEzZsxw0w/ED2z64L3++uuP+6Gv0Wnqr6OmHU1uql/lCoTqY5fUMQDIXPp7bdasmRt5mpwuGyqrMKe+tuecc477DNF0SbNnz06ym0Zi1PdXXTeuueYaFwg1Fuuzzz6LasJVeNMPysi+dPp//GXwQ4xGUGT2QQAAAODkUWMHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0Ab2zdutV69eplZ511lsXGxlr58uWtdevW7jRNaUmnYerTp4+lB520fcqUKUmuHzt2rCtzvMuvv/6aLscGIOvLldkHAABpQWHm0ksvtSJFitgLL7xgtWrVssOHD7vz9vbo0cPWrFljPrj55putZcuW4ds6n/C5555rTz75ZHiZTiQP4NREjR0AL9x7772utmrRokXuhOo6sXrNmjWtb9++7mTrgY0bN9p1111nBQsWtEKFCtlNN91k27ZtC69/4oknrE6dOvbOO+9YxYoVrXDhwta+fXvbu3evW3/bbbfZ119/bSNGjEhQQ7Zy5Uq76qqr3LZLly5tnTp1sj///DOqpu++++6z/v37W7FixaxMmTJufwHtT66//nq33eB2pHz58rn7BZc8efJY/vz53f9nzpzpHvORI0ei7tOmTRt3LJGP7/XXX3c1mrqvnoPdu3dH3eff//63Va9e3Z2Yvlq1avbaa6+d9GsEIP0R7ABkezt27LDp06e7mrkCBQokWK9aPDl27JgLdSqvcDZr1iz75ZdfXC1YpJ9//tk1h06bNs1dVPa5555z6xToGjRoYN26dbM//vjDXRSQdu3aZVdccYWdf/759t1337njUWBUaIo0btw4d4wLFy60oUOHupo2HYcsXrzYXY8ZM8ZtN7idXDfeeKMdPXrUpk6dGl4WFxdnn376qd1xxx3hZT/99JNNmjTJPvnkE3ec33//vQvGgfHjx9ugQYPsmWeesR9//NGeffZZGzhwoDt2AFlcCACyuYULF4b0cfbRRx8dt9zMmTNDOXPmDG3cuDG8bNWqVe6+ixYtcrcff/zxUP78+UN79uwJl3nwwQdD9evXD99u3LhxqHfv3lHbfuqpp0LNmzePWrZp0ya37bVr14bv17Bhw6gyF154Yeihhx4K31b5yZMnJ/uxxz+W7t27h6666qrw7WHDhoXOOuus0LFjx8KPT8/B77//Hi7z+eefh3LkyBH6448/3O2zzz47NGHChASPr0GDBsk+LgCZgz52ALK9/z8PnZhqn1S7pkugRo0arkZP6y688EK3TE2gp512WrhM2bJlXc3X8Sxfvty+/PJL1wwbn2oA1TQs5513XtS65Gw7JVSTqMexefNmO/30091gCzUfq2k3cOaZZ7p1AdVAqjZz7dq17nHreLt27eq2FVDzrpqlAWRtBDsA2V6VKlVccEmrARK5c+eOuq1tK/gcz759+9wI3Oeffz7BOoW3k9l2SqgpuHbt2vb2229b8+bNbdWqVa4pNrn0OOTNN9+0+vXrR63LmTNnmh0ngPRBsAOQ7WkgQosWLezVV191gxPi97NT/zfVymkwwKZNm9wlqLVbvXq1W6+au+TSgAX1ZYt0wQUX2H//+19X25crV+o/WhX84m87pe6880576aWXXK1ds2bNomoogwEkW7ZssXLlyrnbGlySI0cOq1q1qhv0oeXqe9ixY8eTOg4AGY/BEwC8oFCnQHTRRRe5gLV+/XrXvDpy5EjX1CgKOZoGRYFl6dKlbgRt586drXHjxlavXr1k70vhTYMfNBpWo15V46aBGxqUccstt7hBD2rO1FQrt99+e4qCmratefc0J9/OnTtT9Vx06NDBfv/9d1frFjloIqCRrl26dHHNx998840LwxrkoZG1MnjwYBsyZIh77tatW2crVqxwAzqGDx+equMBkHEIdgC8oEmJFdaaNGli/fr1c3O7XXnllS4kjRo1Ktzs+fHHH1vRokWtUaNGLujpfhMnTkzRvh544AHXLKlaPs0Zpxow1XLNmzfPhTg1gSpAahJj1RSqNiy5hg0b5kbJqpZNzaqpob5wmvJF/f001Ul8lStXdvPftWrVyh2r+v1FTmeiGj9Nd6Iwp8eh4Ku+epUqVUrV8QDIODEaQZGB+wMAZICmTZu6Oe1U6xZJ89hpKpdly5Zl2rEBSD/0sQMAj6j59quvvnIXJhUGTj0EOwDwiJpvFe40OleDIQCcWmiKBQAA8ASDJwAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAzA//H59K6XT9Sy0fAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "type_counts.columns = ['type', 'count']\n",
    "sns.barplot(x='type', y='count', data=type_counts, \n",
    "            hue='type', palette='pastel', legend=False)\n",
    "plt.title(\"Content Type Distribution on Netflix\")\n",
    "plt.xlabel(\"Content Type\")\n",
    "plt.ylabel(\"Count\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4d36d59",
   "metadata": {},
   "source": [
    "Netflix hosts significantly more Movies than TV Shows, indicating a strong focus on film-based content."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "81e21c2a",
   "metadata": {},
   "source": [
    "### What are the top 10 genres on Netflix?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "e1e178fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                      genre  count\n",
      "0      International Movies   2369\n",
      "1                    Dramas   2293\n",
      "2                  Comedies   1553\n",
      "3        Action & Adventure    806\n",
      "4        Independent Movies    740\n",
      "5           Romantic Movies    579\n",
      "6                 Thrillers    547\n",
      "7  Children & Family Movies    503\n",
      "8             Documentaries    391\n",
      "9             Horror Movies    336\n"
     ]
    }
   ],
   "source": [
    "genre_count = df['genre'].value_counts().reset_index().head(10)\n",
    "print(genre_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "145a3448",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAnQAAAHWCAYAAAD+VRS3AAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAgkhJREFUeJztvQe8z+X//3/ZpJASKhmVkZZoKCkjVFpaSkVp05bSREqpNLU/NJU0NEQZoUFGW2gglYyGmcz3/3a/ft/r/b/Oyzkyz/u63udxv92Oc877/XLO6zqvazyu57oKpVKplBFCCCGEENFSONM3IIQQQgghtgwJOiGEEEKIyJGgE0IIIYSIHAk6IYQQQojIkaATQgghhIgcCTohhBBCiMiRoBNCCCGEiBwJOiGEEEKIyJGgE0IIIYSIHAk6IYQQ0fPDDz+YFi1amLJly5pChQqZIUOGmGeffdZ+PXv27PR1Rx99tP0QItuQoBOiAMIitzEfY8aM2eb38vjjj5vTTz/d7LHHHvZ3dujQIc9rFy1aZC6++GJToUIFU7p0adOkSRPz+eefb9Lve+edd8wJJ5xgKlasaIoXL27Kly9vGjdubO6//36zZMmSrdCigk337t3tc+Tv+88//6z3frVq1Uzr1q0362c/9thjVqTlRvv27c0333xj7rzzTvPCCy+YBg0abNbvECJWimb6BoQQ+Q8Lns/zzz9vRowYsd7rderU2eb3cs8995ilS5eaQw45xPz+++95Xrdu3Tpz/PHHm6+++spcf/31Zuedd7YLPNaWKVOmmL333nuDv4f/37FjRysI9ttvP3P55ZebKlWq2N89fvx4c8stt5j33nvPjBo1ahu0suCxYMECK9avu+66rfYzed4896ToX7FihX2GN998s+ncufMGf8YHH3yw1e5HiJCQoBOiAHLOOefk+H7ChAlW0CVfzw/Gjh2bts5tv/32eV732muvmU8//dQMHjzYnHbaafa1M844w9SsWdPcfvvtZuDAgRv8PX369LFi7pprrrHWOH6f46qrrrJiEmGb3/z777/WUli4cHY5TA488EBz7733WuFcqlSpbfq7Fi5caD+XK1fuP6/lby1ENpJdM4gQYquxfPlya13BilWiRAlTq1Ytc99995lUKpXjOoQRVpGXXnrJXlOyZElTv359M27cuI36PVWrVs0hrjYk6HDjtWnTJv0arldE3VtvvWVWrlyZ5//F9YclsG7dulZk5Pb7KleubG644Yb1Xn/xxRdtexAluGfbtm1rfvnllxzXYCXcd999zXfffWfdwNttt53ZbbfdrIj0wYXN737llVesRZBruNa5ej/77DPTqlUrGwfG60cddZT55JNPcvwMLIpXX321dV3yXHbZZRdzzDHHbJTr+YsvvjDHHnusKVOmjBXPzZo1s2Lex8Wd8XuvvfbatHv7lFNOSQunjeG2224z8+fPt1a6/wLr6YMPPmifD/2H53zJJZeYv//+O30N7Z06dardALiQAP7uuHjpQ4Dllte5Ni+SMXS4avmd06ZNy3Fdy5YtzY477mjmzp270W0WIpNI0Akh1gPRduKJJ5oHHnjACoy+fftascaCySKfhEUWkYGFr2fPnubPP/+0/+/bb7/daveEGDnooIPWs2ThqkWwff/993n+348//tjG35111lmmSJEiG/07icc677zzrDuXvwFtxCVLzB0/zwfxQZsPOOAAawGsXbu2FYjDhg1b7+fecccdZujQoaZLly7mrrvuslaj0aNH25+LuMPiyOv8jqZNm5qJEyem/++ll15qRdKpp55qXZD8DMRmUpAkQQwdeeSR1mXdtWtXc+utt5pZs2ZZcYOQTHLFFVfYa7mXyy67zMYe/pc704ffxb0janGJbgjEG33riCOOMA899JA5//zz7QYBUbV69Wp7DYJv9913t39XQgP4wMWKwKefAs+X17l2Y+H3IVoRdmvXrrWvPfnkk9Y1+8gjj5hdd911o3+WEBklJYQo8HTq1AmzW/r7IUOG2O979eqV47rTTjstVahQodSPP/6Yfo3r+Jg8eXL6tZ9//jlVsmTJ1CmnnLJJ91G6dOlU+/bt83zvggsuWO/1oUOH2t8/fPjwPH/uQw89ZK+hXT5r1qxJLVy4MMfHunXr7HuzZ89OFSlSJHXnnXfm+D/ffPNNqmjRojleP+qoo+zPf/7559OvrVy5MlWpUqXUqaeemn7tww8/tNfVqFEj9c8//6Rf53fuvffeqZYtW6Z/P3BN9erVU8ccc0z6tbJly9rntamcfPLJqeLFi6d++umn9Gtz585N7bDDDqnGjRunXxswYIC9x+bNm+e4l2uuucb+PRYtWrTB33P77bfb/8/fcuzYsfbrvn37pt+vWrVq6vjjj09//9FHH9lrXnrppRw/h+eZfL1u3br2b51k1qxZ9tp77703x+uuLbzv4P8nf8b777+f7u8zZ85Mbb/99vbvJURMyEInhFgPkgOwZF155ZU5XscFi4ZLWp0aNmxo3ZIOYuJOOukk8/7776etHlsKVh5cjElwl7n388K5NJMxemRFYp3xP7AuwhtvvGFdgbh0//jjj/RHpUqVrMXuww8/zPGz+Nl+DCJWN6yHM2fOXO9+sAb5cWVffvmlLbtx9tln29/vfhdub9yiuK+5FxcnhkVtU1yBPAMsTieffLKpUaNGDjczvxMLZjLDl2xi3zWNxY2f8/PPP2/078XiiAt6Q1Y6YiJxMeM29v/O9Cf+psm/87aAcidYCbEuY/GjT2GlEyImlBQhhFgPFm1cTTvssEOuWa/JRT23DFOSFXCFEneFCNpSEEC5xcmRVODezwvXjmXLluV4fa+99rLJIEBChJ/li8BCvOaVPVusWLEc3+MOTMbmEYP19ddfr/d/q1evnuN7fpcTenmxePFi+/MQR1xHbCOi57jjjrNuYV+oJeEZ8CxwmyfhmSIWiQskhs0X5cm2gB/XtjEQ40Ys4BNPPGETUpLQdtpGLGBe2bL5AfGhxGIirkmwyet+hAgVCTohRBRgTcqtrIl7bUOxTsRdATF9WA4dWICaN29uv8ZK5YPIQaBhjcwt7i5p7csrNi+ZRJKb+HTWNxI2yA7NDff7sBhiLXvzzTet1Y3/Q8IHFkUSHrYWm9Ke/7LSEaeHECX+LwltRzwRM5cbWE3zA2I0nXjEcks8nhAxIUEnhFgPsgZHjhxpMyp9K9306dPT7+dmYfIhSYFMza21ICN0PvroIysA/MQI3I/8HiyCeYEAwq1Hdmm3bt02qkTInnvuacUL1rQN/eytAb8LyD51AvO/xC3lQPhAhJAsQgJHXoKOZ8DfaMaMGeu9xzPl74HFb1uBlQ5Rl5sbk7bT10iI+K/yJhuTDb054NomEWOfffYxhx9+uBWfZPUefPDB2+T3CbEtUAydEGI9cOMRL/Xoo4/meJ1sQhbVpHCgqKtfNgP3He4rYpM2Jat0Q1B7jjIYWKIcxFoRg8XJD7nF1zkQM2R2YqG78cYbc7UyJV8jlop779Gjx3rv8b2Ltdsa4DpF2OD2S7qFwZUL4ZngnvTBuoV1ckNlW2gHz4Jn4h+Dxd8T92KjRo2smNxW4HJF0GFJdC5yBxZH2kXmb5I1a9bkyCamfEoyu3hrQDbynDlzzHPPPWezmSl7glt7Q39TIUJDFjohxHogkAhmpywEAoBSHLj3EASU7nAWJQc12CgxQRIFwopyGoAY+i8oh0F5DKBEBTFnvXr1st9TOmX//fdPC7rDDjvMWlKo9+ZOikAMbMzvQchR2gMXJW2h7Adxb8SEIUYRhogjl2RBG7kPLHr8DUgowFpJqQ/cnSQNUDJka4CF7JlnnrFCmTg22kiNut9++80mBSC2+DthMeWe+VvwTHDDYt2aNGmSLZWyIWgL8YKINyx7RYsWtRYzREuyXt62gPIn9KncxB4JCb1797bxawhP4hOx+vJMKCviCkkjfCnZQluIf+R5URplS6BcDP2I+8PSCQMGDLAClNIu+fG3EWKrkOk0WyFEeGVLYOnSpbZUxa677poqVqyYLatBWQi/lAXw//j/L774or2mRIkSqXr16tkSHRsDZUpc6ZPkB2UnfP76669Ux44dUzvttFNqu+22s+UnJk2atEltffPNN1PHHXdcqkKFCrb8SLly5VKNGjWybcutJMfrr79u36dsCh+1a9e27Z0xY0b6Gu6Dkhq5tY0yHcmyJYMHD8713r744otUmzZtbPv4O/J/zzjjjNSoUaPSpVCuv/761AEHHGDLjXA/fP3YY49tVNs///xzWxqFshz8/Zo0aZL69NNPcy31kfy7unv/r+fqly1J4sq7+GVLHE899VSqfv36qVKlStm27bfffqmuXbva0iqOefPm2f/L+/wcV35kc8uWLFmyxP6NDzrooNTq1atz/F/6fuHChVPjx4/fYHuFCIVC/LN1pKEQoiCCC7ZTp07ruWeFEELkH4qhE0IIIYSIHAk6IYQQQojIkaATQgghhIgcZbkKIbYIheEKIUTmkYVOCCGEECJyJOiEEEIIISJHLtcMwNFFc+fOtUVKt9VRNkIIIYTIjrAWiopzIsyGji2UoMsAiLlteW6iEEIIIbILjlTkpJi8kKDLAO6wcx7Otjw/UQghhBBxs2TJEmsEctohLyToMoBzsyLmJOiEEEII8V/8V4iWkiKEEEIIISJHgk4IIYQQInIk6IQQQgghIkeCTgghhBAiciTohBBCCCEiR4JOCCGEECJyJOiEEEIIISJHgk4IIYQQInIk6IQQQgghIkeCTgghhBAicnT0V0DMPqi6iYFqn8/K9C0IIYQQwkMWOiGEEEKIyJGgE0IIIYSIHAk6IYQQQojIkaATQgghhIgcCTohhBBCiMiRoBNCCCGEiBwJOiGEEEKIyFEdOrHNmN0skrp6o1RXTwghRNzIQieEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkZM1gq53797m4IMPNjvssIPZZZddzMknn2xmzJiR45p///3XdOrUyey0005m++23N6eeeqqZP39+jmvmzJljjj/+eLPddtvZn3P99debNWvW5LhmzJgx5qCDDjIlSpQwe+21l3n22WfzpY1CCCGEEFkt6MaOHWvF2oQJE8yIESPM6tWrTYsWLczy5cvT11xzzTXmnXfeMYMHD7bXz50717Rp0yb9/tq1a62YW7Vqlfn000/Nc889Z8Xabbfdlr5m1qxZ9pomTZqYL7/80lx99dXmwgsvNO+//36+t1kIIYQQAgqlUqlUNv4pFi5caC1sCLfGjRubxYsXmwoVKpiBAwea0047zV4zffp0U6dOHTN+/Hhz2GGHmWHDhpnWrVtboVexYkV7zRNPPGFuuOEG+/OKFy9uvx46dKj59ttv07+rbdu2ZtGiRWb48OEbdW9LliwxZcuWtfdUpkyZ9OuzD6puYqDa57M26rrZzSJpz6iNa48QQgiR3+SlGbLWQpeEhkP58uXt5ylTplirXfPmzdPX1K5d2+yxxx5W0AGf99tvv7SYg5YtW9o/5tSpU9PX+D/DXeN+Rm6sXLnS/gz/QwghhBBia5GVgm7dunXWFXrEEUeYfffd1742b948a2ErV65cjmsRb7znrvHFnHvfvbehaxBpK1asyDO+D3XtPqpUqbIVWyuEEEKIgk5WCjpi6XCJvvLKKyYEunXrZi2G7uOXX37J9C0JIYQQIosoarKMzp07m3fffdeMGzfO7L777unXK1WqZJMdiHXzrXRkufKeu2bixIk5fp7LgvWvSWbG8j1+7VKlSuV6T2TD8iGEEEIIsS3IGgsduR2IuTfffNOMHj3aVK+eMyC/fv36plixYmbUqFHp1yhrQpmShg0b2u/5/M0335gFCxakryFjFrG2zz77pK/xf4a7xv0MIYQQQoj8pmg2uVnJYH3rrbdsLToX80bMGpYzPnfs2NFce+21NlECkXbFFVdYIUaGK1DmBOF27rnnmj59+tifccstt9if7Sxsl156qXn00UdN165dzQUXXGDF46uvvmozX4UQQgghMkHWWOgef/xxG5929NFHm8qVK6c/Bg0alL7mgQcesGVJKChMKRPcp2+88Ub6/SJFilh3LZ8Reuecc44577zzTM+ePdPXYPlDvGGVO+CAA8z9999vnnnmGZvpKoQQQgiRCbK2Dl3IqA5dWKgOnRBCiFAp8HXohBBCCCEKChJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETlFM30DQsTE7NOrmxioNnhWpm9BCCFEPpI1Frpx48aZE044wey6666mUKFCZsiQITne79Chg33d/2jVqlWOa/766y/Trl07U6ZMGVOuXDnTsWNHs2zZshzXfP311+bII480JUuWNFWqVDF9+vTJl/YJIYQQQmS9oFu+fLk54IADTL9+/fK8BgH3+++/pz9efvnlHO8j5qZOnWpGjBhh3n33XSsSL7744vT7S5YsMS1atDBVq1Y1U6ZMMffee6/p3r27eeqpp7Zp24QQQgghCoTL9dhjj7UfG6JEiRKmUqVKub43bdo0M3z4cDNp0iTToEED+9ojjzxijjvuOHPfffdZy99LL71kVq1aZfr372+KFy9u6tata7788kvTt2/fHMJPCCGEECI/yRoL3cYwZswYs8suu5hatWqZyy67zPz555/p98aPH2/drE7MQfPmzU3hwoXNZ599lr6mcePGVsw5WrZsaWbMmGH+/vvvPH/vypUrrXXP/xBCCCGE2FoUGEGHu/X55583o0aNMvfcc48ZO3asteitXbvWvj9v3jwr9nyKFi1qypcvb99z11SsWDHHNe57d01u9O7d25QtWzb9QeydEEIIIcTWImtcrv9F27Zt01/vt99+Zv/99zd77rmntdo1a9Zsm/7ubt26mWuvvTb9PRY6iTohhBBCbC0KjIUuSY0aNczOO+9sfvzxR/s9sXULFizIcc2aNWts5quLu+Pz/Pnzc1zjvs8rNs/F7pE5638IIYQQQmwtCqyg+/XXX20MXeXKle33DRs2NIsWLbLZq47Ro0ebdevWmUMPPTR9DZmvq1evTl9DRiwxeTvuuGMGWiGEEEIIkUWCjnpxZJzyAbNmzbJfz5kzx753/fXXmwkTJpjZs2fbOLqTTjrJ7LXXXjapAerUqWPj7C666CIzceJE88knn5jOnTtbVy0ZrnD22WfbhAjq01HeZNCgQeahhx7K4U4VQgghhMhvskbQTZ482dSrV89+ACKLr2+77TZTpEgRWxD4xBNPNDVr1rSCrH79+uajjz6y7lAHZUlq165tY+ooV9KoUaMcNeZIaPjggw+sWOT/X3fddfbnq2SJEEIIITJJ1iRFHH300SaVSuX5/vvvv/+fP4OM1oEDB27wGpIpEIJCCCGEEKGQNRY6IYQQQoiCigSdEEIIIUTkFA6hfIh/YoODjFPeE0IIIYQQgQs6sk7daQ3J47J+++23jNyTEEIIIURMZCwp4u23386RsEAGqQOBR2mRatWqZejuhBBCCCHiIWOC7uSTT7afCxUqZNq3b5/jvWLFilkxd//992fo7oQQQggh4iFjgo4TGKB69epm0qRJ9hguIYQQQggRYR06ivQKIYQQQoiIBR0QL8fHggUL0pY7R//+/TN2X0IIIYQQMZBxQdejRw/Ts2dP06BBA1O5cmUbUyeEEEIIISISdE888YR59tlnzbnnnpvpWxFCCCGEiJKM16FbtWqVOfzwwzN9G0IIIYQQ0ZJxQXfhhReagQMHZvo2hBBCCCGiJeMu13///dc89dRTZuTIkWb//fe3Neh8+vbtm7F7E0IIIYSIgYwLuq+//toceOCB9utvv/02x3tKkBBCCCGEiEDQffjhh5m+BSGEEEKIqMl4DJ0QQgghhIjcQtekSZMNulZHjx6dr/cjhBBCCBEbGRd0Ln7OsXr1avPll1/aeLr27dtn7L6EEEIIIWIh44LugQceyPX17t27m2XLluX7/QghhBBCxEawMXTnnHOOznEVQgghhIhZ0I0fP96ULFky07chhBBCCBE8GXe5tmnTJsf3qVTK/P7772by5Mnm1ltvzdh9CSGEEELEQsYFXdmyZXN8X7hwYVOrVi3Ts2dP06JFi4zdlxBCCCFELGRc0A0YMCDTtyCEEEIIETUZF3SOKVOmmGnTptmv69ata+rVq5fpWxJCCCGEiIKMC7oFCxaYtm3bmjFjxphy5crZ1xYtWmQLDr/yyiumQoUKmb5FIYQQQoigyXiW6xVXXGGWLl1qpk6dav766y/7QVHhJUuWmCuvvDLTtyeEEEIIETwZt9ANHz7cjBw50tSpUyf92j777GP69eunpAghhBBCiBgsdOvWrTPFihVb73Ve4z0hhBBCCBG4oGvatKm56qqrzNy5c9Ov/fbbb+aaa64xzZo1y+i9CSGEEELEQMYF3aOPPmrj5apVq2b23HNP+1G9enX72iOPPJLp2xNCCCGECJ6Mx9BVqVLFfP755zaObvr06fY14umaN2+e6VsTQgghhIiCjFnoRo8ebZMfsMQVKlTIHHPMMTbjlY+DDz7Y1qL76KOPMnV7QgghhBDRkDFB9+CDD5qLLrrIlClTJtfjwC655BLTt2/fjNybEEIIIURMZEzQffXVV6ZVq1Z5vk/JEk6PEEIIIYQQgQq6+fPn51quxFG0aFGzcOHCfL0nIYQQQogYyZig22233eyJEHnx9ddfm8qVK+frPQkhhBBCxEjGBN1xxx1nbr31VvPvv/+u996KFSvM7bffblq3bp2RexNCCCGEiImMlS255ZZbzBtvvGFq1qxpOnfubGrVqmVfp3QJx36tXbvW3HzzzZm6PSGEEEKIaMiYoKtYsaL59NNPzWWXXWa6detmUqmUfZ0SJi1btrSijmuEEEIIIUTAhYWrVq1q3nvvPfP333+bH3/80Yq6vffe2+y4446ZvC0hhBBCiKjI+NFfgICjmPAhhxyy2WJu3Lhx5oQTTjC77rqrtfINGTIkx/uIxdtuu80mWpQqVcqeRPHDDz/kuOavv/4y7dq1s7XxypUrZzp27GiWLVu2XrLGkUceaUqWLGlPuejTp89m3a8QQgghRFYJuq3B8uXLzQEHHGBdtbmB8Hr44YfNE088YT777DNTunRp69r1kzIQc1OnTjUjRoww7777rhWJF198cfp9TrWgPh6WRWrk3XvvvaZ79+7mqaeeypc2CiGEEEIEeZbr1uLYY4+1H7mBdY6TKUjEOOmkk+xrzz//vI3Rw5LXtm1bM23aNDN8+HAzadIk06BBA3vNI488YrNx77vvPmv5e+mll8yqVatM//79TfHixe3xZF9++aU90cIXfkIIIYQQ+UnWWOg2xKxZs8y8efOsm9U/XuzQQw8148ePt9/zGTerE3PA9YULF7YWPXdN48aNrZhzYOWbMWOGjQMUQgghhMgEWWOh2xCIOUhmzfK9e4/Pu+yyy3qnVZQvXz7HNdWrV1/vZ7j38or/W7lypf3wXbdCCCGEEFuLAmGhyzS9e/e2FkH3QTKFEEIIIcTWokAIukqVKqXPj/Xhe/cenxcsWJDj/TVr1tjMV/+a3H6G/ztygzp7ixcvTn/88ssvW6llQgghhBAFRNDhJkVwjRo1Kofbk9i4hg0b2u/5vGjRIpu96hg9erRZt26djbVz15D5unr16vQ1ZMRyysWGyq2UKFHClkLxP4QQQgghthZZI+ioF0fGKR8uEYKv58yZY+vSXX311aZXr17m7bffNt98840577zzbObqySefbK+vU6eOadWqlbnooovMxIkTzSeffGKPJCMDluvg7LPPtgkR1KejvMmgQYPMQw89ZK699tqMtl0IIYQQBZusSYqYPHmyadKkSfp7J7Lat29vnn32WdO1a1dbq47yIljiGjVqZMuUUCDYQVkSRFyzZs1sduupp55qa9c5iH/74IMPTKdOnUz9+vXNzjvvbIsVq2SJEEIIITJJoZQ7RFXkG7h7EYfE0/nu19kH5cygDZVqn8/aqOtmN4ukPaM2rj0w+/RI2jR449skhBAiPs2QtS5XIYQQQoiCigSdEEIIIUTkSNAJIYQQQkSOBJ0QQgghRORI0AkhhBBCRI4EnRBCCCFE5EjQCSGEEEJEjgSdEEIIIUTkSNAJIYQQQkSOBJ0QQgghRORI0AkhhBBCRI4EnRBCCCFE5EjQCSGEEEJEjgSdEEIIIUTkFM30DQghMsfsS6qbGKj25KxM34IQQgSNLHRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5KlsihMgqZt8YSSmWu1WKRQix9ZCFTgghhBAiciTohBBCCCEiR4JOCCGEECJyJOiEEEIIISJHgk4IIYQQInIk6IQQQgghIkeCTgghhBAiciTohBBCCCEiR4JOCCGEECJyJOiEEEIIISJHgk4IIYQQInIk6IQQQgghIkeCTgghhBAiciTohBBCCCEiR4JOCCGEECJyJOiEEEIIISJHgk4IIYQQInKKZvoGhBBC5M3se6qbGKh2w6xM34IQBRpZ6IQQQgghIkeCTgghhBAicgqUy7V79+6mR48eOV6rVauWmT59uv3633//Ndddd5155ZVXzMqVK03Lli3NY489ZipWrJi+fs6cOeayyy4zH374odl+++1N+/btTe/evU3RogXqTymEEJvN7KcicSNfLDeyiIcCp0Lq1q1rRo4cmf7eF2LXXHONGTp0qBk8eLApW7as6dy5s2nTpo355JNP7Ptr1641xx9/vKlUqZL59NNPze+//27OO+88U6xYMXPXXXdlpD1CCCGEEAVO0CHgEGRJFi9ebP73v/+ZgQMHmqZNm9rXBgwYYOrUqWMmTJhgDjvsMPPBBx+Y7777zgpCrHYHHnigueOOO8wNN9xgrX/FixfPQIuEEEIIUdApcDF0P/zwg9l1111NjRo1TLt27awLFaZMmWJWr15tmjdvnr62du3aZo899jDjx4+33/N5v/32y+GCxS27ZMkSM3Xq1Ay0RgghhBCigFnoDj30UPPss8/auDncpcTTHXnkkebbb7818+bNsxa2cuXK5fg/iDfeAz77Ys69797LC+Lx+HAgAIUQQgghthYFStAde+yx6a/3339/K/CqVq1qXn31VVOqVKlt9ntJmkgmYwghhMgOZr8WSZLHaUryyGYKnMvVB2tczZo1zY8//mjj6latWmUWLVqU45r58+enY+74zPfJ9917edGtWzcbo+c+fvnll23SHiGEEEIUTAq0oFu2bJn56aefTOXKlU39+vVttuqoUaPS78+YMcPG2DVs2NB+z+dvvvnGLFiwIH3NiBEjTJkyZcw+++yT5+8pUaKEvcb/EEIIIYTYWhQol2uXLl3MCSecYN2sc+fONbfffrspUqSIOeuss2yZko4dO5prr73WlC9f3oquK664woo4MlyhRYsWVride+65pk+fPjZu7pZbbjGdOnWyok0IIYQQIhMUKEH366+/WvH2559/mgoVKphGjRrZkiR8DQ888IApXLiwOfXUU3MUFnYg/t59911bWBihV7p0aVtYuGfPnhlslRBCCCEKOgVK0HECxIYoWbKk6devn/3IC6x777333ja4OyGEEEKIzaNAx9AJIYQQQmQDEnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRU6DKlgghhBDiv5k9OpLzaZvqfFqHLHRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggROUqKEEIIIURWM/uLSJI86m1+kocsdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBt5n069fPVKtWzZQsWdIceuihZuLEiZm+JSGEEEIUUCToNoNBgwaZa6+91tx+++3m888/NwcccIBp2bKlWbBgQaZvTQghhBAFEAm6zaBv377moosuMueff77ZZ599zBNPPGG22247079//0zfmhBCCCEKIEUzfQOxsWrVKjNlyhTTrVu39GuFCxc2zZs3N+PHj8/1/6xcudJ+OBYvXmw/L1myJMd1S9euMzGQvO+8WLomu9oDS1dnV5uWrsqu9sDSldnVpqX/Zld7YOmK7GrT0n+yqz2wdHl2tWnpsnjb415LpVIb/L8SdJvIH3/8YdauXWsqVqyY43W+nz59eq7/p3fv3qZHjx7rvV6lShUTJWXLmqwi29qTjW16NsvaAw9mWZu6Z1l74Opsa1O2tScb21Q2z3eWLl1qym5gbpegywew5hFz51i3bp3566+/zE477WQKFSq0zX4vqh7R+Msvv5gyZcqY2Mm29mRjm7KtPdnYpmxrTza2Kdvak41tWpKP7cEyh5jbddddN3idBN0msvPOO5siRYqY+fPn53id7ytVqpTr/ylRooT98ClXrpzJL+hs2TCAsrU92dimbGtPNrYp29qTjW3KtvZkY5vK5FN7NmSZcygpYhMpXry4qV+/vhk1alQOixvfN2zYMKP3JoQQQoiCiSx0mwHu0/bt25sGDRqYQw45xDz44INm+fLlNutVCCGEECK/kaDbDM4880yzcOFCc9ttt5l58+aZAw880AwfPny9RIlMg5uXWnlJd2+sZFt7srFN2daebGxTtrUnG9uUbe3JxjaVCLA9hVL/lQcrhBBCCCGCRjF0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIUQ+oBxEsS2RoBNCbPJiFPPCRCFwx4oVK0y24J6Ja1/Mz8i/f448ygZ4Lu6ox5kzZ2b6dsR/9LuVK1ea2JCgi7Sz/fDDD+bXX3/N9O2IDTyj3377zfz5558mW9pD8Wy+/vfff+3C5AujWOCeCxf+f9Nev379zIABA7JiHPFceCYjR4401113nVm2bNk2PSc6v9pDfc+zzz7bfPXVVyZm/H7Xq1cv06lTJzNmzBiTLXPDmjVrTDaQ+r9+x7O55557zOzZs01MSNBF2NmGDBliWrZsaYYNGxa9YHATwtSpU833339v1q5da7LhGb311lt2IXrnnXfs4hp7e+hr7dq1M02aNDGtW7c2X3/9dXqBigl3z127djU9evQwpUuXNkWLxl9fnWf0+uuvmzPOOMN+P2PGjPR7MVrqaM8bb7xh28NRi2wiYm1Lst899NBDVtDVqFHDxIybG8aNG2dPS0qebx5re15//XVz4okn2q8XL16cfi8KKCws4uGdd95JlS5dOvXwww+n5s6dm4qZdevW2c9vvvlmarfddks99NBDqfnz56diZ8iQIalSpUql7r333tQvv/ySip233nrLtqdXr16p119/PXXcccelSpQokZoxY0YqRp588slU5cqVU1999VX6tVWrVqX++OOPVKxMmjQpVb58+dRTTz2V4/V//vknFSPfffddavfdd089/vjjOV7/8ccfU7EyatSoVI0aNeyzcn1u4cKFqeHDh9uvY5y7X3vttVSZMmVSPXr0SH355Zc53ouRCRMmpHbeeefU008/neP1v/76KxUDEnQRsXTp0lTTpk1TN998s/1+xYoVqd9//91O4gg9vo+NoUOHWoH62GOPpRYsWLDe+2vXrk3FxK+//praf//9U48++qj9fuXKlalFixbZSfvrr7+OasLjPpctW5Zq0aJFqnfv3va1OXPm2EXp4osvjvY5de3aNXXOOeekBcL//ve/1AEHHGDH1iOPPJKKkWeeeSbVrFmz9OLz6quvpk488cTU3nvvbcdWDM/HHxcsrLVq1UrPe4hwnk/JkiVTHTp0SC1evDgV40Zvjz32sM8Cwco8vueee6a233771FFHHRXNvOD45JNPUjvuuON6mwjmDIitPdCvX7/UkUcemW7HG2+8kTrllFNS++67r+2DoROfz6QAQxzGqlWrzE477WR+/PFHe5YsbrAuXbrYM+V69+4dj2nYGOtGefLJJ80ll1xiLrvsMrP99tvbmIX77rvPvPTSS2bBggXRufU4169YsWJmxx13tK5WngkuyvPOO880atTIxgSFHtvkBwWXLFnSuu9oA+79hg0bmubNm9vnBs8++6z566+/gn1OyfHgxtC0adPM9ddfb8455xwzdOhQ+2zq1KljnnnmGfP7779HMY78e6xQoYIZPXq06dOnjznllFPM888/b3bZZRdz8sknW/ce80XoMC4GDhxoLrroItsexj9t4dm89957pkGDBjbc5LnnnrNtDZnc4ktr1qxpypYta/bff38busA54DfddJP5/PPPzSeffGLefvttExMff/yxfSY8L+Y6xlHbtm1Ns2bN7HPiecYwjnzod7/88otdTxk7xNgSksHXl156qfnmm29MyMQfPFKAKFOmjKlbt665++67za233mpatWplBR2Dh0H1888/By8WfBjs//zzjylevLj59ttvzdNPP21j6YjPqlq1qpkwYYLp27evHVCxtIsYwJ133tk88cQTdgJgcjvttNNMixYtTOfOne1CxHMLGRenyb0irg8++GAzaNAgu5CecMIJ5uGHH7bXIfCIEeT5IIxCDkQnm5W+xmaIRfSGG26wC5JbgPbdd18bs0XwfalSpYLuby7Wh+zP7bbbzgpvYn66d+9u+vfvb5o2bWo6dOhgDjnkEPsezzGGTNFZs2aZnj17WgG62267mRdeeMG2x22IiDmjrx199NGmSJEiJlT8fjdlyhT7DJjjED9sgIivrVevnjnqqKPsxm/hwoU2TrB8+fImJpjnfvrpJztHjxo1yraZfnnQQQeZNm3a2EzeatWqmdDH0fLly+0mnA/Gzumnn27nv8MPP9z2OzaxtOWDDz6w1wRNpk2EInecuZp4i8GDB9t4rD///NO+NmbMGOti5Zo1a9bY1y688MJUx44dU6tXr47K1N29e/fUTjvtlNphhx1Sp512Wur555+3LonLL7/cmrpDxv2dv//++9TYsWOtm+jff/9N/fbbb6nnnnsu9cQTT+RwDbVu3Tp1xx13pELnm2++sa6h/v3729iebt26pcqWLWtdr37fuvHGG1N16tRJ/fzzz6nQ8O+T2L9jjz3W9rMrrrgiNXLkSPv68uXL09fw3I4//vjUySefHPT4cfdGqAKxjIcffrh1EX322Wf29SVLluS4nmdXs2bN4GNTv/jii9S1116bOv/88zcYT3bLLbfYeNsQ+xwkxweuuqpVq6YOOuigVJs2bXJcSzjGvHnzUieccELqsMMOS8/lIbeLsB73NeEXl156qQ3BYP1hDnTzx8EHH5yaNWtWKlTW/V8b3n33XbvuECZzwQUXpIYNG2ZfT7r0cY/vs88+wY8jCbqAIeCUAE0WI+JJ6FB9+/a1os1BYsRNN91kF9ypU6emQh9As2fPTn377bepadOmpd9jIvjwww/t125S69SpU6pt27Z2oQ1xgXX3RJJAlSpVUvXq1bPPiFiYESNG5LiWRZZntMsuuwSfSECiAJsHBLU/iSN0mPSYwO+///5U+/btbZ9jIQ6JZF9BAFSoUCH10ksvpd57773Ufvvtl6pfv77th+7ZEEOHOOI9JyZCjjl7++23bSwZcY0sSKeeemqqUKFCdlw56INs8BCxoT2jJDyDs846y851jB+HP8+x0LZr1y5VsWLF1Oeff54KjWR/YQzxtx8/frydw9i48oyc6OG1AQMGpJo0aZI65JBD0v0uRFHnxhTjh2dw6KGH2o2R20SQ2JHcRDBXJF8PbW5466230uOIDfi5555rn5FL7oDRo0fbOY9YwdDHEUjQBQqTFpl4DHon3Ohsffr0SV+DCGrcuLEVEiF3Nj+bleDzXXfd1VoWkoH18NNPP1nxQ+YUO72QJ+5PP/00Va5cuXQCxKBBg1KFCxfO8YwQEkyCWLxCXIgcLCRYDBA79DMWGh+sWYgjrHQsQOedd14OARHioop4PvDAA+2kDB999JHNznVjiutp12WXXWYtQ05A+EIiNBDXWHrvvPPOPJNUEEhkwWPhDu0Z5cWUKVPsOGHc+xmGPCOC09k4ISJIJggNkp586D+0BQu3Ew60yyUPuOQ1ROoDDzwQRb8joQPx07NnT9u3sDYWK1bMeicc48aNsxvBGMTP4sWL7SaOzSmQkIflt3PnzjnG0W233WbbGuJalBsSdAGACyiZ4Yn4cbtVrFnVq1e3Zm0Hbj3AHRuyadvB5EU2F1mEiDYGEsKBnbmDBZc2Y4kMbUIgoysJu3DM9YALqFq1anY3508IPJv77rsv2HILTmy7zDRcQMccc4yd3MiUzM1igDUhNEvCJZdcYu/XZ+bMmdbqhijA2k3/c2UwEHKvvPKKzaD03Ughtevqq6+2pXyS4oG5gFAMQjB4Tr6YQ0RQfgVxnnS/hoL7W5ON+/fff1trFfzwww/WKs9m74UXXlivz7nrQut3zpXq2oUww8VK+AjZ7X6/47177rnHWlZ9Qup3SXhOZBg/+OCD9nvcjmzK8aI46HNkj7PZCE383HXXXVaIJscRhhDmddZSxtFFF12Ufp+5hM0S80NMGdUSdBkGM3bt2rXX881j9WnVqpWdyHDp0dmcBYL4OXYOfgxQyCASiE/CXQyIV9rUsmVLOzGceeaZOYRfaPExAwcOtBNask4ZE8U111xjS8e4hdU9I9rBTjZ09x0Q+4cL1U3E9EVieojNoh1uoQq1HQiXG264Yb3YK0IQqGVG3CJWA2dJdW0mdgmXmCMk1z4LPCUUcrPqsgli8WQMsYFw7Wbhxf3qLJAh4v7GuI0bNmxoLfaUVnn22WetCMUCd/bZZ6eOOOIIa90OHTae7u/vav4h2ogHZH7DMufX0sPTwlxIKZkQwfKbLN3DfI0VmHCM3MQPmyXcq2wwEOihzQ133333epZdBB1hJLSVjbi/vtJGLPbJDWIMSNAFAIIAsFwhftzXxP4ULVo0deWVV+a4/qqrrrKLUdLUHzIMHAQDYqFu3bp2IWICvP76662lDvN3qGAhdSKTXZuDSRmhUKlSpRymeiYG4pcQeDEUdqUdWLKwALuJjz5JrAyiDitDSGLHJykysVCxcXAWjy5dutj+heBz8EywJLCwhipSk5s+343PZg5Xf/PmzXOIWILwsTq4+MBQYZOw3Xbb2TYxzxGMjjvPxdEiHIhnYp4gjCEG6HeEyDhPC0WEiaFDmDrrPGPKJbKEaJFjQ3DrrbeuJ34QaowVNgqIH+Y1d//Mh4gfjAyhsub/7pX4RcJ5HG7tYS7wnwcxgBhZQjMsbAwSdBnExUywWOJuYEKg4rYTeLgl2YUTUAtcQ2dDRMQSG5MEqwOWR2eRJK6EmCzEQ2gD6OWXX85hOaUwMPfpu8GIlSlevLi1pGAxZUfIwkrwtp/4ETo8BywmTM6+qGNBQuy5zNDQ8AUZ4oaNDv0Jqwjv8fywALMxYrFC4FGAF7EQagIE84EvoHHts/DgunfzBm2iDRTZxVKMAELkhRaq4G9o+Dtz72eccUZaYGOxwkKH6zIZU4fVJNRwkuQGhwQBMjsZK27OIHYOUdegQQP7rBByxKiGnADh7g3xQ79zILrpg1iAk5m8tC3EE3HWeeOIz6yjWBeJBXYw31FhgbmB99nUYlUNbRxtLBJ0GcR1Nvz0cN1111nTNiZirG+YsfH908EQe6TAUyYi5OB61ybEDxNaMquTuAva4e+SGGAuhisUcNcxURFP5srF8BoLKVYrhKlbkHDH8oy4niQVJo2QnxEQzOw2Dg5EEIsOk5x7brgfsASFbvWhojuCGrc4LjvEKZXd6Y+ML1xJjRo1Sp100kl2nMUQiE55Ivcc2ESwoLoTO7hv5gZOg6CtWIRD2+TxN0eo+fHBCAY2CbSNzQ/zmh8DSOwcG1cIMWYut40QghqIx6JtzNHO00Ks44svvmifFfHOTsSF1u8Q227uZr5jXmYec0kDQF9jo4plFSs4zxYx5GeFhsjEiROt1RcLJCWMeD4IUQdfY2RAkCNcQ4sB3BQk6DIMmZLEkfj1boj7YeJ2Qc1Yrogn4doYzm8lIwqXyl577ZUqUqSIndjdTht3C0HdDCCOX2JCCNGSxcTLRIwIIBbGLUpYr7CKEGPmH3lDADQxc1j1QrM05lY6BvFJ/J9beBy0AQswO1UnEEK0JPgLEW4fxI6LHUPUEVzPM0LUuft3GydHyO3iXhkj9DXaSOIGQelkUTtR50AchGZlBOLieC6IA7+EBZsi3FzUZyMrktg5YFOHaEAsJK2UIYL1kedDW4BnQGKXE3XOUpdsR8j9Dhc3/QsLKd4gXPgkcTiwmrJpZc1i4+SOMwyVv/76y87hziqHJRFxjUuV9jlYa9lsxHambhIJugyDUKD+kssgAsy/iDosdUkrSsgwoTEwEEAspATI0i524QRxc84pCxMTPbX1MN+HOCH4Ey6iDgsVC42z1PmiLtTgZnCLvD9Jud00fQzXJJNaso/hFmInjjWVxTb0hRVw4eEOdxsHJnKSB7A4YnlMLqIxtAlrAi48FyuLBdKJOud+DRGsik6kIRAQdVhFXT/Dco9QoFaZD/FNnG1KXF0sYImnfAcbOdevPv74YysifPdryLixgNhhM+e8D2z8mLcpTO3HcDKvI2bdMw4dxhGub/csMIog6hDdvvs1G5CgyyAsMrgVWDjZtfpuRxZc3K8EQOd2aH2IE4Lb5RCn5MdUIHrIZmWn7osHV48p1PYQpI07iFpmLEqIOmdpcKIO9yu1pEKF0h0IUqw4ZG2VLl3auh/g9ttvtwWREXVusuMZ4nIlnsRPAAmFpCXKCTWC0LEakEDgQNQR40iMFmWAQsYXmH5WMcKHOnkO5gsSjOiPLos6JHCZIgCoG+c2EpSH4X7J/KR/Me7pX5QnokwRlmLK/yAmQg1VSG4A/O8pL4Mr31m7eQ/3K88OL0QMECNLgW2ekT/G2CAh6miL734NlXXec3GCk7IjWBURb65Psg4h9Ni4upqO2YAEXYaEjw8FGQnaTi46DC7izZLlMkKNYSKWB3cqH5SF8MFKgosF8YrICJ0PPvjALkJMYpRY4Fmw48YN5os6FiKK7YaWru9AWPN3Z/GkPVRE90HUEbSNOMVVjrijhpazRoYKJyH4RU2BemBYF30YO7QxZDeXg3gr7tePHWMzxKbBxZUB73OsXIhFdhkHWKewjDKfuUXViTrED4IOayOWOhIkcFnyeoihF0lwP/JM/GQNynYQb0aslj/X432Iod8hchCePB+8Dsn4PtrKvEDVBWe9C5nJkyfnmI95FszfWPD9sUV8MJbHUGuEbg4SdPkM4o2Fx7lY3YCn7AUB+Ozy/F1G6NY5IIiUDDsGPYKNMh64u5LuVGJjQj8Pj789ExqWOU5D8MFVzP1jqcP6A9OnTw8+rpHFn8mamEbnvvN34Vh8OBmC50b7iJ+JIe60fPnyNlnAHUHEs8Di6IrSJuNhQo+Z4zQR/v4EmzsBhyAnZCFkFysQ8O8EGRvWo48+2i6geYm6UIsebwgsPXgZOPIOqzciwYkfNkRsaHNLdgi53znoZ5THImP//fffX+++cYOzMQpd/Pz+f+WWKOaMWHMF4RF4VIzA8xXbs9kUJOgyYNomIw1TLztv3CZMbmR9YY1jlw6xxCcg2nCfMNgdWIGw+tDOZMZQqJasJLgdeT5JCOJmUcKEH9pZhXlB38ItTP8ik8slbfiTGX2QBTnEDURuAf8sLLQJVxCxgCxGCDqspTyjGEHUIdyILy1VqpTNvsMFSXwWbsykRTIUXCIAMbK++MGdmpeoQxj5G6EQYxrzSjQhWYgNOQKcMUXsH1Y7NuTumLmQyetvjRjCUkdYBpum5BwRWmZubqxZs8aOI4qJMxdwfjYhQFjtKMNC3HaIJVa2FhJ02xi/Do4/QTB43K4OFyVmexIhmMxjAWsiCRBYSjhn0YeMQ1x3WLr8tPYQJ+4k3CMTNPfPYuVPZCRJIFZxtYaezcrE5p8mQkwc2V2IOn/xJe4s1BIR/pjBxciOGyHtngkbCjLAcSvjDifQHsHgFqRQcc8IdxbWuGTpB/ofNfXY+BHDicUheRxWSLjNDaV9nCs4L1FHLCfPiJimELNzwb8v5mY2DwgCP2GD9lCVgBMHaI9fVib0fscmj00Q2exY8P3nSPYqos6dohLqM/Lbw1w8ffr0HJseQntIymHTh0WVOYKqC0OHDk1lKxJ0+dDZiPfBPO+qbTuXFrsJMonYQTDpsStnRxF6/JIPkzO7cxI42AX5UMoDscrEEarF0T0jMvO4fwQcIIQQbljpmPzcTpUAYU7qCP2UDuL+iE1CvFHF3tWRY3eKqKNtWBOwAhEbE6I4TRYwZWKmHA4Ch7IkfhIR7lUWXWKycFuG7Epx7UIokNXJGKF8D8WBfYs2FiwyJolHI0YrRAudv9khlIK/PbW8nPs1KeqcG5ykCcRf6JCdi8vbFQdmjmYD4RdMph+SUEACTgxWLOKdSUBhU8pGHCGKldFt/hB1hJvwuh8XGOo4oi+RsVq5cmUbVkJIjJ9wx+aVsYbxgTaFGHu6tZCgy4fBw7E2nJWJCRgLAu46gu59yDzEVRlyYHBe1jUmamKwsCgkRR3noIaaBOFPCLhPED/Ex5xyyil2IsM9jJWOD0QEx/bwLEOfEBAB7LARnggfrDzEaLoFlIWXGDQmP47yCT1mjthLrMDE9mDJIkwBgUCf8xdWV7vMPyQ95FhaxCm1DLEmsulDtLHpc8/JWUYQDKEnRpHgwHjB2sM4IpY2aalj44fLNZZaX8wLlJTi1AD6GfeNwGMOcFae3KxXIfc7xjpznTtfFi8L8c8IHax1bjwxR1BzLuT1yFUiQGTTnlGjRlnhhnGBTVBuXodYwmQ2Fwm6bYAb5LhVEQN+jTk6HTs5goZDq+y+IdwiSQA67WFR9eNFMG1j1sYqFLpASIofJjRXJPjdd9+1k5ub8FiMcHURyE2ts9DFHLtRaiz5JQZI5mAHS2yZ3+d4TiHGzPmV69lpY0mgTf6CyYLK2HKxm8nNRihuouR9uPvkiD9irvzXcL2SmOKfnBBKOzYEmx/GDJZgePTRR21ySlLUsYlgjkgWeA6FpNAkoxMLPdZe3+LL80EUhR4P7DY3fh9CpLrzTF0GPPMCr+OOZI5zlu+Q+l5e98I4IsnQ56effrIbVTazDvf8Ygj52RIk6LZiZ2PSSi6u1F8jA8yH3TgLLLuJGDqZb8nCVE+sEuUh2AX52Xe4X3mPSTCWs/Ao3oxgcAsqVit2pq7d/i4vpAkuCffKREYcZm5ZkYg6XJa4WEKt9eVOEknGk3H2KnE9uSWuYPUOFddfcGcPHz48R1+69NJLraXe4d6jdAzWyFiK67JBYDPknybgxBCiDrHgRB2JN6EeIceGlOQu3xLKGGK+c2LAPSNKMmFNDfXIq+SRku6esfwSKoIXBfFKvDZjiPYR5oP7H2GejIcOZRwRb5pMssPzhTs8aR0dMGCAdZH7scIFgcJGbDGFCxc2M2bMMA0bNjT9+vVLv45grlSpkpk3b579ft26dfZz8+bNTdmyZc3QoUPt94UKFTIhw/199NFH5oorrjC9e/c2w4YNM48++qiZOnWqeeCBB0z37t3tdaeffrpp166d2Xnnnc1OO+1kQoZnA3PnzjW1atWy3x999NGmadOm5sknn7TvDR482Lz66qtmzZo1QT8n7p17q1GjhuncubNZunSpmTJlivntt9/S17Rv397cfPPNZtCgQWbgwIFm1apVJjTGjBljjjvuONO6dWvz+eef29f42x966KHm559/tm1yYwjq1atn/vnnH7N8+XIT6rwwZ84cs/fee5uuXbuaESNGmJUrV9r3jj32WDN+/Hjz1ltv2e9LlChhPxcvXtyOn9KlS5vQoW0dOnQwXbp0ST8X177LL7/cXHjhhWbSpEnm7rvvtvPjDjvsYKpWrWpCGzvTpk0zbdu2NT169DCPPfaY+fvvv+17p556qtljjz3MJZdcYpYtW5Z+RiVLljSlSpVKzyGhwVwwf/58s//++5tx48aZDz74wBx11FHmjz/+sOtO/fr1zaJFi+w1bdq0MUWKFLFtY11izuvUqZMJbRwx/pnfmjRpYr788sv0e2eccYZtC/MaFC1a1H7ecccd7dwQ6py9zci0oswG2O1g1WF3Q/yIf3IA5nniMFw9HLeDIlaG1OpYIMOLMiTALps4BWrNkfBAIodvEYqpxhSJG2XKlLFWEdyqvmuF4G6ea+gnWiQth1hLsNLhjqB4ZjKmMdRaUiRyYGHEcoW1wGWquv5GDCMJKlhKsIYTQxd6JX6sIhwNRX0vyqvQRu4ftxb15vxTLOh7uMOI14whMYpnwLzAs+JZOPwEKOYF4udCP8KQuQyXMMeqkcDG8+F5UOcQTwTlLrA0EnLC3I0XImSLPdYsXN7EBJcoUcLGcvtzBvMCsWeEMmBBpoYoyVKhupHJ0KeOHMlDhCW48l5YsnG5Eurz8v8dv8Z6TBIV483VCy0oSNBtJSgzgDAg+JxK6QRyO+hsnCVHSrs7XoVrQw449Y+/IoCbYFnM9ogbgpsx1bsFi7YRKByyQHXtQcwwGTBhMyGT2UVGF5meTkCwULGwkkwQ6jNy7SGOEWGAsOEIJd+VjFsoN1EXKgRi4xZmccUliVBwGyHc4dT8IqmIuB82Tpzc4eKeQgxbcPfEuOfZIFRx6buAesoscKwXp8QQD0iVfjYWIbrE/WQTcGIGFx4xczwrNyckRV3IiyqijXZRhJa5m+QOngcJRbxHO5izeTbEmJHFy/zu+l3Ioo4QGYwMJN8Qu+3u17kln376afs+myXmvxD7HfB8mK9xr1K/kOQNhKo7jYhYYMJmqlWrZucPNhchHyO3LZGg20L8jCbieagtx8TALttPhiAuASHEhM6ONdQYM3/SRswxGbhYP0AMsZC64HpKKZDdyqLlH4cTIu6IHgY79f+oKcekTUwJZzE6KwrPCUtR6BMCu27qk7ETR8AxKbPwOAspljomOUqthHyahR+4TbwpgfPENDFJM16cqMPK884779h2ESPjxl4oWYV5JUAQv0ifwuqGpQfx486cxVpHTC1nNnNih3/EVwi4GCT3NyY7H7GDZd6VtKC/kSSFhctZ8SHUUkW5QYIAyVGIINqIeMNi7/ctBATznXvOofS7JK7fYVFkjuN5IYAQq+B7IWgPVu+QYs38ceSvRzwbjAdYSdmEM487UYeVcdy4cTYLmXEUYomf/ECCbjM7m+9WpNMxSHAvINwwAxMMzATnu19JmWZSTyZPhAgDHHcKBxj7A4vdEC5klxWKJYu6PyG7iLh3rFQkclBWgYWIYqCIN6wLPFMskJjsCYzGDRu6OKXcgN+/aB8JOFi2/EmQ4q1YFUJM1ydRgMXEn8DpX1iymJwZRzwnRF1ehYJDqTfnJ0AgCNxB7Q6y2l12IdmtuFrJqA61oLNL0MCCw7MA3MW46ajnxVhC9CC8gTkNUcfr1AIMGUQOmxwncBxswN1xf7TLuV9zqzkZomXOjXvcpv49M46w4iPq6HP+hjC0WoDu74onhQ11cl3h+ZDBT/uYG7Bou6P/hATdZoGrBCsVpl8K0rrMKNxz7PKwItARsZyQ6cVEFxPUjWMiZwJIZq+5+kTEaBFzwS4pRGuj7yJyJnusp05M4zrGRYTrjucT8sLq45e44O+PFQTxjeWRSdtBH3SEWMMMVzF9jEWTeBe/wj7V93kuiDXnTsGV4oo+hwqxfrSJRQYLPaLAZXhiXcCS7WjatKnNwuP10OqyuUWVfsUcR3gIgpowkieffDItGihxQXwghXbdJpf5ApdkiBZhxg5ztzvVATc3llPGChY6nhXufJe9ikWf+DOsjv6JKyFDPCZ9j75F2Q439umbzA9Y9LFgMeaIRwtx40q8nHMVn3nmmTaO0Vl7XfY08Bo1QwmNCf1kmPxCgm4TYeEnWJ4Oxw6V6u5MzlgbXIdzsSRMHrgmcHs5i1aIMFlhwcHF6kzvBM/TRnbbyVplCD4mQdoaaoC9g3gl3KlYRXB1J9vNs2JSv+uuu6JwETnLDwsq6frU/mIRYrJ2woAdOeLB1QkMMb4MlyOWOBYY4vywYGHdYbFhLBFH59wp7MAZY6FbfhgX1CdjMWUhoj0kciB8KBzOwkOsrQMLMcLVP/EiFDGHuCEmlr5E3Uwsc7TH3yjQ32gbMWcuIB1RF3LMHGCFd8d0EZeFKGBzhAWSPolb3Ak4xCoJECGOoSR4HthMsCHCisUJJPQv535kbud5EU7Cs0wWgQ8FxDXxsmwW8DAwv+EFIiyBscK9OyMJG3TmduIAVwSavJafSNBtBriJyF5lp8BixCKEhYTJAdHAzs+djoAFj0DOUE9L4P4wYzOhkdjAro3FFBceJnkmPib20I+6yg12bdw/FkXED9ZEgtN9iwgTNxYg4rZCX4hwj3BCAueXct+IBgQRC5IPkzYTeYhWEgfPgJMfENPEMzJR4/5250jy3PwkDwRGiG4uh7s3NnGMJaw6xM7RRueGRBTRXt9iGtKRa64NWKj4+xOX6azyeBt4DXelfy1xZLiSeS9ZbzM0fPc8czKWRwQbz4yYTMYWoptQhtzCYkLuf9RnwzrnF+Bmk05fpP/5MWXEooZotfdhXLAxoq4pbSOBgxh14k+pqsAm3Qk4nhUiUEjQbRL+Lo24EqxzuF5xtdIBObqLnQWTmwt6htBcKg6sBrhOibti8aEdiAF2dri4MH07Sx0WrBhi/xwkbTzzzDPpbGMEA6n5iAfcDX5AM/FzIYsfBy5HdtcuDgbLFRM2BUI52QJrJLGbuMpDLXoK/tFcxJsxZhDU7pkgDHCP55aUEvKi6u4Nwc1zYdFxhVBpJxmtzBEhBtS7e2fTgPB0J3D4lmGeCW4wl6TiniPzGxvb0E9RSfYf4uNwqTrvCZ6IsWPHphO+YrDKuQLCiBzmaca/D8KNvohYpV2xtAlYU1mLKCzuPEdYgtkscXqPWB8Juo3AHwT+10xsp59+ul2QXOAwg8stRCEPHsQckzMiJ7m4EPtDeQhcQriYSSTA/H3rrbdGIeqYCLDIEc+I9dTBvdNeJjfcEqEtqrmR7EOIApIEXL0oRB6WOoQezwxhxLONBawmZHmyMUJsu1hG5/IKeQxtSDCweHIaDBaG0IO23T0jPkl44r5z24wieCiPgwU1Kepiwhd1WOoInUHUxXIqTG6wgSP5Ccu8q/nnng3x3FgeKecRQ1hJci4ngYi1yIWbhGogCQEJuv9wR+ZW58r/GrceCyoLEu4V937IEx2WNyZuxKiD+/UFDhMcE7fbvd55553WZRm6qT5Z8JSMPB9ifIjLqFmzprUqhEpeda5IQKHQKZm4ro/hemDSRuSFGLydzERNjg0n6nB1IercohNKBuuWijoK0XJmcIj4blY2eMQyki1N7K/Dnxdw4yHq2CwRehIyybHjf58UdZQswqIfUjxjXrjxg2eBdjghyjNEuNHf3DztriWcJMR4541ZJxF1zNdsxGOpqZkpJOjyAFcjgoBMJzeh/ZeoI6bOJUeEDJlN7OQINE1mDvrtIkCY1HBHqDFmuU0KCDeSNpgI/NpYTvARaxJahhcZhH7cGFZfrHH0QRcDg9AjZs6vzB+LNQFLVV4WAifqiD9lRx669dT1ubxEpy/qsJwSWO+SPEKD2pJY4EkWoD30QzZ8GxJ1uJOJG0ZUhA7JDrmVVfLHDaEmuCy5NoZ+R0gP8aZYrohv5AxkwDrPSQqIOtfmkI0L7t7YHCRL/SRFHRZINkgxhMdkCgm6PMDSwW6VXQHJAf8l6saPH28z2gh65v+GPIgAgYA7CAuWL+r8+6b9/qHoIbbJ3RMWEEomMDEjDICdK4H2WE+Toi60tmAZ4N4RM2RzAYITKyqWK4QO6fv0QwKAyfwiUDhkyIh0pToo0ko5iw1tChATxAeSXBSydc71HQQ3wfR5HTjvBAOLLPMIlvEQIW7MF28kQP2XqMMCFIO1hMxPMiCZnyHZr3xRxwYw9I2Eqw/oTuZhfmOOINOY5A4Xw0kIxn+Nt1CgugJimnV2Q5tTEgsJpQltIx4SEnS54AY1u09ikuhEGyPqmDxCqri9KaLOdwkxqBANBNuTLBGiAPLBgkW2JxnGLJwuQ5IdH+5I4uhiKHjKzpNJmphM4hUdCAeOJiLZgfIdxNEhtMneDdVCwsL56quv2qQb2sO9b0z1dn9CD1nU0efICMeqtaFkANeGWGKX3DjHip2bqIsxfonNEDXZ8iLZz0IWdYRVkCTgCooT14iLHCudD/UbXWJbyOAGJgmKMisbQ8jPJgQk6P5jkG+qqIuNvCx1WIuwDIWUDp7b35kCu9T+wlrl3icTiiNiunTpkrY4YL3D7RWiud6dNALUhuJvz0JK3GLyWVE7izgzRCuuldCTVHDZc6/UiopBqG0MPCOyCjnjc2PbEuMc4Ys6PxQgVJJzsxPRhMFgpXeJHDGDu5tQIGJpsZDi9mZj52803PFxoW8isGwTl83GyB2TGUv4SKhI0G0EuFDZFW1I1MWML+rI0EX8YPEKqfSFG+jsSIn5YQfqMvNwqXCv/vOgvhSnEDiRSvZx6O4HdqqITtyUTHSIUt9SB7QRKwnlWCgzExr+6RzcJxnSHIlH+YE2bdqkr0suNqGOJeLekoHyFHMmdskX09m6ENFGd4g75X5CTV5LupD9PkVxZKzE7jSSUPtaXvj3i4WudevWdjNBwXrEnNtUYI2jUDpxgDG0kbmctYbNkS9Ks3Us5QcSdB5uEDAwEAq47PwyCtku6pgoGFwESIdURdyvkUWMIuITccBE5gK6XcC5X3qASRwxEQPEWSGiqSfHLpxdNucC4zbxa4KFvOv2J2LEnBsjfE0pHCypvqhz9dlCdeNRRJdEp2RAPYV0sfg4fCsdG42QigVvDbBwE3qRFE4hQHITCV4uRg4rHGVIyARn7LtAe0Q4GaCuxlwM+HX+fBA/CGzGkr/+ILgpxhuqmzW3tZK5jnASl5TjkKjbPCToEp2NattkFmL1wZxNTJMLNnWi7rDDDrNuvWzz59NOMl9DmvTcc+GeKJXAYsqC6Q94goLJgGIn7gsf4uZCPnLNh3gz+p1/IgftpOgzx/lQhiUWsISQBUlM46hRo9LPAwskyRxsHHC34Ialv4W8KXLijNADMqeBNhGEnixuymaC5A/mhpDbtDmE2h6qEbDBI6uTzZ17VhyFRyY4YwdrNoKUODqXSBS629/PZmWMIOLcOboulIHNN6d5IFxpL67LkLwqubWHjTfWRYQ4GwTmBcaNixH2S0lJ1G06EnQepH7TqQg4JZged1eFChVsEDrWISfqEApMFrjxso0QrSVYSMjY8oOz/QFPQgeTOtYsFltcLhQOJvbHF3mZZkNxlyQ+kJmWjPNxQpasNv9Yn5DwJ17EHGOGmCuyvtl5Y3UEJm8yX3G/IuxIYMmtzmNo44BnwD1zDiuijgUIoY3LyyUNYQly84WLYRLbDv9MXPoUx0IxB7jkLgQbmyP6I2KPuDOsWrjKY4E5Aas9J3TQPvobGwYHfZBKBAceeKA9b9edShIqbOg4bg2DCOOfscKcxtFyrLdsWpmziSEWm4cEnScasCq4HQLB81jpWHSYzNkhuZglRF22uVVCBjHNhIxQy2vXRoYxkxpH+WDpwvWQ29FRIcQA4mbILSUfFzHZan6mNP0MixZHr4Wero/VDbcPZQgcTNi4wPwFGFFEbKN/HmgI5Na3XBIN1h36FNYF7pfnRdINgpX+xrNDkIfU57IVSsVgofJFN2EwiB4y85NFnEkewCWLixKvSyxWez/7kw0DY4i42quuuipHTB1iKORQDGDt5G/Ps3OZ+bhYqdFI8hdjj3kRjxhij69D2+TFgATd/8GuG3cru2s6Ey48F6jZtWtXG6ROhfSQ3JEFBRIccHG5AZ5baQtENpMGzw4RlJtoyjQIMtwiTFi45RChuZVfYedNLT2O8EEgkWUdYnt8OEcWCwiTti/onKjj+WGpcwdqO0JzfVFGwVmCX3/9dRsz66run3feebZOIKLOLaC4+ahfxuKrTV7+bb5dvxk5cmQOUUdiF6KOYu8ON1+Q4EHpIubxEHHzG5sCxhAbVJfI4cSbE3WcQxsyydOSENlYGJmj/depuYmlzlVT4NnmVgRabBwFVtDlpv5dRyKFmkXUfc+EzS6cycKdkyfyD9yQuBwRPHnx8MMP25gsPykiNNgMYEXo3Llz6tRTT7Wue9z5JEQ4ocOixOvEx2AhxgURi9WHRQZRxxFKyTHWq1cv+x6bplDhfonJ4nB6xjr3m4yTc6KONoZeMibbwcpLogNHd+Um6lyihG8FZuNBck6oRZG5f+Y6vELE/yVrZ7qiz/RNwkpCh0LhxPWxQfVDYPwjCim/xBortpwCKejcQkMmJx2OGAwfsgrx8zt3CxY6yi9o55AZcEEicAgO9qvy+4Lhuuuus9askM30WNlIqsHCA7iQKVNCu3CrIuwAVxLZkpwNHFIdwI0JVsaqzZmgjKskuFtCca9uCAQ3C6Z/vJpvWUTU4X6lSn8MZ39mK4gy3HZkHPtxV4gilyjhSpg4cJPjffGTjzKNm7OwwJFIxDnNxMMxT7C5SBYNpvwS74WYdeyDB4Jx5JKE2KhSpSDZFuqdYg0XW06BFHS+e4vdNgsQ5m1nxicTijNAibng3EzeD7HmV0GCAU983LnnnptOUHE7vW7dulk3ZugTnDu2h3t1dfSA0hjUzCNOkBp0rshmiPhiDivV5ZdfbkWcv8Pm+9KlS+cq6iBkUcfCg5vrwgsvtBX4/SPj/FM5yKzmBIKQhEE2k9xEuO/Z7BF3xRmfvqjDEoyAYKPnrucDi5fLhg0JyvdwHjj35wwJjBOy33MTdSFvXAGr3FtvvWWzcB1YTJnjKIzO+xhUcLmyWQ89PjgWCpSgc4MAEcDum50QFh8qidOp3LmTQMFDYi0QdaFnDxUEmIyxkhKLVbt2bVtAE3cl1i2eXQxuSfofVl76FDXOgAw24s6Y0JgAmbiJkQnxRAsf3Fy4u7BeUy8Pd8oFF1yQfp8yCmS0bchNHgq5LY5Y5MhgpY1+u8DFyin8Iv9hs8O4J9vTuU357ESdX/zYT6IKvQQGsYBsWNkI+UfJOVFH9QUswzHA3IUVFOscm22/LVjt8H4RN4dbGcOJv7kVW0aBEnRuJ3TWWWfZA8D9CZndA5M3ZvrQy3gUZD777LPUaaedZlP1cVeyK9+YM0JDApc+WZFkTmIFSiZHhBib5ScvjBkzxu60XYwSCQEsRK7Gl4PnhIs5BjHHvECpFayLLvGJjR+ijhgfNhD8DShNgoVBlrn8B9GGECDDFTcrX7swBUQdcZqMKwSfT8hijjXIue0pU8ImCEOC78pHCBHLyVwR+iaCGEUqRTBuENiUVckN6tG54v1i61HgBJ1bfJgMXPaaX/SQ0gONGzcOPg28IBNaZuTmVH4nXZ8JOvTdKTFKroyK+7uTdUx1fucKJ3MX6ylQmxGLdwyLqb8I4daibh7PhVCMV155Je1mJVGCAHVELJbIpAAX24Zk3yHpxpUkwaJNmSmqD7hiuliGsBifffbZwbskATHKZuG5555LCzgsdaxPbCB8UcfYc4WtQwVXNs8DiyIbHsYQ48VP7NC6um0pcIKOCZo4JhYh4mRyy5zCDBxiMLr47wK9McCOm8WJjUPI7aD0A64TMnN9ywAFuJmkETqIHyfmgEQO4ur844dCFnUskrfcckuO2mS483B/IVzds0FA8L2flCO2HX6fwRJMGQ8qD2Chd2CVw1qH2Haizq9fFuKYSkKMNuU8GEtJUcf6FEvxerwkhCkhqP2wBRIiqlSpYr0RsW/IYyCrBZ0b0FSiZoHxS1pgqWNXTs2vJMlaWUJsiM1ZOIjDQgxRbiVUmHiJgUN44jp1og6XJIsoMTKPPPJIjs0S2YXE+sSwmH7xxRf2FA6SUpKZ7k7UZeMRfzGBQEDckFVMf3Mi24FVjhJAvOef0BFi/8vrnrAoEkeLqHPlPEaPHm3bRExtiG1JxgUj2ooXL25jgn2YE7DUUYKJUjJi22IKwtmsTAYEYDJo2I27mCsn6pIZREJsqiUBseP6VW4TsP+a26GSWc0k52dPhoIfO0r8DvGKxJe6mBesdJwAgTUO0cf3WFCIbXICKOSFyLWRZ8DC6UrJJEvh8F4MiR3Zgv/3J6mBWFl3nB/Ch+QAxI4P3hSSIWIQ3sSfcv9JKxVx3YQBIeqcVY42h1xdwX9WWFCp1UoJEr+oMzC/4VYmvtE/BUdsfbJO0PmdjImAIo0c/EvAKcHonOXHJO52c8QAMWmHXnlbhCvmvv76a7vwkO3pB/myYaD2Wl5QbDOks2ZzG0Mc/E05BcIQGCcUbXXZhQgdJmliAclcw33khGAsbhWs9iymxP4ka5bBTTfdFPSims3ZrFjn/KLBCDZEHVbVpKjzrwl5rjj88MPTfS05Rqi8QCJB//79g65v6OYHd/+ubTwT3Mc8I6zfSa9X6DGA2UDWCDq/bIU7dgR3KuLNB2sD9aM4P84Fab799tuatMVmHxVFmRHqKflxlxTMRAgRO8IONXRrVW5wWDZuYZIGiFEii5CjsLDEubIqhDPQbj67Noa4qLp7IxaOeoX+eGdBIiMXN3Juok7kP4wbNhD0NT+ODBFBFihj7r333kuFjut3/tF9TZs2tadVYNXyRR1GBTxGJOaEmOnut4c4PzxbrK+spYx/ly2OqON1F9co8o+sEHSkSBO4TaVtf+GkBAF1ypJBtuz8cMHGYkUQ4fLAAw9Y65SLu/T7GeIAkcDRZRBTsDbtYexgoXJw32yIsNbhfnWTuE+IbXP3RDIUhcRr1aplF04yeF1coBN1ZB3654OKbY/fZ/zxQxwjdSep2ejHNXMNGclYi2NoFwW2GzVqZOtMOjgRwok6F3KB25ikvNBrUBLGhOeLpA2OW2STR7F0V58RUcc4Y/7AeyHyj6wQdOwEXKVpPxsPqwkTtLOcuMmCDomrSEd5iS0FwUPGNOVHSNWfOXOmFTr0Q6xAuPM4c5HXYrMC40LlIwklFbCeYOn2LQ8hgzWHGl+caIH11J2H6ReoZX5AJBDAHWJcYzbiCzjc9UlXI32NpAgC65OiLuTsaQebCDYPnJiQjC3DUkfcGRnjWLRoJ/NHyDDeCS8hjMlBPTkMKhhJFixYYF+jdBHxdKGemZutmGza3eG3x1qCxc7B7oEOiOBzNXCIdaI4aCwp4SJcyEpj903iDZ/ZKFDqA7dD5cqVbRA3wgExQR0zN+GFRG4LI+MKFyuijfhT341KfBMTOFXgY7Bys3HDhUd7gLmAhRR3nkvscGVW+FsocDt/8PsOAgGLDtZTvvYzVhF1bJqob5YU2iGLOsY6x4/5x18la7FhlUPQcZZzSNYst666uDc/ZIEC/Fjh/OeIUYW5gqx390xcxq7IP6IUdP4g9jseNaI4vovq1O5oJV6jCCrHQ5GpR1Yhi2syaFOILVmQcD9QroNi1Vjn6HdYhhESnAdKLS3i7UIeS0zS1JFztb7Y8DBJH3rooTaODgskr1H766677lovODpUuGc2eYg2LAxk4rozWhEPxYoVs88vdFdXNlu58aQQi0VNQ+I2L7744hxnrvK82BjF5A5HlFJZATeqH9udmxANseAucxmFgf0ajSQRIVLxOvjQLhIOO3funOM1kb8UNhFSuHBh8/3335s333zTFCpUyAwePNi0aNHC7L777qZHjx6mYsWK5vHHHzeDBg0yVatWNRMnTjRdu3Y1RxxxhDnooIPs9wceeGCmmyEip0iRImbNmjX265IlS9rvd9ppJ1OpUiXb7+iPxYsXN9WrVzeHHXaY2XPPPU2IYwkYH6eddpq57LLLTOPGjc1DDz1ktt9+ezNmzBjbhm7dupm6deuaww8/3EybNs1cf/31duyxKaTdIcE9+dCOE0880VSpUsXOCeXLlzd33XWXfa906dJmn332sXOJyB+GDh1qhg0bZr8eMmSIefXVV81bb71lbrrpJtOgQQOzfPly89prr5l7773XfPHFF/a6Z555xvTq1cscddRRJnRc/2PcFCtWzMycOdN+78YLjBw50rz99tvp/8O1oVGqVClz3nnnmc6dO5sXXnghPV80bNjQjB492rzxxhvpa2nbbrvtZsqVK2fbyAeviXwmFSnUk3PlRvjsu1nJeCXD8IgjjrBB3EJsawh4ph+ym8XSQzkS3CnUlgrxrFl/98z94SomDpCiwX379k0VLlw41bNnT/s+sUtY7x566CEbe+bcryFa5ly7aAtlVYhbcrFXvOdO6HDuIMpiDBo0SO6hfOKxxx6z48QlClG659FHH00nD1CShFpsJAtwHZY5Z+FyhJxF7UOmKskPxMq584EdxG7iLQq5PIlrA+cX+0WdCWEg1hTL/VVXXWVd4Vjm8HzFFiecbUQr6IA4HtwlrjCwP6icqMP9Sl0fh8zAYmvj+hSHUjPx4d7HrUdNKb+cTojgOiWmlAUmufAi6lx5nyQhijnHG2+8YYUB7i6ewQUXXJCOBULk8YzIaCU8g9is5GIrtg24U5mvqf3pu/UInOczNdpcvBkinJhTnpWLfQx9/HPOLMdfsZFDqAIbO+o0Eq+JcOVEEmI2ia0lmSAUki5gRLO/VmIc4VlQINiJOjZDxKKT0Uo4k8KYMk+Ugs51NAYJu22OHHGHafvvs5iyC2I3oaKGYmuxoUBsLEKcOsCEHnpMFnE7zsKdWwmIxx9/3I6tZLxMqDDuEQJt2rSxlnmKPHO0GosOAffEAAKLEmUvKIAaUiB6NsOYQMwRi5k8OQEoeUFiEVmhQKwjG3WuD3nz4GCjQOwfFjksV4wprFfEnBFPe9JJJ9mED0QqyVMh1mjjGWCFT85ziFQ8DSRv0C5nIOG5cA0Z/KFbGgsKUQq6JNdcc41deDh30Qc3ChlryloTm4vbHJDQQJA2JS/+69qYhCgiB9cq1ji3+04WF2YBCrlt7t78pA3n+sHS8Pzzz9vsd1/UMTeE6LrLRhBntWvXtpYcH2oZUtMQMUCxZ7LCsRTjAkdws1mPIfGGuYGack8//XT6flmLKH7sTiCiv9H3sEaGaFzg73vDDTfY54GAc2Chp5YmG1TGiwt1YkyJ8IhG0LmBwsAnPiYZV4Goo9ghA4nBg5mehYgdkhBbAi4iJmcmbVx5ZFA7YRALvphD7DB+2Oi47DqKbSPqkoefx1IQGcsOFh7ilaiH5VtHnahjPsCCEuKCms0gFoiJ4wB3V+gdaw91yvy6a/S93Xff3Zb9Qcy5Y+RC6Xd53QdWXsoUYXXzr6E9jClcsTHAfIBVEQsj1nkywJMnciC+OUITUed7xUQYRCHo3CChIDADh7gYijVSasCfEFiU6GjEYlCkcfLkyRm8a5EtljmEAvWViLUi3gxRhyuPk0liwF9kqB1HfB/lCDg7ksLHBD4j7CgfQV22pKU7+TNCwd0TCyqxcARvE59E1XpKKzhB4EQdCStUtvePaBP5B/UMKU+CaxIx55/S4Z4lpWV4Pm4DEooV1a+thsURgYoAYuwwRzBuXOFg34hAshHnIccCz4QEB9zDnNLBeejJ54AVHMvdd999l8E7FdEKOqA+FoGkZNkxYMiIQrwRB+MXoSQgmok7xJpfIi6I72Gn6tdWAlwTHLCNyItF1AELC7EwLm6Jo/G22247u9C63TeijnHlFw4NmQkTJqSGDRuWuuOOO+z3iDjcQwgGYuf8xZVFKdQzMgsK9DU2FFhKHb6gC7FosLsPvEPUmsR9jDeI9Yj1B8scGz1e99ciNklsLPw6bjFA7OmVV15pz5T1xagv6kLc4IlIBB3uLaxxrowCVjmCSwl+JlWa44n8dGl1NrE1YLJG3HDaSNLFSiYb2ay4JUJ3vzIesCwQmO0WF0QQlhLifgDhw4TNZ0RsKJaRDYEAZdFx5S0c3DuijhNiyL5T2EVY7ldnqSNOLjTxlsTd11dffWVj/C699FJbIov1ho0d6xBCjuxcxB5xghQ/5hxnkomwhJPpGhvOUof71T/pIuRYRhGJoGNCJlCWgUF6e7169dITOPFMTOiUIIhx4IiwYVJzsWVJYcCunHitDSVKhLQwkRXOQoN1GzGHcHNWLYQdVnCfGEQdmezNmjWzCytzg7/w4C7C/Up5IxEWiDrKeTBvh4ov5rBkE66QHBOEJ3BCAsKHpCKOKSMciOQCQjVCL1u0MaKOkiWciy7CJ0hBl5uFzZ27SnAzrhQXB8NCi/megHV3HqMQm9vn6Ge45fz4K+LMsARTmiB5RA8p+6GRtHbQNtrTqlUra23EXUxNMAfjBrFHaYmQ8ecFf2EllodYJdysvkuVa3Ava6OX/2yMl4TEHDbjXbp0SYUKYwMr2+mnn56jbX7/YyyRPOCs38TaUgKEWLvYQdR16NDBzg/+hkmESSH+MQHhjgyZMGGC+fLLL80uu+xijxviOCXe69mzpz1yZOzYsfaYEY4k2mOPPUzHjh2DPD5FhI/rc++8847p16+fPVaOPscxRFdffbW95uyzz7ZHFj377LPmuOOOMyVKlMjxf0Nh3bp16eO8fvjhB1OmTBn7WuXKlc2MGTNMq1atTIUKFcz48ePN6tWrzYoVK0y7du3MsmXLzIcffhjcMV4O93ceMWKEPS6KZ3TCCSeYRo0a2eP8pk+fbo8uK1q0qPnoo4/MDjvskOlbLlBwFBQccsgh9qi1JHmNk6+++srsu+++wfa72bNnmzPOOMOOH467o7/l1qYjjzzSjivWJn8MZgPz58+3nzlSUwROKtAyEVhEXCFGTntwxydxyDk154iNYdfAdZjEhdhY/EOyHRQwpV+Rkk8dpvbt21t3qqsjBcTIYFF4++23U6FDfE+NGjVsGQhcP65uFPdOBjhhCwRsU8qDWDNnkQw5RoYs9xIlStjnQHwj7lQKIrtitFjqaBfWemfRF9ueZ555xibbMG4IqHdg2cnrpJEkIfc71h6s2/Q1v1yWP4ewRrVr1y5DdyjE/yM4QceRImTfEY9AzBJnZHLaAy4VlyZNyjhusMsuu0zH9ohNJrl4/PPPP/YoKESQA3cJR/UgilysGVxyySWp6dOnp0LDX1zYEJGwgXgjJIEjeogDfPDBB9NuJBZaMkMJ8HZ/j5Bj5hAKCFDXBvjss8+sK4zF1h2jxPFDxPzIzZo/kACACx9RzTjy+yMJQ2zKs2HD7Ys6v64c4Q2E/7BGufPElZQnMkVQgo7JmPg4ioP66d/EwTCYEHUum5VYplAzo0S4sMgQRO9PvAgZxII7E9gXdQiGiy++OJpJmoQH7pd2+lBiBeti8uil0Cwkef2dSTxBXCcr1CPqCK734/+ScY5i24HAJnYxt785xZ2Zt2MpgbO5ljo2gvwNVN9QZJqMO/pdCN+3335rxo0bZ2MpPv/8c1OqVKn0NUcddZS58cYbTbVq1Uzz5s3Njz/+aOPlsilOQeRPXyMujjg5n7Vr15qGDRuaefPmmV9++SX9+s4772z22msvM3nyZLNy5UoTOsQj9ejRwwwaNMisWbMm3WZiei655BJzyimnmNdee82+5953hBDDxH0Sk/Tnn3+a7777znzzzTfp95YuXWrjFhcuXGi/J/7PxWwdeOCBZtSoUem5RLG0+Qcxi//884+59dZbzccff2z71/PPP29efvll8+6779rxdPfdd5vhw4ebp556yixevNjEyt57720efvhh20d79eplvvjiC9OnTx87nzz33HNm9913z/QtigJO0UzfAIPj7bffNl27drUDfrfddjPdu3e3QegsTCRDOFHHJP7kk09KyInN7mtNmjSxXxM4T5AzmwiEQrNmzcwFF1xg++BFF11kE20AAcFEHmKfSwaaH3DAAebyyy83999/v11gTjrpJLPPPvvY94oVK2Z23HFHs2DBArsIh4YLJGdjx3Pg7077WrRoYZ8Jz4M5gSQoBFzTpk3T/5frqlevHlRySkHhrLPOspuDwYMHm08//dT2Lebp0qVL2+eBgEOc//HHH7YPXnjhhSZmnKi79tprbYLR33//bROMGHtCZJxMu1ZwpRAP17dv3/R7gwcPtmf5cUyPH2QLfpyGEP9FXm556mCR9OCf90stNsoPcGg4Ac4kRnCkVIgxQH67GBN+iQTGjzuMnur2sGLFCtvWCy64IBVqW6i4T8LGddddZ+NkcYGTqEIso3ON407mSCKKjHP8GkkrJEbpGKLM9kHGCueAJt/nOVFgl/7pro8lfGFDEEfL+FIMtwiJjJkd2L1ReqRly5bmt99+M0cccUT6vVNPPdV07tzZ/Pvvv+b88883v//+e/o93xUrxH+B1efXX3+1Fjl48cUX7e6aMgNPP/20deVh/cWlivWAsiT777+/TdXHdYfVge9Dwi+LcM8999jyHbiMzzzzTDNlyhRbvqNTp0623Ycddpi1cnXo0MFaSx5//HH7/0KqVkRbCKPgXq+55hpz3333maOPPtpcd9119v1Zs2bZz1h/sNDfcccd1qqP5Q63F/NInTp1MtyKgodvtSaUYdq0abZ8jANX7JgxY6y1jvAFrndu9dipVauWdS/XrVs307cixP9PJtUk52BSYoBgbbLxfNjFYWngaB+O+AolaFvEA32IYG2svRSf7tGjh+1rLmuVPuWOiKLau7PUxZD1Cbfccos9QomCplSkL1eunC2fsGDBAvv+K6+8YttGMeH+/fun/59fNDkEsNxQhZ/SFw888ED69bvuuss+LywhWPBJiMDS6J4tR38tWbIkg3cuHCQ+7LXXXvakBJ4TczcJBCQLhD6OhMgWMp7lyjmYTAQIN7JcfZi0qT01e/bsjN2fiB9OD6CPIQ4QDj6IN0ovIHwodxHquZ/+hoZx8eOPP9oxM3z4cPsapRQ4csidzeoYMGCAPfqKbN1Zs2al/39o/Pbbb9ZlxxFKjz32mK1pRjkMRCsndHBeM8J0t912s1nwMdQCLGhQtoP6oMWKFbPPkY14DPUNhcgW8k3QuUUE0cYOjg+KBLvac9WqVbOTQIjxSiJO6HNYf7DqcGh2lSpVbHzc6NGjcxV1FOEN8dxPCum++uqrOSxrxO5QMBioAeafzYrVijMm/YUWEUS5BYRg6GdHUruMODnOYnU4Kw/lV7ACTZ06NYN3WnDIKwbV3xT4X3M8FH2M2Gi/LJAQIsssdOy0K1eubIOzWTg58BgLgnO/IuqwksR8oLEIA7eYEGjvzvdEMGDVou/5YsExYcKEIAUPblTOk3znnXfSog63KiIVq1bZsmVznM3K+MHF7NfK4v3WrVunfv3111TIkAR15ZVX2ud03333pV/365xJIOQPvlDDfY/VlELv7vxiX+zlZfUN0RosRLaSb4IOyxyLkrMiTJkyxbrAyGhzEzSijqxCjvRScVCxubhFhBMTKDp7+eWXpw+Wdq5K4nuwyrnCoPTD0PAXzDPOOMO6IHE1EjsGN954o83w7NixY/o6XMYINyyRSesK4Q0x4Cx1WOzvvvvu9OsScvmHL8Q4aYT4xjp16qRq1qyZOvPMM9MbHxV3FyIcCvGPyYeMPA4t7t+/vy02+fPPP9ssQ7LzXJFXstwo4komHjWo+FqIzWXkyJHmxBNPtP2LTOpdd9013RdnzpxpM0IpKFy2bFlbyJrCp2SKhprNSsY32bhk5brMVrIKb7vtNpvp2bp1a3soOlm5jB/aRN0vl1UYW2YhRZ7vvPNO2zZqBFIwWeQ/FHfmb3/TTTfZWmtkiVM4mNqNjzzyiNlzzz2z7jB6IWJlq45CBjb4GpFFE5YvX27T2Ckcipg79thj7YQApLZTrJHyJCywEnNiS/vhkCFDbKkOyt644tS8Tt+sUaOGLTlAeY9DDz3UTJgwITgxB26RpJQHpzyUKVPGFgbu2LGjeeedd2ypDkp4UKJk9OjRtoArJVYQQYg5Cr7yM2ITc8Azu/nmm20hV0Qqp0eI/OWVV14xV155pVm1apUtUM1pIu3bt7eFtynzw3s//fST7WMhlcERoqCyVUvGM7AZ4HPmzLEV+akeTt2o9957zy6iixYtsq9TwZ7XHW+++abdkVOvSIgthcWFemyuNplbcNwJCViwqlatam644YbgBQ/WkAEDBpgPP/zQHi3EvXKSAgsrp0Fgqatdu7at24iI8zdSIZ4IsamijmOjYKeddsr07RQ4mMuZl6kDiIArWbKkfb1t27a2H/7vf/+zp3fgfeGEHyFEZtnqdnIWSdw/uII4Fuacc86xBVopHIzrhJ025y8i+igozPUvvfSSuf32260FQohNsQYnv+czloT69evbvjZ37lz7OgsQoo5Fij7HGZNcF7KYAxZUXF377befLc7KB0V1sSximSOEAcu3L+ZCOZt1a1CxYkX7IfJ3PAEW0quvvtoKuSuuuMIW23YQssD8TjHoypUr5/PdCiFyZVsE5lHTq0iRIjaYNgklByhLQJkFjiciU09ZrWJzmDZtWuqmm26ydQqT2XQUNqUuG0cPzZkzJx3Affvtt6dq164dfLana0/37t1t8W2HK6w7bNgwm1RUokQJW4NOiM3FT2wg+5tsasaPo1+/fqnDDz/czt0uw3VDP0MIkQVJEStWrLBunnr16lmXDwHcuItws/ruH9xhs2fPtmb6atWqpWOchNhYOAAcq+/kyZNtzCVufCy/p59+evoaYjR79uxpDjroIHtkHH2QZAliNjngPSTyCizHin344Yeb5s2bWxeXg6PMiKPDEkccXezuVZF5brzxRhs3RwLR999/b8cICThYux966CEbQkMYA2NKVjkhwmOrCDp+hO+6YrHFBcQiRCYe52P6oo6MPRePIcTmcu+999o+te+++5pPPvnEJtYcf/zx1h15+eWXW4FE7Nm4cePMpEmT7HXEnoV27qc/foiL++qrr6yLtVGjRjYpgOxw2orrlZiyJUuWWLcxcakuS5wNVLa4WUX+88QTT5ju3bubYcOG2Q35M888Yy6++GIzYsQIGyrjNkh8kGjUrVu3TN+yECLJ1nINUZT1/vvvT73xxhupH374If1+s2bNbAX+999/3xZF7dWrl60BholeRSfFlvDhhx/aOmyTJk2y38+dO9e6KClYffDBB9szTn/++ef09SH2N/+eOOaKIsHUYaRmI0cnOXcqJ0UQqkB7OfGifv36wZ3JKuLBuUhd/+vUqZMNXwBOGaEfcgQbLF26NP3/Bg0apGO8hAiUrRJDR/XwkiVL2rMWWUzbtm1rY3wcHDlEYUpOiGBBmjhx4tb4tUKkunTpkmrXrl06toyip8TItW/fPn2upH/iQKhijkLbjJtPP/00HcuEsDv22GNTY8eOTV83ZswYK2Ddoqpiu2JL+t24cePsZ46Ge/DBB1OTJ0/OcYwc/YxN+IsvvpjjZ0jUCREeRbfUTfTrr7/aml64u6hPRIHW++67zzz66KM2Lui4446zr/E+dbEw5deqVWtzf60QOcC92rdvX5tJfeGFF9r4uFGjRpm6deuaGTNmmPfffz/tMgoN52alNMnAgQOt2xS3MDRt2tS+f9ddd5k+ffrYTNZWrVrZ4sLZVJpEZM69TxYr5aOoOED5EVyu1113nY17Pvfcc9P1Q8eOHWvnbh+594UIj6KbG7TNpPDZZ5/Z2AtKKxxzzDH2dRYdFtfevXubxx57zF5HEWGKUCZj7YTYUigOTFwPMZsk1yDgEHPAxiHEzQOCc/z48eaWW25JCzNqfVGnkcLbrsgxcadAYDrV+qnFdvDBB6d/jhZVsSkgytwGgOLTCLm33nrLbLfddrbPsTki5plENSBxjVhU+iXiTwiRJXXoEHNMAFjaHGRCsXtD2LEgObAucFQMIhALA1XsQWJObE1cPg8JAmS6kiBA4kDIVesp0Prqq6/aDyxvQJA5og1BijglC9yBqKMWGIst2YZCbCoU/gUn5uh7l156qbVgU5QaOAmCJAi+ZwPOkV5kjiPmSDji/7pTf4QQkVvoGMxY3DjVgUXp+uuvt2Z5igHfeuut9j2+dosOCxHZrljwyNQTYmvjNgj0OTYPCKGTTz456I0DZ2BSRBsxx0KL1YTND/dN2R/cx5SIQMRRbsVZvfkAnZspNoWXX37ZFqBGvLnM1GXLltkxwlFxbMTdKRwtWrSwR8dxLecdV6lSxc7jWIJ9654QIlA2JeCOYqxXXXVV6tBDD03deeed6dfJiiIh4txzz7XB3T7Lly/fehF/QuTBCy+8kCpdunTqs88+S8XA77//nurcufN6Y2ngwIE2Q7dDhw6p8ePHZ/QeRfzMnDnTZk+TKESRbQfVCOhnJN588cUXGywQrAQIIeJgk7b6FAKm+CRxPBw/hDvVne137bXX2vgLkiEmTpyY/j/EZwixrcGSQL+kKGpMh88nxxLHKTGWqJ9HDTAhNhesatWrV7fWXo5gxFqHBRhOOeUU288IT8BiTO1DyM26rVhNIbK4sDBJEHfeeact1nriiSdalxEMGjTILlIkSDz44IPWvSREfhFjwWp/LBGz5NxiiDliUbWYis3BT0B74YUXbBwc1QhWrVplk3G6du1q30PkUbh6hx12sPN4gwYNMnznQoh8PykiL1H3+uuv29gfdoZCiI0bS1joiAFs3LixzRB36AQIsSkkYyzZYD/11FP2hBEsdmS1kszWoUOHdJY1x33xPnGafBZCFMCjv5yoIwX+6KOPNr169dq6dydEAYGxhNUECyO1wUJO7BBh4sS/S2CYO3euad26ta0t165dO3sNyQ6PP/649abgisXtCu6ILyXcCBEvhbdGHBBZrJQu+fPPP7fenQlRgGAsEaZAVjhiLuTSKyI8EGaUHMGl6rJRiV9euHCh+f3339PXcf5v586drYv1jjvuSHtWCJNBzKk0iRDxUnhrLESY6V988cV0+rsQYtMpX768XVRxm8lCJzYWRBjxlog0PiPqgL50+OGH2/Ikv/32W/r6qlWr2rqGNWvWtGLP3zzIvS9EvGwV+3rFihXthxBiy5HbS2wsI0eOtCKMYsD33nuvrTFH+Auijrqgbdq0sXHNuFk5+cEd57VkyRJzySWX2IQIWYSFyA62KIZOCCFEZqCY+9NPP20mT56cjp2j3A1F30uVKmXPNabSAOdnkwDBaRBY8YjXpIg1sc/8Px3JKER2IEEnhBAR8s8//1jBhiibOnWqPcOY03kQcog6Emw4mpFrsOSRRU29OWo1kknN+cfKohYie5CgE0KIiOGs7ObNm9t6c2Sz+qIOMTdu3Dj7OWmJ03FeQmQXCtYRQoiI4SxjSpNccMEFtlAwljfi6IipI5aORAnO3066VSXmhMguJOiEECISsKo5yIaGsmXLmu7du+c44ssXdSRDXHnllRm8ayFEfqAtmhBCBM6vv/5qY9+cVY16hZz4ULx4cWudq1ChgunZs6d1qyLq3LnAnDwyZMgQe3qPECK7kYVOCCEC5qKLLjItWrQwM2bMsN8j3Lp06WJry/Xr188e2UXyA+KOYsG81759e/O///3PvnbwwQfbxAcVDRYiu1FShBBCBAzFfw855BB7Pvb9999v7rnnHntMHK8RI3fEEUdY9yvvHXXUUfa1q666yma+fvTRR5m+fSFEPiFBJ4QQgeLKiiDqcJvidt1+++3tyTxVqlRJFwpu0qSJvbZv377WzeoyWFVfToiCg1yuQggRINSMe/fdd22x4MqVK9vvEW9Y3WbOnGmvYT9eunRpW6YE9yrxc19++aVNitAJEEIULCTohBAiMF566SXToUMHezTXiBEjrPVtl112MR9//LHZfffdzU033WTPaHUWuO22284WD27ZsqXZf//90z9HFjohCg5yuQohREA8//zz5tJLL7VijoSHcuXK2dedG3X+/Pm29lyNGjVstitHeiXRCRBCFDwk6IQQIhBIZDjzzDNtTbkLL7ww/bo75cEXdQ0aNDB77bWXefDBB80BBxyQ0fsWQmQeuVyFECIQKEXCGa0kNvh7bec6dVa3ihUrmokTJ9pjvZ566qmM3a8QIhxUWFgIIQJhypQpZunSpaZmzZr2++T5q3w9bdo0M2/ePJvZunDhQntShBBCyEInhBCBgAuVTNYPPvggz6QGYuw43mv16tWmfPnyKhoshLBI0AkhRCCQ7ED5Edyoc+bMSb/u3K9LliwxP/zwg9lvv/1saRKHEiCEEBJ0QggRCC5zlfpz3bp1M1988UXaUjd37lzTtm1b62697LLLMn2rQojAUJarEEIEBO7TAQMGmMsvv9wmP+y77772aK/Fixfbz5988om1zqk0iRDCR4JOCCEChBMfqEU3Y8YMe8xXvXr1bH06RJwrXyKEEA4JOiGEiAhZ5oQQuSFBJ4QQgZIsWyKEEHmhpAghhAgUiTkhxMYiQSeEEEIIETkSdEIIIYQQkSNBJ4QQQggRORJ0QgghhBCRI0EnhBBCCBE5EnRCCCGEEJEjQSeEEEIIETkSdEIIIYQQkSNBJ4QQW8i8efPMVVddZfbaay9TsmRJU7FiRXPEEUeYxx9/3Pzzzz+Zvj0hRAFApzsLIcQWMHPmTCveypUrZ+666y6z3377mRIlSphvvvnGPPXUU2a33XYzJ5544jb53atWrTLFixffJj9bCBEXstAJIcQWcPnll5uiRYuayZMnmzPOOMPUqVPH1KhRw5x00klm6NCh5oQTTrDXLVq0yFx44YWmQoUKpkyZMqZp06bmq6++Sv+c7t27mwMPPNC88MILplq1aqZs2bKmbdu2ZunSpelrjj76aNO5c2dz9dVXm5133tm0bNnSvv7tt9+aY4891my//fbWOnjuueeaP/74IwN/DSFEppCgE0KIzeTPP/80H3zwgenUqZMpXbr0Bs9jPf30082CBQvMsGHDzJQpU8xBBx1kmjVrZv7666/0tT/99JMZMmSIeffdd+3H2LFjzd13353j5z333HPWKvfJJ5+YJ554wgpFxGG9evWsqBw+fLiZP3++FZdCiIKDXK5CCLGZ/PjjjyaVSplatWrleB3r2b///mu/RuxhpZs4caIVdLhj4b777rPi7bXXXjMXX3yxfW3dunXm2WefNTvssIP9HkvbqFGjzJ133pn+2Xvvvbfp06dP+vtevXpZMYe719G/f39TpUoV8/3335uaNWtu47+CECIEJOiEEGIrg3hDnLVr186sXLnSulaXLVtmdtpppxzXrVixwlrlHLhanZiDypUrWxHoU79+/Rzf87M//PBD625Nws+WoBOiYCBBJ4QQmwlZrbhUZ8yYkeN1YuigVKlS9jNiDnE2ZsyY9X4GyRSOYsWK5XiPn40w9Em6dvnZWADvueee9X42v1MIUTCQoBNCiM0Ei9sxxxxjHn30UXPFFVfkGUdHvBylTUiewAq3NeFnv/766/bn8vOFEAUTJUUIIcQW8Nhjj5k1a9aYBg0amEGDBplp06ZZi92LL75opk+fbooUKWKaN29uGjZsaE4++WSbRDF79mzz6aefmptvvtkmMmwJxOiRWHHWWWeZSZMmWTfr+++/b84//3yzdu3ardZOIUTYaDsnhBBbwJ577mm++OILm5TQrVs38+uvv9rEh3322cd06dLFljXBdfree+9ZAYfQWrhwoalUqZJp3LixLTOyJey666424/WGG24wLVq0sDF7VatWNa1atTKFC2vPLkRBoVCKFC0hhBBCCBEt2r4JIYQQQkSOBJ0QQgghRORI0AkhhBBCRI4EnRBCCCFE5EjQCSGEEEJEjgSdEEIIIUTkSNAJIYQQQkSOBJ0QQgghRORI0AkhhBBCRI4EnRBCCCFE5EjQCSGEEEJEjgSdEEIIIYSJm/8PbxKh/UL6208AAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "genre_count.columns = ['genre', 'count']\n",
    "genre_count = genre_count.sort_values(by='count', ascending=False)\n",
    "\n",
    "sns.barplot(x='genre', y='count', data=genre_count, hue='genre', \n",
    "            palette='autumn', dodge=False)\n",
    "plt.title(\"Top 10 Genres on Netflix\")\n",
    "plt.xlabel(\"Genre\")\n",
    "plt.ylabel(\"Count\")\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.legend([],[], frameon=False)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "01c66be4",
   "metadata": {},
   "source": [
    "International Movies and Dramas dominate the Netflix catalog"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "66fcc712",
   "metadata": {},
   "source": [
    "### Which top 10 countries contribute the most content?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "e8d45c1d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['country'] = df['country'].str.split(', ')\n",
    "df = df.explode('country')\n",
    "df.reset_index(drop=True, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "45ef6071",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "          country  count\n",
      "0   United States   4675\n",
      "1           India   2555\n",
      "2  United Kingdom   1007\n",
      "3          France    707\n",
      "4          Canada    597\n",
      "5           Spain    406\n",
      "6         Germany    375\n",
      "7           Japan    304\n",
      "8           China    254\n",
      "9         Nigeria    251\n"
     ]
    }
   ],
   "source": [
    "country_count = df['country'].value_counts().reset_index().head(10)\n",
    "print(country_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "d87f380d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAnYAAAHWCAYAAAD6oMSKAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAUHdJREFUeJzt3QWcVOX7//9ryaVbQrobREJAQRAECSlBERFQkA4BUUQkFFAEVFoMQEVBJOSDSHd3SEmDSkgt3ef3uO7v/8x/ZjtmdnbPvp6Px7DMzJkz9zkzu/ve644JsCzLEgAAAMR7ifzdAAAAAHgHwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2AEAADgEwQ4AIuHkyZMSEBAg06ZNc93Wtm1bSZ06day1QZ9/8ODBEtti+zgRP+l7U9+j8C+CHRBLjh07Jh07dpT8+fNLYGCgpE2bVqpWrSpffvml3L5922fPe+DAAfMDV4OJr926dcs81+rVqyUuW7RokV8CUnxvm68NHz5c5s+f77fnP3v2rLz33ntSo0YNSZMmjQkp4b2XN27cKE8//bSkTJlSsmXLJj169JAbN26IE/j7tUAM6GfFAvCthQsXWilSpLDSp09v9ejRw5oyZYo1fvx465VXXrGSJk1qdejQwWfPPXv2bP08aGvVqlWWr/3333/muQYNGmTFZV27djXtjIpHjx5Zt2/fth48eOC6rU2bNlaqVKlirW36/Pfv37dimy+OMzT6HPpc/qLfI3ruCxUqZFWuXDnc75tdu3ZZgYGB1hNPPGFNmjTJGjBggJU8eXKrbt26lhNE57XQ96a+R+FfSWISCgFE7MSJE/LKK69Injx5ZOXKlZI9e3bXfV27dpWjR4/K77//7tc2ImwPHjyQR48eSbJkyUyl1Z/8/fxO9+STT8qlS5ckY8aM8uuvv0rz5s3D3Pb999+XDBkymIqeVt9V3rx5pUOHDrJ06VJ5/vnnJaG4efOmpEqVSpIkSWIu8DM/B0vA8Tp16mT+8t+wYUOk/+odOnSolT9/fitZsmRWnjx5rP79+1t37tzx2E5vr1+/vrVu3TqrQoUKplqQL18+a/r06a5tpk6dap47+MW9CrFo0SLr6aeftlKmTGmlTp3aqlevnvXnn3+GWrH5+++/rUaNGpn/Z86c2erTp4+rgnXixIlQnyui6t2VK1esXr16mePR43388cet1q1bm+qf7fz589Ybb7xhPfbYY+Y4S5cubU2bNs1jP/bzf/bZZ9ZXX33lOn/ly5e3tm7d6nEsobUz+D4+//xzs49EiRKZ6ox9n57T4Ofl2LFj1vPPP2/OYfbs2a0hQ4aYCl/wSlDw6k/wfYbXNhXa+dy5c6epEqVJk8a0pWbNmtamTZs8trHfB+vXr7fefvtt89ppWxs3bmxduHAh3NcnssepX/U1fPHFF0M8Xqs4adOmtd56660wnyO043avGEXlONesWWOeK2PGjGZ7fT9dvnzZ8lalOygoyEqSJIn1zjvveNx+9+5d8z305ptvRrh/PSf6Wmp1UN/T2bJls5o0aWIdPXrUtc2NGzes3r17Wzlz5jTv5cKFC5v3pvt7K7T3ZVjvF/2/3nbkyBFzbtOlS2del7Zt21o3b96M1Gth72P//v1Wy5YtTS9E2bJlPe4L7ocffrDKlStnKpwZMmSwXn75Zev06dMe2/z1119W06ZNraxZs5rzoT8HdLurV69GeC7hiWgN+Nj//vc/M66uSpUqkdq+ffv2Mn36dHnppZekT58+smXLFhkxYoQcPHhQ5s2b57GtVvt0uzfffFPatGkj3333nRnorpWHEiVKSLVq1cy4n7Fjx5oKQ7Fixczj7K8//PCDeVydOnXk008/NWPkJk2aZMYN7dq1y1QgbA8fPjTbVapUSUaNGiXLly+X0aNHS4ECBaRz586SJUsW81j9f5MmTaRp06bmcaVLlw7zWHU80jPPPGOO7Y033pBy5crJxYsXZcGCBfL3339L5syZzfjDZ5991hxrt27dJF++fDJ79mxznFevXpWePXt67POnn36S69evm/GMOkZq5MiRpi3Hjx+XpEmTmtv//fdfWbZsmTn+0EydOlXu3Lkjb731liRPntxUcLRqFxo9L3Xr1pWnnnrKPNfixYtl0KBBptI3dOhQiYrItM3d/v37zfnTilG/fv3M8X311VfmfK1Zs8a8Vu66d+9uqkzaPh1z+cUXX5hzOmvWrAifK6Lj1HP92muvmfsuX75szpn798C1a9fM/WHR49X3fsWKFc15V/reis5x6jGlT5/ejFU8fPiweV+eOnXKVNe8Mbh/37595rjLly/vcbtWdcuWLWu+dyI6lw0aNJAVK1aYar6+h/U9q6/7n3/+aY5b89WLL74oq1atMt/fut8lS5bIO++8I//88498/vnn0W5/ixYtzPeR/lzZuXOnfPPNN/LYY4+ZnwERvRY2rWYWKlTIjMX7vywYumHDhsnAgQPNc+o+//vvPxk3bpz52aTnSV+ne/fumZ8td+/eNe9RHa+ox7hw4ULzPZ4uXbpoH2uCFCzoAfAi/ctev820yhUZu3fvNtu3b9/e4/a+ffua21euXOm6TasjetvatWtdt2n1Rf/a1UpaRJWH69evm7+2g4/vO3funPlL3v12u5KklUR3Or7oySefjPYYuw8//NBsP3fu3BD32VWJL774wmzz448/uu67d++eGQOl1ZFr1655VC4yZcrkUZ357bffzO3/+9//IhzHZu9DqxjBK1lhVez0tu7du3u0WyupWmGxq46RrdiF1zYV/NxqxU2fRytptn///ddUqapVqxaiklWrVi2Pao9W7xInThxhVSSyx3n48GGznY45c6dVvLx583o8d1TGdUX1OPU9qe8R28iRI83t+l7wRsXOvs/9e8/WvHlzU30Lz3fffWceP2bMmBD32edo/vz5ZpuPP/7Y4/6XXnrJCggIcFX2olOx0+q3O60U6vdNZF4Lex9arQvrPtvJkyfN+2vYsGEe2+3bt89UPO3btSKuj9PziphjVizgQ1qlUDrDLrIzIlXv3r09btfKnQo+Fq948eKmkmHTqlmRIkVMdSoiWh3Qv4ZbtmxpqmT2JXHixKYCopWC4Dp16uRxXZ87Ms8Vljlz5kiZMmVMhS84u7Ki50T/gtd22rRiY89A1IqNu5dfftlUpdzbqKLSzmbNmplzGVlaIXJvt17XKoRWNX1Fqz46lqtx48amImzTMZyvvvqqrF+/3vX+s2n1xb1ipedG96PVLG8cZ+HChc17Z8aMGa7ttHr3xx9/SKtWraJVLYvucep7xKZVZB37ZX9/xZQ9i12ruaGNg4xolru+77UardWp8N73+r2o7/PgPws0s+k5ja7Qvo91bGHw8xiVfYRm7ty5ptKt1Tr3nzH6/azVPvtnjF2R04qk9hogZgh2gA/Zg6q1myUy9BdsokSJpGDBgh636w9C7bII/gs4d+7cIfahoebKlSsRPteRI0fM15o1a5oQ437RX6QXLlwI8QsreNiJ7HOFtwRMyZIlw91Gj1l/Ceh5cWd3J0d0TuyQF5V2ajdVZGm73AOHHXCUL5eY0S4t/SWoQT44PTf6C/XMmTNeOzeRPc7XX39dNmzY4HpdtNv8/v370rp1a4mt49T3iztdg0+DoLdejxQpUpiv2nUYnHbh2/eH977X4wlvooGevxw5coT4ozCs931UxNb3iP6M0RCqr0fwnzE6/ML+GaP70j9mtUtYA692y06YMEGCgoKifGwQYYwd4ONgpz+cddxMVES2sqF/0YcmvDEvNnvMmI6n0eAYXPBfOmE9V1wTk3Nii+gXc1SF9XpqNSq+nZuI6Jixt99+21TtdFznjz/+aMaihRbM4it7Zruuexec3qbf87ElOu+t2Poe0Z8x2j6tLob2nO6LXut4XR03+9tvv5k/LLVSqWMAN2/eLDlz5ox0u0DFDvA5HSStf6Fv2rQpwm11SRT9YWhX02znz5833aZ6v7d+8NuDoXXQdK1atUJcdGC6t54rLNqGiEKvHrOej+CTFw4dOuS639ftDI+2K3g3719//WW+2pNP7IqIvobuQqu6RLZtWvXQhXF1ckBwem60wpYrVy6JzeNUOmmifv36Jtjp8Wn1LrLVutCOPTrHGfz7R7vsNXC5tzMmtMqsf/hs377d43btlt69e7eZ6BDR+16PRyuZYdH3tU6kCV7tD/6+j8p7K7a/R+xJIFqRC+1njE7EcVeqVCn54IMPZO3atbJu3TozgWLy5MkxbkdCQ7ADfExn8ekaTzojTANacBr69NMnVL169cxXna3obsyYMear/sKMKn3u0H7wa3eHVhR1Vltov2C0Cyyq9BdwaM8V3li2PXv2hJjt61490HNy7tw5j5mbOiNRZ9bpX/zVq1f32jmJrvHjx3u0W6/rGK/nnnvO9UtYKxb6C8vdxIkTo9023Z+ulaYVDvcuRn2P6cxgndlsDwXwloiO06ZBTj/xRGdwaju1ihcZeuzBjzs6xzllyhSP97TOitX3zAsvvCDeoGPCNJhoNdI9eGn1W0NkeOvf2e97HWvmfj5De99r1S34NjobVkOXfSx67Np9GZn3VlSE9lpElc5G19dvyJAhIaqBel3H9Skd26evT/CQp6E9tO5uhI+uWMDH9K9W/QWkg/p1fIyOQdK/+PWve/1IInvpDqUTCXT5Ef3FpD9UNbRs3brVLH+ig8f1o46iSqsH+sNVlzLQMSs64FvH1WmlTn/h6S9hXWZEf/lqdeT06dNmkoZ+3Flov3gi6p7RCR0awnT8lVZv9FjDGkenv/jthWB1uRNdpkUH2+tyJ/qXup4PHQivS1voOdqxY4epuuhjtBKkATiyE1Pc6fMo7e7RgBuV8BGcjj3UpT/0ddOJA9rtpOdPuyHtMYkaBPQYNYzqL2V9T+hSDsHHMUa1bR9//LGZBKPhpkuXLqaKpOdKfxnqsiPeFJnjtOkfIJkyZTLvbQ0g+l6LDD12nYihf8hod6ZWevS5onqc+r2lYVMH7WtlTEOOPlaXD4mIPpe9xIod1nSChtJqkvsyHrqEkX6P6ntUl+fR7kQNobosTHj0Z8D3339vxpXp97dOXtBFfvXY9fgaNWokDRs2NN/vAwYMMIFWvxe0i1IDbq9evTyWH9E/Gj/55BPzVbu9NeTZ1dToCuu1iApto57P/v37m2PQn2H6/aqLtusfc3re+vbtaxZu14k4+j2iPzc05Ol51/e+hmBEkRdm1gKIBF2AU5cQ0WUfdOkGXaqhatWq1rhx4zwWH9YFinXhV11sWD9uLFeuXOEuUBxc9erVzcXd119/bRbb1aUHgi/hoP+vU6eOWeJEFxAtUKCAWbB0+/btEX6kVGgLkm7cuNEsN6HHGJmlTy5dumR169bNLEiqj9HFWPX5Ll686LFAcbt27czCurpNqVKlQizv4L64cHDB26GLKuvSHVmyZDFLR4S2QHFwkV2gWBdY1ed6+PChx+N1SZBmzZqZbXSR1o4dO5qFoIPvM6y2hXYc9sK9+vrp0i+67xo1apjXwJ29DMi2bds8bg9rGZbgonKcti5duph9//TTT1ZkHTp0yCxfoh+/F9oCxZE9TnuBYj3Pun2rVq3M+ywyQlucN/hC0TZdHLxKlSrm+0ZfL12qxl5+JyK3bt0yH0Nmf5/rEim6lIn7ki66JJEuSZMjRw6zjS5mHHyBYntfuiiyfg/rz5UWLVqY5XrCWu7EffFv9/Om7/GIXouw9uF+X3Bz5swxi6Dre0gvRYsWNedKl8dRx48fN0uw6M8ePZe6sLS+vsuXL4/UuYSnAP0nqmEQAIDw6ASKb7/91nSj2130vjZt2jRp166dbNu2LcTiwUBCwRg7AIBX6ZIfOv5Mu9FiK9QB+D+MsQMAeIWOGdRxWToGUgfGB/+4NwC+R7ADAHiFzoTVT5jQyRL6+cQRLfsBwPsYYwcAAOAQjLEDAABwCIIdAACAQzDGDj6hHz+kH4eji1F68+ObAABIaCzLMp9yootF6ydyhIdgB5/QUOfNz6kEACChO3PmjOTMmTPcbQh28An7Y570Tejtz6sEACAhuXbtmimWROYjFAl28Am7+1VDHcEOAICYi8zQJiZPAAAAOAQVO/jU5Z1L5EFqPlIIAJAwZCxf36/PT8UOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIQh2bvLmzStffPGFzz7fbf78+T7ZNwAAgCOC3bPPPiu9evUKcfu0adMkffr0UdrXtm3b5K233vJLGPvvv/+kc+fOkjt3bkmePLlky5ZN6tSpIxs2bIhxe3wZWAEAQNzBZ8W6yZIli9+eu1mzZnLv3j2ZPn265M+fX86fPy8rVqyQS5cu+a1NAAAgfon3FbvIatu2rTRu3FhGjRol2bNnl0yZMknXrl3l/v37oVa29P+qSZMmplJmX1e//fablCtXTgIDA00IGzJkiDx48MB1/5EjR6RatWrm/uLFi8uyZcvCbdvVq1dl3bp18umnn0qNGjUkT548UrFiRenfv7+8+OKL4bbn2LFj0qhRI8maNaukTp1aKlSoIMuXL/eoaJ46dUrefvtt8zi92NavXy/PPPOMpEiRQnLlyiU9evSQmzdvuu6fOHGiFCpUyByH7v+ll16KwSsAAAB8LcEEO7Vq1SoThPSrVsa0u1YvYXXLqqlTp8rZs2dd1zWAvf7669KzZ085cOCAfPXVV2Yfw4YNM/c/evRImjZtKsmSJZMtW7bI5MmT5d133w23XRrI9KLdrHfv3o1Se27cuCH16tUz1b1du3ZJ3bp1pWHDhnL69Glz/9y5cyVnzpwydOhQ8zi9KD0Puq1WCvfu3SuzZs0yQa9bt27m/u3bt5ugp487fPiwLF682IRVAAAQdyWoYJchQwYZP368FC1aVBo0aCD169c3gSi8blkdp6fj3ezrWp177733pE2bNqZaV7t2bfnoo49MwFNaLTt06JB8//33UqZMGROGhg8fHm67kiRJYsKhhk19vqpVq8r7779vAldE7dHn6Nixo5QsWdJU17QtBQoUkAULFpj7M2bMKIkTJ5Y0adKYx+lFjRgxQlq1amXGJ+rjqlSpImPHjjXtvnPnjgmGqVKlMudJK4hPPPGECXph0UB67do1jwsAAIhdCSrYlShRwoQcm3bJXrhwIUr72LNnj6li2VU2vXTo0MFUwm7duiUHDx403Zo5cuRwPaZy5coR7lcrZ//++68JZFpJW716tenuDauiaNOKXd++faVYsWIm9Gl7tA12xS6849B9ux+HTtbQiuOJEydMYNVAp+G1devWMmPGDHN8YdGgmC5dOtdFzwEAAIhd8T7YpU2bVoKCgkIdt6YBw13SpEk9rut4Mw0yUaFBSqt2u3fvdl327dtnxtXpWLSY0MdroBo4cKBs3LjRjAscNGhQuI/RUDdv3jxTFdRuYm1PqVKlzESMiI5DK33ux6FhT49DK35a4du5c6f8/PPPJgB/+OGHpjqo5zU0Oh5QXwf7cubMmRidCwAAkABnxRYpUkSWLl0a4nYNJYULF47RvjUIPnz40OM2raLpmLOCBQuG+hitnGmo0QqeBiK1efPmaD2/TrxwX94ktPbocigaAHVShR3YTp486bGNjvcL7Th0jGBYx2F3EdeqVctcNGBqRXDlypVmDGFwukSLXgAAgP/E+4qdrv32119/mfFfOiZNQ9eYMWNMpalPnz4x2rfOPNUxeOfOnZMrV66Y27RypePQtGq3f/9+0+05c+ZM+eCDD8z9GoI0UOoYPK2AaRVtwIAB4T6PLmlSs2ZN+fHHH80xaFfo7NmzZeTIkWbGa3jt0fFxOkHCrri9+uqrIaqQ+ri1a9fKP//8IxcvXjS36YQOrQrqZAl9rFbqdLavPXli4cKFZsyd3qezavWYdb8apAEAQNwU74OdjgHT0KITFjRUVapUSX755RcTjHSsWkyMHj3aLFWi48V08oDScWgaerRKqEuLPPXUU/L555+b8WgqUaJEpmv09u3bZsmS9u3bu2bMhkXHt2m7dT862UInQmh3rI7d08ke4bVHQ6xOCtHJDzobVtun1Th3OiZQq3jaxWpPuihdurSsWbPGhGJd8kT3p6HVHhuo1TkNjBo4tQqps3s1LOs4RQAAEDcFWJZl+bsRcB6dFatjHE+s+kXSpk7p7+YAABArMpav77PfqTqGXecWOLpiBwAAgP9DsAMAAHAIgh0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAhyDYAQAAOATBDgAAwCEIdgAAAA6RxN8NgLNlLFcnwlWyAQCAd1CxAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIVjHDj51ft5YuZUy0N/NABBD2Zr39XcTAEQCFTsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBLsEKCAgQObPn2/+f/LkSXN99+7d/m4WAACIIT55Ip5p27atXL161RXMYipXrlxy9uxZyZw5s1f2BwAA/Idgl8AlTpxYsmXL5u9mAAAAL6ArNh579tlnpUePHtKvXz/JmDGjCWiDBw/22ObIkSNSrVo1CQwMlOLFi8uyZcs87g/eFfvw4UN58803JV++fJIiRQopUqSIfPnll7F6XAAAIHqo2MVz06dPl969e8uWLVtk06ZNpqu2atWqUrt2bXn06JE0bdpUsmbNau4PCgqSXr16hbs/fUzOnDll9uzZkilTJtm4caO89dZbkj17dmnRokWsHRcAAIg6gl08V7p0aRk0aJD5f6FChWT8+PGyYsUKE+yWL18uhw4dkiVLlkiOHDnMNsOHD5cXXnghzP0lTZpUhgwZ4rqulTsNjL/88ku4we7u3bvmYrt27ZqXjhAAAEQWXbEOCHbutLJ24cIF8/+DBw+ayRF2qFOVK1eOcJ8TJkyQJ598UrJkySKpU6eWKVOmyOnTp8N9zIgRIyRdunSuiz4vAACIXQS7eE4rbO50vJx2p0bXzJkzpW/fvmac3dKlS83Yu3bt2sm9e/fCfVz//v1NV699OXPmTLTbAAAAooeuWAcrVqyYCVi6nIlW8tTmzZvDfcyGDRukSpUq0qVLF9dtx44di/C5kidPbi4AAMB/qNg5WK1ataRw4cLSpk0b2bNnj6xbt04GDBgQ7mN0nN727dvNuLy//vpLBg4cKNu2bYu1NgMAgOgj2DlYokSJZN68eXL79m2pWLGitG/fXoYNGxbuYzp27Ghm0r788stSqVIluXTpkkf1DgAAxF0BlmVZ/m4EnEdnxeokir+mfSRpUgb6uzkAYihb877+bgIgCf13alBQkKRNmzbcbanYAQAAOATBDgAAwCEIdgAAAA5BsAMAAHAIgh0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAhyDYAQAAOEQSfzcAzpa1SY8IV8kGAADeQcUOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBDsAAACHYB07+NTpMX0kTWAyfzcjQcrz3gR/NwEAEMuo2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2AEAADiEY4Jd3rx55YsvvvDJvgMCAmT+/Pkx2sezzz4rvXr1El9bvXq1ae/Vq1d9/lwAACBu8WuwCyvsTJs2TdKnTx+lfW3btk3eeustr4axyGrbtq00btzY47Zff/1VAgMDZfTo0eb63Llz5aOPPoqV9gAAgITJMZ8VmyVLFokrvvnmG+natatMnjxZ2rVrZ27LmDGjv5sFAAAcLl50xdoVsVGjRkn27NklU6ZMJjjdv38/1K5Y/b9q0qSJqdzZ19Vvv/0m5cqVM9W0/Pnzy5AhQ+TBgweu+48cOSLVqlUz9xcvXlyWLVsWpbaOHDlSunfvLjNnznSFutCqk9qm4cOHyxtvvCFp0qSR3Llzy5QpUzz2tXHjRilbtqxpS/ny5U0FUo9n9+7drm0WLVokhQsXlhQpUkiNGjXk5MmTIdo0Z84cKVGihCRPntw8r11FdG/Lxx9/LK+//rqkTp1a8uTJIwsWLJD//vtPGjVqZG4rXbq0bN++PUrnAgAAxK54EezUqlWr5NixY+br9OnTTXetXsLqllVTp06Vs2fPuq6vW7fOhJeePXvKgQMH5KuvvjL7GDZsmLn/0aNH0rRpU0mWLJls2bLFVNzefffdSLdRt9Xu1oULF5pQGRENWBrYdu3aJV26dJHOnTvL4cOHzX3Xrl2Thg0bSqlSpWTnzp1mv8HbcubMGdNe3U7DXvv27eW9997z2GbHjh3SokULeeWVV2Tfvn0yePBgGThwYIhz9/nnn0vVqlVNW+rXry+tW7c25+q1114zz1+gQAFz3bKsUI/l7t27ps3uFwAAELviTbDLkCGDjB8/XooWLSoNGjQw4WPFihXhdsvqOL1s2bK5rmt1ToNPmzZtTLWudu3aJjBpwFPLly+XQ4cOyffffy9lypQxlTutqkXGH3/8Yap1WhF87rnnIvWYevXqmUBXsGBBE9oyZ85sgqv66aefTHXu66+/NpXDF154Qd555x2Px0+aNMkELg2IRYoUkVatWpnqprsxY8aY9miY08qe3t+tWzf57LPPQrSlY8eOUqhQIfnwww9NMKtQoYI0b97cPE7bd/DgQTl//nyoxzJixAhJly6d65IrV65InQMAAJAAg512JSZOnNh1XbtkL1y4EKV97NmzR4YOHWq6Fu1Lhw4dTFXv1q1bJrhoIMmRI4frMZUrV47UvrWrUrs0Bw0aJDdu3Ij0Y2wa4jSE2seklTu9X7thbRUrVvR4vLa3UqVKHrcFb69uo5U4d3pdu5wfPnwYaluyZs1qvmq1MPhtYZ3z/v37S1BQkOui1UQAAJCAJk+kTZvWhIDgdKkOrfq4S5o0qcd1DULadRoVGri0aqfdl8G5B6joePzxx81MWB3nVrduXVPB07Fz4fHGMXmLe1u0HWHdFlb7dPyeXgAAQAKt2Gn3oY7fCk5v0+6/mNBQ4l6RUjppQith2vUZ/JIoUSIpVqyYqTRpBc+2efPmSD+nTjpYs2aNnDt3zoS769evx+jc6Jg4Hbtms8cK2rS9W7du9bgteHt1mw0bNnjcptf1/LpXQAEAQPzn12CnkwX++usv6dGjh+zdu9eELh0T9vPPP0ufPn1itG/tFtUxeBqyrly5Ym7TsWM6fk6rdvv37zfdlDp79YMPPjD316pVywQeHYOn3bY62WLAgAFRel7tytVFgrXLsk6dOtGeRPDqq6+a6piuzaftXLJkiZkV7F4969Spk+lS1bF3eu50XF7wSRF6HvU86FhCPdc68UTHKvbt2zda7QIAAHGXX4OdTmBYu3atmbCgoUrHi/3yyy8ye/ZsU/GKCZ1QoEuVaNB64oknzG0atHTG6tKlS83EgKeeesrMBtVKm9Kq3bx58+T27dtmPJvOMrVnzEZFzpw5Tbi7ePFitMOddlP/73//M7NddckTDZgaTN27jXWJFF3KRJdB0ckeOos3+GQPrVLqOdUAW7JkSbMPHWcYfJIFAACI/wKssNavQJwzY8YMszaejkvUdeviMg2zOk5y36D2kiYwmb+bkyDleW+Cv5sAAPDi71T9/a+FnwTxyRNOpN3GWtXUiRnaNaxLjuiadHE91AEAAP8g2MVhOj5Qu071qy7vomvKRadrGAAAJAwEuzisX79+5gIAAOCoBYoBAAAQPoIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2AEAADgEy53Ap3L3Hh3hKtkAAMA7qNgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByC5U7gU391eV1SJ0sqCV3R72b7uwkAgASAih0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAhyDYAQAAOATBDgAAwCEIdgAAAA5BsAMAAHAIgh0AAIBDEOwAAAAcgmDnZ23btpWAgIAQl6NHj/q7aQAAIJ7hs2LjgLp168rUqVM9bsuSJYvH9Xv37kmyZMliuWUAACA+oWIXByRPnlyyZcvmcXnuueekW7du0qtXL8mcObPUqVPHbDtmzBgpVaqUpEqVSnLlyiVdunSRGzduuPY1bdo0SZ8+vSxZskSKFSsmqVOnNsHx7NmzHs/53XffSYkSJcxzZ8+e3TyX7erVq9K+fXsTLtOmTSs1a9aUPXv2xOIZAQAA0UGwi8OmT59uqnQbNmyQyZMnm9sSJUokY8eOlf3795v7V65cKf369fN43K1bt2TUqFHyww8/yNq1a+X06dPSt29f1/2TJk2Srl27yltvvSX79u2TBQsWSMGCBV33N2/eXC5cuCB//PGH7NixQ8qVK2eC5uXLl2Px6AEAQFQFWJZlRflR8OoYux9//FECAwNdt73wwgvy33//ybVr12Tnzp3hPv7XX3+VTp06ycWLF10Vu3bt2pkxegUKFDC3TZw4UYYOHSrnzp0z1x9//HGzzccffxxif+vXr5f69eubYKfVPJsGPw2QGgZDc/fuXXOxadu1oritVSNJnSypJHRFv5vt7yYAAOIp/Z2aLl06CQoKMj1p4WGMXRxQo0YNU0WzaTdry5Yt5cknnwyx7fLly2XEiBFy6NAh80I/ePBA7ty5Y6p0KVOmNNvoVzvUKe1q1aCm9Ou///5rKnCh0S5X7drNlCmTx+23b9+WY8eOhXkM2qYhQ4ZE4+gBAIC3EOziAA1y7l2h7re7O3nypDRo0EA6d+4sw4YNk4wZM5oK25tvvmkmV9jBLmlSzwqZzrK1C7MpUqQIty0a6jQIrl69OsR9OnYvLP3795fevXuHqNgBAIDYQ7CLR3S826NHj2T06NFmrJ365ZdforSPNGnSSN68eWXFihWmUhicjqfTLtskSZKY7SJLu23du24BAEDsY/JEPKJVvfv378u4cePk+PHjZnKEPakiKgYPHmzCoU7COHLkiBnHp/tUtWrVksqVK0vjxo1l6dKlpkq4ceNGGTBggGzfvt0HRwUAALyFYBePlClTxix38umnn0rJkiVlxowZZmxbVLVp00a++OILM6lClzzR7l0NeHa37aJFi6RatWpmgkXhwoXllVdekVOnTknWrFl9cFQAAMBbmBULn87gYVbs/2FWLAAgNmbFUrEDAABwCIIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwiCT+bgCcrfDE7yNcJRsAAHgHFTsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCdezgU5teaCupkiQVp3p6zSx/NwEAABcqdgAAAA5BsAMAAHAIgh0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAhyDYAQAAOATBDgAAICEHuzZt2sjatWu93xoAAADEbrALCgqSWrVqSaFChWT48OHyzz//RL8F8LuAgACZP3++v5sBAAD8Eew0BGiY69y5s8yaNUvy5s0rL7zwgvz6669y//79mLbJkc6dOyfdu3eX/PnzS/LkySVXrlzSsGFDWbFihb+bBgAAEvoYuyxZskjv3r1lz549smXLFilYsKC0bt1acuTIIW+//bYcOXLEuy2Nx06ePClPPvmkrFy5Uj777DPZt2+fLF68WGrUqCFdu3b1d/MAAIBDxHjyxNmzZ2XZsmXmkjhxYqlXr54JLsWLF5fPP//cO62M57p06WK6O7du3SrNmjWTwoULS4kSJUww3rx5s9lmzJgxUqpUKUmVKpWp5uljbty44drHtGnTJH369LJkyRIpVqyYpE6dWurWrWvOv23btm1Su3ZtyZw5s6RLl06qV68uO3fu9GiLBu5q1apJYGCgeY30dQvu3XffNW1MmTKlqTAOHDiQSiwAAE4NdvpLfs6cOdKgQQPJkyePzJ49W3r16iX//vuvTJ8+XZYvXy6//PKLDB06VBK6y5cvm+qcVuY0tAWnYU0lSpRIxo4dK/v37zfnUKt7/fr189j21q1bMmrUKPnhhx/M5JXTp09L3759Xfdfv37dTGxZv369CYw6BlKDtt6uHj16JE2bNpVkyZKZKuvkyZNNiAsuTZo0JkgeOHBAvvzyS/n6668jDOl3796Va9eueVwAAEDsShKdB2XPnt2EhJYtW5oqVNmyZUNso92MdmhJyI4ePSqWZUnRokXD3U6DsU3HLH788cfSqVMnmThxokeg1jBWoEABc71bt24e4blmzZoe+5wyZYp5DdasWWNCuAbuQ4cOmaqfdpkrnfyi4yPdffDBBx5t0fA4c+bMEEHT3YgRI2TIkCGROCMAACBOBTut3jRv3tx054VFA8WJEyckodNQFxkaujQcafDSateDBw/kzp07pkqnXaJKv9qhzg7YFy5ccF0/f/68CWWrV682tz98+NA8Xit76uDBg6ab1w51qnLlyiHaohNitHp47Ngx0x2sbUmbNm247e/fv7/pWrbpMehzAQCAONwVq1Wjdu3amUoUIqbdoTq+TgNbeJMrtKJWunRp08W9Y8cOmTBhgrnv3r17ru2SJk3q8Tjdr3tw1G7Y3bt3m+7TjRs3mv9nypTJYx8R2bRpk7Rq1cp04S5cuFB27dolAwYMiHAfOtNXw5/7BQAAxPGKnYaL3Llzm2oQIpYxY0apU6eOCWo9evQIMc7u6tWrJshp1/bo0aPNWDulYxSjasOGDabrVkOZOnPmjFy8eNF1v0660Nt0woVW+5Q9ecOmgVDHTWqYs506dSrKbQEAAPFk8oT+0n///ffNxABETEOdBuGKFSuaipzOTNVuUe3u1K5QXSpGK6Hjxo2T48ePm8kROpYuOtVBfazuWydHaOUtRYoUrvt1UWmd7aqVPV2mZt26dR4Bzt6Hdt3qmDrtitU2zps3zyvnAQAAxMFgN378eDMrU8dqFSlSRMqVK+dxgSddMkSXHdEJJX369JGSJUuaZUl0ceJJkyZJmTJlzHInn376qblvxowZZrxdVH377bdy5coV8xromoJaIXzsscdc92s1UEPa7du3Tchs3769DBs2zGMfL774olmHUCdm6KQYreDpcicAACDuC7AiO7rfzeDBg834rrAMGjQopu1CPKeTJ3QtvcVVmkiqJJ5jA53k6TWz/N0EAEAC+Z0aFBQU4Rj2aM2K1WAHAAAAB3TFatfipUuXQtyuEwH0PgAAAMSTYKfLc4Q2K1Y/feDvv//2RrsAAAAQRVHqil2wYIHr//rpBdrfa9Ogp5MB8uXLF9U2AAAAILaDXePGjc1XnTihS2YEX99OP35K12IDAABAHA92uoiu0qrctm3bJHPmzL5qFwAAAKIoWrNi+QxYAAAAhwQ7pePp9KIfNm9X8mzfffedN9oGAAAAXwe7IUOGyNChQ6V8+fLmM0fDW6wYAAAAcfiTJzTMjRw50nxsFRDTVbIBAIB3fqdGax27e/fuSZUqVaLzUAAAAPhItIKdfnj8Tz/95P3WAAAAIHbH2N25c0emTJkiy5cvl9KlS5s17NyNGTMm+i0CAABA7AW7vXv3StmyZc3///zzT4/7mEgBAAAQj4LdqlWrvN8SAAAAxP4YOwAAADikYlejRo1wu1xXrlwZkzbBQWZV7CApE3uOwfS3Vvt/9HcTAACIO8HOHl9nu3//vuzevduMt2vTpo232gYAAABfB7vPP/881NsHDx4sN27ciM4uAQAAEJfG2L322mt8TiwAAIATgt2mTZskMDDQm7sEAACAL7timzZt6nFdP2727Nmzsn37dhk4cGB0dgkAAAB/BDv9IFp3iRIlkiJFisjQoUPl+eefj2mbAAAAEFvBburUqdF5GAAAAOJasLPt2LFDDh48aP5fokQJeeKJJ7zVLgAAAMRGsLtw4YK88sorsnr1akmfPr257erVq2bh4pkzZ0qWLFmis1sAAADE9qzY7t27y/Xr12X//v1y+fJlc9HFia9duyY9evSISXvgB7r+YPBFpwEAQAIJdosXL5aJEydKsWLFXLcVL15cJkyYIH/88Yc325fg/ffff9K5c2fJnTu3JE+eXLJlyyZ16tSRDRs2eO05+vbtKytWrPDa/gAAQDzqin306JEkTRry8z/1Nr0P3tOsWTO5d++eTJ8+XfLnzy/nz583IezSpUtee47UqVObCwAASIAVu5o1a0rPnj3l33//dd32zz//yNtvvy3PPfecN9uXoOm4xXXr1smnn35qxi/myZNHKlasKP3795cXX3zRbBMQECCTJk2SF154QVKkSGHC36+//uqxn3fffVcKFy4sKVOmNPfrWoP6+b5hdcW2bdtWGjduLKNGjZLs2bNLpkyZpGvXrh6PAQAADgl248ePN+Pp8ubNKwUKFDCXfPnymdvGjRvn/VYmUHYlbf78+XL37t0wt9OgppW9PXv2SKtWrczEFnu2skqTJo1MmzZNDhw4IF9++aV8/fXXYX7er23VqlVy7Ngx81Wrhfp4vQAAgLgrwNKPjYgGfdjy5cvl0KFD5rqOt6tVq5a325fgzZkzRzp06CC3b9+WcuXKSfXq1U1wK126tKti16lTJ1O1sz311FNmWx0HGRqtxOnsZf2kELtip+Fx9+7droqdznjWYJc4cWJzW4sWLcxC1Pq40GjwdA+fGvJz5colU4q0kJSJQ3bb+1Or/T/6uwkAAESa/k7VD4cICgqStGnTeq9it3LlSjNJQp9AA0Xt2rXNDFm9VKhQwaxlp12H8B6txGmX94IFC6Ru3bomcGloc6+eVa5c2eMxet29Yjdr1iypWrWqmXihFcAPPvhATp8+He7z6mtphzqlXbK6zE1YRowYYd509kVDHQAAiF1RCnZffPGFqR6Flhb1l3nHjh1lzJgx3mwfRCQwMNCEaO1y3bhxo6moDRo0KFKP3bRpk+merVevnixcuFB27dolAwYMMBMywhN8cowG+fAmxui4P/1Lwr6cOXMmkkcHAAD8Eux0DJdWjcKinxOrn0YB39Kq6c2bN13XN2/e7HG/XreXotEgqJMuNMyVL19eChUqJKdOnfJ6m3QpFg387hcAABCHlzvRpTZCW+bEtbMkScy6a/AOXdKkefPm8sYbb5gxdToJQsfFjRw5Uho1auTabvbs2Sa0Pf300zJjxgzZunWrfPvtt+Y+DXLa7apj47S7/Pfff5d58+b58agAAECcCHaPP/64+YSJggULhnr/3r17zVgseIeOh6tUqZKZwaoTGXS5ER27pt3h77//vmu7IUOGmODWpUsXc/5//vlnU9VTuiyKLkPTrVs3M7mhfv36pktXJ0wAAIAEPCtWJ0no4P1t27aZcV/udNamrrGm662NHTvWF21FKHTsm1bgdN25uDiDh1mxAADE3qzYKFXsdDbl3LlzzWK3WgEqUqSIuV2XPNGPE3v48KEZywUAAIDYF6VglzVrVjMYXz+7VGdB2sU+rRrp55dquNNtAAAAEA8+K1ZnWC5atEiuXLkiR48eNeFOB+hnyJDBNy1EuKK5vjQAAHCgKAc7mwY5nWUJAACAePxZsQAAAIh7CHYAAAAOQbADAABwCIIdAACAQxDsAAAAEvqsWCAyXt76dYSrZAMAAO+gYgcAAOAQBDsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEOwjh18amSl9hKYOKnEBR/8OcPfTQAAwKeo2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2AEAADgEwQ4AAMAhCHYxdO7cOenZs6cULFhQAgMDJWvWrFK1alWZNGmS3Lp1y9/NAwAACQifFRsDx48fNyEuffr0Mnz4cClVqpQkT55c9u3bJ1OmTJHHH39cXnzxxSjv9969e5IsWTKftBkAADgXFbsY6NKliyRJkkS2b98uLVq0kGLFikn+/PmlUaNG8vvvv0vDhg3NdlevXpX27dtLlixZJG3atFKzZk3Zs2ePaz+DBw+WsmXLyjfffCP58uUzlT8VEBAgX331lTRo0EBSpkxp9r9p0yY5evSoPPvss5IqVSqpUqWKHDt2zLUv/b8+v1YOU6dOLRUqVJDly5d7tDtv3rwmiL7xxhuSJk0ayZ07twmiNm1ft27dPB7z33//mbC5YsUKn51PAAAQMwS7aLp06ZIsXbpUunbtagJWaDSYqebNm8uFCxfkjz/+kB07dki5cuXkueeek8uXL7u21bA2Z84cmTt3ruzevdt1+0cffSSvv/66ua1o0aLy6quvSseOHaV///4mUFqW5RHCbty4IfXq1TMBbNeuXVK3bl0TME+fPu3RttGjR0v58uXNNhpQO3fuLIcPHzb3aQj96aef5O7du67tf/zxR1OB1NAXGt322rVrHhcAABC7CHbRpEFMQ1WRIkU8bs+cObOplOnl3XfflfXr18vWrVtl9uzZJkgVKlRIRo0aZbpvf/31V4/u1++//16eeOIJKV26tOv2du3amWpg4cKFzf5OnjwprVq1kjp16pgKno7vW716tWv7MmXKmOBXsmRJ81waDAsUKCALFizwaKeGPw10OjZQ96vtXrVqlbmvadOm5utvv/3m2n7atGnStm1bV1gNbsSIEZIuXTrXJVeuXDE+xwAAIGoIdl6mIU6rayVKlDBVLO1y1SpapkyZXIFPLydOnPDoQs2TJ4/pqg3OPeRp96rSsXzut925c8dVIdPn6tu3rwl9Gh71uQ4ePBiiYue+Xw1r2bJlM1VFpV3BrVu3lu+++85c37lzp/z5558m2IVFK4hBQUGuy5kzZ6J1/gAAQPQxeSKatNKlgcjuvrTpGDuVIkUKV9DKnj27R1XNpsHLFlZ3btKkSV3/t6tlod326NEj81VD3bJly0xVUNuo7XjppZdMRTCs/dr7sfdhd8fquL+///5bpk6darpgNXyGRSeN6AUAAPgPwS6atAJXu3ZtGT9+vHTv3j3MYKbj6XRJFJ1koZMWfG3Dhg2mstakSRNXsNTu26jSqqB2HX/99ddmvJ0eJwAAiNvoio2BiRMnyoMHD0wAmjVrluny1AqeTjQ4dOiQJE6cWGrVqiWVK1eWxo0bm8kWGrI2btwoAwYMMJMfvE3H1dkTMLQbWCdbuFfiokKrdp988okZS2gHRQAAEHcR7GJAJyXorFINbzrGTCcuaMgbN26c6RLViQvaxblo0SKpVq2amQihkyBeeeUVOXXqlGvMnDeNGTNGMmTIYJZB0dmwOslCq4bR0bJlS1Np1K/2EiwAACDuCrC0HAOEQquLGl63bdsW5XCokzl0duyAos0lMLHneD5/+eDPGf5uAgAAUWb/TtXJiboebngYY4cQ7t+/b9bp++CDD+Spp56KdsUPAADELrpiEeoEDJ3Jq5W6yZMn+7s5AAAgkqjYIQT9uDJ66AEAiH+o2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHILlTuBT/bZ8E+Eq2QAAwDuo2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHILlTuBTncu3kmSJk8ba8009ODfWngsAgLiGih0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAhyDYAQAAOATBDgAAwCEIdgAAAA5BsAMAAHAIgh0AAIBDEOwAAAAcgmAXh7Vt21YaN27s72YAAIB4gmAHAADgEAS7eGLx4sXy9NNPS/r06SVTpkzSoEEDOXbsmOv+kydPSkBAgMycOVOqVKkigYGBUrJkSVmzZo1rm4cPH8qbb74p+fLlkxQpUkiRIkXkyy+/DLVKOGrUKMmePbt5rq5du8r9+/dj9XgBAEDUEeziiZs3b0rv3r1l+/btsmLFCkmUKJE0adJEHj165LHdO++8I3369JFdu3ZJ5cqVpWHDhnLp0iVzn26bM2dOmT17thw4cEA+/PBDef/99+WXX37x2MeqVatMaNSv06dPl2nTppkLAACI25L4uwGInGbNmnlc/+677yRLliwmoGllztatWzfXtpMmTTKVvm+//Vb69esnSZMmlSFDhri21crdpk2bTLBr0aKF6/YMGTLI+PHjJXHixFK0aFGpX7++CZMdOnQIs3137941F9u1a9e8duwAACByqNjFE0eOHJGWLVtK/vz5JW3atJI3b15z++nTpz220yqdLUmSJFK+fHk5ePCg67YJEybIk08+aUJh6tSpZcqUKSH2UaJECRPqbNole+HChXDbN2LECEmXLp3rkitXrhgfMwAAiBqCXTyhXaqXL1+Wr7/+WrZs2WIu6t69e5Heh46/69u3rxlnt3TpUtm9e7e0a9cuxD60sudOx+4F7/INrn///hIUFOS6nDlzJkrHBwAAYo6u2HhAx8gdPnzYhLpnnnnG3LZ+/fpQt928ebNUq1bN/P/BgweyY8cO0z2rNmzYYCZWdOnSxbW9+wSMmEiePLm5AAAA/yHYxQM65k1np2q3qXaLatfpe++9F+q22tVaqFAhKVasmHz++edy5coVeeONN8x9evv3338vS5YsMePrfvjhB9m2bZv5PwAAiP/oio3DtPtTx8npDFjtRtXqm06UePvtt+Wzzz4L9TGffPKJuZQpU8ZU9RYsWCCZM2c293Xs2FGaNm0qL7/8slSqVMlUAt2rdwAAIH4LsCzL8ncjELq6detKwYIFzQzViOg6dlp502VOypYtK/6ms2J1EsWrhRpIssSeY/Z8aerBubH2XAAAxObvVB3DrhMow0PFLg7S7tOFCxfK6tWrpVatWv5uDgAAiCcYYxcH6Zg4HfumCw03atTI380BAADxBMEuDpo3b16UH6Pr2tGrDgBAwkZXLAAAgEMQ7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIVjuBD41afuMCFfJBgAA3kHFDgAAwCEIdgAAAA5BsAMAAHAIgh0AAIBDEOwAAAAcgmAHAADgEAQ7AAAAh2AdO/hU/dINJEki37zNVh1f6ZP9AgAQX1GxAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCXTwXEBAg8+fPD/P+1atXm22uXr0aq+0CAACxj2AXx507d066d+8u+fPnl+TJk0uuXLmkYcOGsmLFikg9vkqVKnL27FlJly6dz9sKAAD8i8+KjcNOnjwpVatWlfTp08tnn30mpUqVkvv378uSJUuka9eucujQoQj3kSxZMsmWLVustBcAAPgXFbs4rEuXLqYbdevWrdKsWTMpXLiwlChRQnr37i2bN292bXfx4kVp0qSJpEyZUgoVKiQLFiwIsyt22rRpJihqOCxWrJikTp1a6tata6p6tm3btknt2rUlc+bMptJXvXp12blzZywfPQAAiCqCXRx1+fJlWbx4sanMpUqVKsT9Gs5sQ4YMkRYtWsjevXulXr160qpVK/P4sNy6dUtGjRolP/zwg6xdu1ZOnz4tffv2dd1//fp1adOmjaxfv94ESA2Lul+9PSx3796Va9eueVwAAEDsItjFUUePHhXLsqRo0aIRbtu2bVtp2bKlFCxYUIYPHy43btwwVb6waHfu5MmTpXz58lKuXDnp1q2bx5i9mjVrymuvvWaeW6t6U6ZMMWFwzZo1Ye5zxIgRprpnX3QsIAAAiF0EuzhKQ11klS5d2vV/re6lTZtWLly4EOb22mVboEAB1/Xs2bN7bH/+/Hnp0KGDqdRpSNP9aVjUyl5Y+vfvL0FBQa7LmTNnIt1+AADgHUyeiKM0VOnYuMhMkEiaNKnHdX3co0ePorS9e5DUbthLly7Jl19+KXny5DGzcStXriz37t0Lc5+6jV4AAID/ULGLozJmzCh16tSRCRMmyM2bN0Pc78t16TZs2CA9evQw4+p0soYGNp2gAQAA4jaCXRymoe7hw4dSsWJFmTNnjhw5ckQOHjwoY8eONRU0X1YLdWKFPteWLVvMZIwUKVL47PkAAIB3EOziMF2UWJcZqVGjhvTp00dKlixpliHRiQ6TJk3y2fN+++23cuXKFTOxonXr1qZ699hjj/ns+QAAgHcEWFEZpQ9Eki53ohMvns7zjCRJ5JuhnKuOr/TJfgEAiIu/U3Vyok5oDA8VOwAAAIcg2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHIJgBwAA4BC+WTkW+P/8vndhhIspAgAA76BiBwAA4BAEOwAAAIcg2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQ7COHXyqTMHKkihRYp/s+9i5vT7ZLwAA8RUVOwAAAIcg2AEAADgEwQ4AAMAhCHYAAAAOQbADAABwCIIdAACAQxDsAAAAHIJgBwAA4BAEOwAAAIcg2MVB06ZNk/Tp0zvuuQAAgG8R7GJZ27ZtJSAgQD755BOP2+fPn29uVy+//LL89ddfsdKe2HwuAADgWwQ7PwgMDJRPP/1Urly5Eur9KVKkkMcee8zn7bh//36sPRcAAPA9gp0f1KpVS7JlyyYjRoyIdPfoxx9/bAJYmjRppH379vLee+9J2bJlPbb55ptvpFixYiY4Fi1aVCZOnOi67+TJk6YiOGvWLKlevbrZZsaMGSGe69ixY9KoUSPJmjWrpE6dWipUqCDLly/3+jkAAADeR7Dzg8SJE8vw4cNl3Lhx8vfff0e4vQawYcOGmSrfjh07JHfu3DJp0qQQ23z44Ydmu4MHD5r9Dxw4UKZPn+6xnQbCnj17mm3q1KkT4rlu3Lgh9erVkxUrVsiuXbukbt260rBhQzl9+rQXjhwAAPhSEp/uHWFq0qSJqbgNGjRIvv3223C31QD45ptvSrt27cx1DXBLly41Icym+xk9erQ0bdrUXM+XL58cOHBAvvrqK2nTpo1ru169erm2CU2ZMmXMxfbRRx/JvHnzZMGCBdKtW7cwH3f37l1zsV27di3CcwAAALyLip0faQVOK2paPQvP4cOHpWLFih63uV+/efOm6ULV8Kfdp/ZFu2/1dnfly5cP97k0LPbt29d06WoXre5H2xdRxU67ldOlS+e65MqVK9ztAQCA91Gx86Nq1aqZ7tD+/fub2bLRZVfuvv76a6lUqVKIbl93qVKlCndfGuqWLVsmo0aNkoIFC5rJFS+99JLcu3cv3MfpMfTu3dujYke4AwAgdhHs/EyXPdEu2SJFioS5jd63bds2ef3111236XWbTnTIkSOHHD9+XFq1ahWj9mzYsMGETO0qtkOjTryISPLkyc0FAAD4D8HOz0qVKmXC2NixY8Pcpnv37tKhQwfTjVqlShUzs3Xv3r2SP39+1zZDhgyRHj16mG5QnfCg4922b99ullRxr6RFpFChQjJ37lwzYUJn0eoEjEePHsX4OAEAgO8xxi4OGDp0aLjhSYOfdnVqN2m5cuXkxIkTpqqmS5bYdAkUXe5k6tSpJizqkia6lIlOooiKMWPGSIYMGUyA1HCnXcX6nAAAIO4LsCzL8ncjEHW1a9c2a+H98MMPEhfpGDutHubNUlwSJfIc5+ctx87t9cl+AQCIi79Tg4KCJG3atOFuS1dsPHDr1i2ZPHmyqZ7pZIiff/7ZLBqskxwAAABsBLt4QMe6LVq0yCw+fOfOHTOZYs6cOeYTLAAAAGwEu3hAlxzhY70AAEBEmDwBAADgEAQ7AAAAhyDYAQAAOATBDgAAwCEIdgAAAA5BsAMAAHAIljuBT+05uinCVbIBAIB3ULEDAABwCIIdAACAQ9AVC5+wLMv1wcUAACD67N+l9u/W8BDs4BOXLl0yX3PlyuXvpgAA4AjXr1+XdOnShbsNwQ4+kTFjRvP19OnTEb4J4f2/7DRQnzlzhokrfsD59x/OvX9x/n1HK3Ua6nLkyBHhtgQ7+ESiRP83fFNDHd/g/qHnnXPvP5x//+Hc+xfn3zciWyRh8gQAAIBDEOwAAAAcgmAHn0iePLkMGjTIfEXs4tz7F+fffzj3/sX5jxsCrMjMnQUAAECcR8UOAADAIQh2AAAADkGwAwAAcAiCHbxuwoQJkjdvXgkMDJRKlSrJ1q1b/d2keGft2rXSsGFDsxhlQECAzJ8/3+N+HRr74YcfSvbs2SVFihRSq1YtOXLkiMc2ly9fllatWpn1pNKnTy9vvvmm3Lhxw2ObvXv3yjPPPGNeK11YdOTIkZLQjRgxQipUqCBp0qSRxx57TBo3biyHDx/22ObOnTvStWtXyZQpk6ROnVqaNWsm58+f99hGF+euX7++pEyZ0uznnXfekQcPHnhss3r1ailXrpwZbF6wYEGZNm2aJHSTJk2S0qVLu9ZCq1y5svzxxx+u+zn3seeTTz4xP3969erluo3zHw/o5AnAW2bOnGklS5bM+u6776z9+/dbHTp0sNKnT2+dP3/e302LVxYtWmQNGDDAmjt3rk5usubNm+dx/yeffGKlS5fOmj9/vrVnzx7rxRdftPLly2fdvn3btU3dunWtMmXKWJs3b7bWrVtnFSxY0GrZsqXr/qCgICtr1qxWq1atrD///NP6+eefrRQpUlhfffWVlZDVqVPHmjp1qjknu3fvturVq2flzp3bunHjhmubTp06Wbly5bJWrFhhbd++3XrqqaesKlWquO5/8OCBVbJkSatWrVrWrl27zOuZOXNmq3///q5tjh8/bqVMmdLq3bu3deDAAWvcuHFW4sSJrcWLF1sJ2YIFC6zff//d+uuvv6zDhw9b77//vpU0aVLzeijOfezYunWrlTdvXqt06dJWz549Xbdz/uM+gh28qmLFilbXrl1d1x8+fGjlyJHDGjFihF/bFZ8FD3aPHj2ysmXLZn322Weu265evWolT57chDOlPyz1cdu2bXNt88cff1gBAQHWP//8Y65PnDjRypAhg3X37l3XNu+++65VpEiRWDqy+OHChQvmXK5Zs8Z1rjVozJ4927XNwYMHzTabNm0y1/WXWaJEiaxz5865tpk0aZKVNm1a1/nu16+fVaJECY/nevnll02whCd9n37zzTec+1hy/fp1q1ChQtayZcus6tWru4Id5z9+oCsWXnPv3j3ZsWOH6RZ0/2gxvb5p0ya/ts1JTpw4IefOnfM4z/pRM9rtbZ9n/ardr+XLl3dto9vr67FlyxbXNtWqVZNkyZK5tqlTp47pdrxy5UqsHlNcFhQU5PH5x/oev3//vsf5L1q0qOTOndvj/JcqVUqyZs3qcW71szT379/v2sZ9H/Y2fK/8/x4+fCgzZ86Umzdvmi5Zzn3s0K5W7UoNfo44//EDnxULr7l48aL5Qez+Da30+qFDh/zWLqfRUKdCO8/2ffpVx7a4S5IkiQkn7tvky5cvxD7s+zJkyCAJ3aNHj8z4oqpVq0rJkiVd50bDsAbn8M5/aK+PfV942+gvwNu3b5uxkwnVvn37TJDT8Vw6jmvevHlSvHhx2b17N+fexzRI79y5U7Zt2xbiPt778QPBDgDCqVz8+eefsn79en83JUEpUqSICXFaLf3111+lTZs2smbNGn83y/HOnDkjPXv2lGXLlpkJVYif6IqF12TOnFkSJ04cYoaUXs+WLZvf2uU09rkM7zzr1wsXLnjcr7PSdKas+zah7cP9ORKybt26ycKFC2XVqlWSM2dO1+16bnTYwdWrV8M9/xGd27C20ZmgCb1ioVUhnSn55JNPmlnKZcqUkS+//JJz72Pa1ao/N3S2qlb49aKBeuzYseb/WlXj/Md9BDt49Yex/iBesWKFR1eWXtduFXiHdp/qD0b386xdGDp2zj7P+lV/+OoPatvKlSvN66Fj8extdFkVHTNj07/UtVqSkLthdb6Khjrt/tNzFry7Wt/jSZMm9Tj/Oi5Rl3hwP//anegervXc6i8u7VK0t3Hfh70N3ysh6fv27t27nHsfe+6558y502qpfdFxurpskv1/zn884O/ZG3Decic6O3PatGlmZuZbb71lljtxnyGFyM1K06UC9KLfpmPGjDH/P3XqlGu5Ez2vv/32m7V3716rUaNGoS538sQTT1hbtmyx1q9fb2a5uS93ojPcdLmT1q1bm6Uk9LXTJQgS+nInnTt3NkvJrF692jp79qzrcuvWLY8lH3QJlJUrV5olHypXrmwuwZd8eP75582SKbqMQ5YsWUJd8uGdd94xMwsnTJjAkg+WZb333ntmBvKJEyfMe1uv62zupUuXmvs597HLfVas4vzHfQQ7eJ2uSaTf+LqenS5/ouuoIWpWrVplAl3wS5s2bVxLngwcONAEMw3Szz33nFnzy92lS5dMkEudOrVZaqBdu3YmMLrTNfCefvpps4/HH3/cBMaELrTzrhdd286mAbpLly5mGQ79BdWkSRMT/tydPHnSeuGFF8zagLqOV58+faz79++HeJ3Lli1rvlfy58/v8RwJ1RtvvGHlyZPHnBMNBPretkOd4tz7N9hx/uO+AP3H31VDAAAAxBxj7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCYAcA8dC5c+eke/fukj9/fkmePLnkypVLGjZsGOLD1X0tICBA5s+fH6vPCSBsScK5DwAQB508eVKqVq0q6dOnl88++0xKlSol9+/flyVLlkjXrl3l0KFD/m4iAD/hs2IBIJ6pV6+e7N27Vw4fPiypUqXyuO/q1asm8J0+fdpU9LSClyhRIqlbt66MGzdOsmbNarZr27at2da92tarVy/ZvXu3rF692lx/9tlnpXTp0hIYGCjffPONJEuWTDp16iSDBw829+fNm1dOnTrlenyePHlM6ATgP3TFAkA8cvnyZVm8eLGpzAUPdUpD3aNHj6RRo0Zm2zVr1siyZcvk+PHj8vLLL0f5+aZPn26eZ8uWLTJy5EgZOnSo2Z/atm2b+Tp16lQ5e/as6zoA/6ErFgDikaNHj4p2tBQtWjTMbbRKt2/fPjlx4oQZe6e+//57KVGihAlfFSpUiPTzacVu0KBB5v+FChWS8ePHm/3Xrl1bsmTJ4gqT2bJli/GxAYg5KnYAEI9EZvTMwYMHTaCzQ50qXry4CWB6X1RosHOXPXt2uXDhQpT2ASD2EOwAIB7RqpnORI3pBAkddxc8JOoEjOCSJk3qcV2fW7t6AcRNBDsAiEcyZswoderUkQkTJsjNmzdD3K8TIooVKyZnzpwxF9uBAwfMfVq5U9qNquPi3OnEiajS4Pfw4cNoHQsA7yPYAUA8o6FOw1TFihVlzpw5cuTIEdPFOnbsWKlcubLUqlXLLIHSqlUr2blzp2zdulVef/11qV69upQvX97so2bNmrJ9+3Yz9k4fr+Po/vzzzyi3RWfG6pg7XVfvypUrPjhaAFFBsAOAeEYXJdbAVqNGDenTp4+ULFnSTGbQgDVp0iTTXfrbb79JhgwZpFq1aibo6WNmzZrl2odW/QYOHCj9+vUzkymuX79uwl9UjR492syS1fF8TzzxhJePFEBUsY4dAACAQ1CxAwAAcAiCHQAAgEMQ7AAAAByCYAcAAOAQBDsAAACHINgBAAA4BMEOAADAIQh2AAAADkGwAwAAcAiCHQAAgEMQ7AAAAByCYAcAACDO8P8AEUoqOLfifnkAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "country_count.columns = ['country', 'count']\n",
    "sns.barplot(x=\"count\", y=\"country\", data=country_count, \n",
    "            hue=\"country\", palette=\"rocket_r\", orient=\"h\", \n",
    "            dodge=False)\n",
    "plt.title(\"Content contribution by top 10 countries\")\n",
    "plt.xlabel(\"Count\")\n",
    "plt.ylabel(\"Country\")\n",
    "plt.legend([],[], frameon=False)\n",
    "plt.tight_layout()   \n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56e375eb",
   "metadata": {},
   "source": [
    "The United States and India dominate content production on Netflix, together contributing over 50% of all titles."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7976e3f1",
   "metadata": {},
   "source": [
    "### Which year has released most movies or TV shows?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "deec2f41",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAnYAAAHWCAYAAAD6oMSKAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAQ7RJREFUeJzt3Qm8jHX///EPR7Y2cRAplW5b1qwtKipJKqFFRaJb3dGO0kJIC1puIWtKtBBa3P203+2llC3LQYVsOUoq+znzf7y/9+Oa/5xxDmeOw5n5zuv5eBzOzHXNnPlc18xc7/l+v9d3CoVCoZABAAAg4RUu6AcAAACA/EGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAHDTMf45EEA/P03h4DPADwQ5JrVOnTlatWrUsP9WrV7fTTjvN2rVrZ2+88UbM99miRQu79957LVHMmDFjr21Qu3ZtV8eDDz5oGzZsiPk+d+3aZY888oi99dZbB/z4tC31mM4+++wcD37Dhg1z62h/5qevv/7a3a/+j2faRtpf+/Phhx/a9ddfbw0bNnT7+IILLrDBgwfb5s2bs6ynmp955hmLx9eoXp/169d3r89JkybZnj17Duj198EHH9g999wT8zbOr9f51q1brU+fPvbtt99mqTm/n8tIHkUK+gEABa1mzZrWv3//8OWMjAwXZp5//nn3hluqVCk755xzzHcjRoywsmXLut+3b99uy5cvt7Fjx9r7779vr776qp1wwgm5vq9ff/3VXnjhBXv00Ufz5bEVLlzYNm7caN999501aNBgr+Vvv/22HQynnnqqq/2UU06xRDdz5kzr27evXX311dalSxcrUaKErVixwu3jjz76yKZPn25HH320xftrVK/PP/74wz755BP3/FIgevrpp91zJHgeH3HEEbm+b73Oc+OWW26xzp07W35bsmSJ+wDZvn378HWR70dArAh2SHo6CNSrV2+v69VCdPrpp7sWrWQIdjVq1LBKlSqFL6t2tUqoZUQHmokTJxbYY6tQoYJrrfu///u/vYLdvHnzXOirWrXqIXtuJKKRI0faxRdfbA899FD4uqZNm7rWu8suu8ymTZtmN954o8Wj7PaDnpsnn3yya3GcNWuWXXrppeEQeDDE8sHmQPnwQQIFh65YIAfFihWzokWLWqFChcLXZWZmuhYOdWHVqlXLLrzwQnvxxRf3eT87d+60IUOGuHCo21xyySV7tTDt2LHDnnjiCWvZsqVbR13BN9xwg/s0H/jtt9/s7rvvtjPPPNN1o+lg/Prrr2e5n3Xr1tldd91ljRs3trp167put8WLF+d5GyjoXXXVVfbFF1/Y6tWrw9erFe+aa65xXWJ6vK1atbIpU6a4Zb/88oudd9557ne1EEV2X6l15brrrnOPTY9RXWCqKzf0N9599929umO1Lc844wzXshpJLTt6TNrederUsXPPPdd12Wp/iLqJ1bWXlpaW5XaqTddru2XXFav1b7rpJreP9NOjRw9bs2bNfh+/gpNCsgKKHo/2n4JqQB8gFErmz5/vtrn2cfPmzW3ChAlZ7ketVdqu2n6NGjWyoUOHuufl/qSnp2fbla2uTd2f9mOkv/76y+6//373d7Sfb7vtNncf0dteNWm5npf9+vVzj0/UTar7/v3337OES23PL7/8Msv21noK57HSc6l8+fL2yiuv5NhFGoQ+bXMF2V69eoX/lro758yZ436C/Rzsc92ntr/28eeff55td/fu3bvt4YcfdvtBATn6+Zxdl2rkc0o/QSug/g/Wjb6dnrPadnoN6Hmh9wm9D0Xud62v/aXr9VzXemqdXbBgQczbFYmNYIekp4OdxukEP3oT/fHHH93B7u+//3YH4IBaO4YPH+4OFKNHj3ZvtBpLpjfdnO5bB34dJBTUnn32WXcQvPPOO7OEMnX5qiuse/fu9txzz7m/ra5QBbngYNy7d29buXKlDRgwwMaNG+dCgA4kX331lVuuA4reyH/44Qc3Nk5BUW/81157rbtdXumALXPnznX///e//3U1qZty1KhRbizW8ccfbwMHDnShpFy5cq47TP71r3+Ff//mm29cF2Dx4sVd19l9993nDqg6oCnY7k/r1q3D3bEB1Td79mzXEhVNIUNddeeff77b7toOkydPdl1q2qa6vmTJkvaf//wny+0UBP7xj39k2/Lz008/uW2sMWmPP/64ay1SqOvYseNe49QiKWDq8ehvjhkzxgVMfWhQyIgcw6h67rjjDlerDtAKFfpQ8Omnn4aXq1Xt448/dvv+sccec9sjN13ROtirVu071RgZpLRfFHoiKZgpuPz73/92z0ONz9M+Dmjf60OEgqpeE7rfd955xwUM7U/9PW3n4Pkpwe96LgTUpaptrYAWK3W/qmVZ4SV6rF3wnNVrS0FIrxm9rvQYVI+oJVp/Wz/qctdzOqDnrbax9ptes9lRMNfrTftB6+q18c9//tN9qMgN/T3dv+j/7LpgtQ1vvvlmGz9+vF1xxRXh9x29hqLX1/bXmMEHHnjAnnzySRfEb7311lw/HviBrlgkPR1kIt/QRa106trTQU2f2oOD+tSpU93BTAFMzjrrLLeuDtZqwTrmmGOy3I9aunRQfuqpp9zBWpo1a+bGsOng3qZNG3ewVoDUm3GwjlpJ1GKiA4benDX2TSFIB0+Fg2AdtVIpIIjGtG3ZssVefvllO+6448LdybpP1aGDb14E4+42bdrk/te4rMsvv9y1DgR04GvSpIlrgVBrnLp1g+6rICApaJ500kluW6WkpLjrtK5CmUKtgte+qAVCATKyO1YtgKpZ20T3EdBjfO2119wBPNhXCqgKnTrQK0yoBVUtrgpFCtqi/aDxZtrO2dHBXmPTNC4rGMelYKG/rwNvToPwFf66devmQmVA+0itXQofQTDVQVzr6AAuqvO9995zgUHPGz1uhRiFFO3b4O/n5sSJQYMGueeaWj3VShbsH7Wu6kNHdLDS9laoDP6GQrsCpahVTmH5yiuvDAcT0WtG+zHYn9rfap276KKL3HP++++/d6+1yGCn14e2Q16lpqa6AKrngX6PpG2rDxJ6DgSvE71mFi5c6La1ujyD/Rjd1avXswLUvuj1rhZVfUAILuu5o/0UvG/si/520O2q/7PrgtV96X1EQS14nui5rLr0utYHI30QEYVbPZ6gJj2f9ZxUy390iyz8RYsdkp4ONAoB+lErhA5OJ554ovtEHPnGrk/6OhjoIBrZwqfLauULWrQi6aCm4KcQEX0bBSW1yumAozfjoEVKf0ctfAoYwRmmouCk1jF1ialbT4FPb9pq1Qn+lgKVDtDB31GLhgKADgx5FbQYBl3SajFS4NRBY9GiRS4YKaxFPtZoOqgrGGg7RLaQKqhVqVLFdXXlhrZRZHesWqDUMhQ9WF4hWKJb8nRZoTLoWlVrrLqYg+4qtXaohmC8VjTtGwVqHVSDGvS31Q23r22sbjy1zukMSI0J1GD5oOs6eptFtg7puVG6dGnbtm1bOMgedthhLuQFFCpyMwb0yCOPdOFeoU5hTKFWj0djJ/U8V+iKFD2WUd3yWl9Ugx63PphE0nZQYA22v/ZNsF30+tBjVxDRc0G3VwDX8AGtl1/Pz0jqItVzT49THyy0/fRhrGfPntmuHyn4cLIv2u5BqBO9rosUKZIluB4obUvdZ3TIDJ6jwbaWyKAqQVjXNkDyoMUOSe/www93rRMBtSLpTbNr165u3JMOrKIWAcmu20+yGyOk2+jAE4Sv7M4e1QFErRbq0lUXsB6PxhwFB4zgwKVWP3XDqMVKXS4KbRpbpu4xHUz1t1atWrVX62NAb+5qbYpV0FV47LHHhrt81QWkgKCDY+XKld0BPfKxRlMgUGuRWpr0k914xtwGO4VIdT+qhUUhL/JkgEAwzitobQzoAKlWlT///DMclnXwU0DUGCz9r+AW1BpN21hBNruuz+B5kh2FR4UphW+FGw361z7ObpspNEbSfg7WUV1qcYoOJdF17osCmlrT9KN9ov2o4KkWPT3fA5GBJbvHIdEtZMF1wfZV8FFw1LhL1a7XgVr/9EFI4U4fDPTYD6Q1Sa87bbPoMZZBSFaXtlpY9Tj0ux6fujb3N51IdP3Zid7u2kZ6fgUBOD9oW+s+g1bu6L8dbGuJfn0HZwrnZgwm/EGwA6LojV8H4dtvv92NodInfTnqqKPCXZ4KX9EqVqyYbSuJDhAar5QdhSId9IMuVoUWtWLpwK0WnWBsVXBfGmenHwVAtS6phVFj7nTA0nKFEnU1ZifoioqVWlz0eILwppYn/X0dLHXg1P0qNKqbOifaXroPjeXKLhjnNnAqDKl7T+PqNI5LASG71p5g2g61igbd0qIuOw3mD7rMdeDTyRUac6aDvVoOI8eRRdM2VphW12U0hcbs6KCqrkAFOrUKK8hrXbVWxTpPoh63Hr/GTEUe6IMPHTnRBwGFcXXTa/sFVL/Gn6mFaV/7L6ftq1ZjhdRI2uZ6DoueM2pBUqhTa6daCRWk1SKuVlO14mn/7a/1LCdqMdX9KDBGB5+AWjeD4Q96DHot6oQHfYBTmD8Q0dtd+0X7p0yZMlmuixS0vsayrbPb5/pQKNHDPwC6YoFsqNtDBwMd8IOujiDY6E1WLXzBj1qwNNYlu4OrgpbeyNXSEXkbnVmpEy50YFKrhQKKDv4a8xQc5IJQp9uuXbvWtX4o0IgOphqkrZChrqzgb2kcoA7ckX9L4UGBIqcD3/5a69Ttq4OvphwRHYwVBtTaFYRFjQOKbBmI/ls6uGusnQJh5GPT2CB1L8cyAXDQHatWM52dnF1rn7aFRJ8Yocs6QEZ2M6o7VnVqf+hxq7ac6H4VyBTOghrU2qSQq7Fw2dHzRfulQ4cObv0gAEZvs9xQa5eeM8EYOVGX5v66srWd9fzUh5Ls/PzzzzFNF6NQpH2v10ckdXXq+Ri0UCvMajyYPoRonFewX3SihsYNav3cjEXLiU54UJDUySvZ0Qkumh9OryF9eNDfCsZBBq+boFUrL7TdI0/aUIDWZb02gud99ATf0UM29ve61DbTfQav/cCbb77p/s9uXkckN1rsgBzorE11yerTvSZ31RQFuqwzThW0dEDXAVtdpOreUitENIUxjfPRgHj9aDyZxnNprJOCo7rv1HWqg72mrVD3rw7U6hLTgU8UDPW31T2ox6KTKhQAFQg1mF1Tb4hawxTi9L/uR5/kFX7UEqOzAfdHB95gOgu1bixbtswFFnVzRQ6QVyuHpgrR49ZjUreoWgwVSIOxPGrZErXUqGYFgeCkE53QoO2ogKUzgNUlF3lSQW6CnUKYalWLZXY01kgneGg76zFpH6g+nfygg27kGDUFGgW1l156yQ3y39fktnqcOitW21xhQqFS4UJBK6eTU9R6o1ZDtcBqe6nlV6E9aMWNZfyTgp3GiOlEG52Fq/vV/ejDRWQrUTR9ENC2V4uwAo22vx6L7kPbUfsplnkK1e2p+9N+UHhTYFJ3qz7gBNs+8jWg15JaroMuV+0DjSPV9tOHk/3Rc17j+oIgrLD82WefuW2vWnIK4wqQqktdzVpPLbY6yUWPPzgLWPtD4wu1DWKdA0+hUmedqltX4VgnOCjIaj+JtovOJtbZ2Rp/pyAbPUVR8FrR612tc0EXfUBjZLW9tM/V7azl+rCpIQ3azsx5h2gEO2AfB0O9YSt8qAtLc2bpDVoHRx2U9ElcB1MFDU1Rkd0nb7UGKPTogKfb6UCqrih15QVnXqo7Vt29Ch2aHkRv7ho/pvnx9Pd1MFCw03IdOHRfOrCpBU2DwIOzPoP5vHRfGnemVkCFTXUnq7Vof3RfAR2sFRrUIqb7jxxLpBMnNB5LP6K/oe5gtSAEX4ukcKQadeBV+FTLhgKJThJRHToBRH9D4VAH3lgmAdaBTGFMB9V9hQLVrW2rMzR1ENQZsRq4r3AW3UqjVjvVldNJEwEdVBXQFObV5a2WID0WBZxg7r7sKIDq8ShgqKVLNeisUo2r1DaL5eujtP10RrWCpPaxnn86O1WtYvuiYK0AqxbY4AOCQo1aotWiGx0o9keBRsMWNIWM9rPCklq69VqIHJ+mYKfQr1a8oLVSQUXX6f/cdMNrTkHN7Se6nbr2td31PA/OIM6O/ra2lV7DwQkTauFSGA7G5GmsoT4kqQVcr289T3JLZ85qjJtey9qv6tbXUImg1V2thRpqoQ+Gem3qA4b2W2QLo1pTdXJHMPQiuhU0OOtet9MHLYV4fZDU/sxuSABQKMQ3DwMAAHiBMXYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJ57PJAE2QGX7Ce16/CAQAAyA3NTKfsobkg9/dtKQS7PFCoW7hwYUE/DAAAkERq16693+/9JtjlQZCWtYFz8/2b+uokBcHcru+TZK2dupOr7mSunbqTq+5krj2jAOsO/nZuvtuYYJcHQferdmwsOzfW9X2SrLVTd/JJ1tqpO/kka+0pBVh3boZ/cfIEAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJ+Ii2O3atcvatGljX3/9dfi6NWvWWJcuXaxevXrWunVr++yzz7Lc5osvvnC3qVu3rnXu3NmtH+n555+3Zs2aWf369e2+++6z7du3h5ft3LnTXdewYUM766yz7LnnnjsEVQIAAHge7BSy7rrrLlu+fHn4ulAoZD169LDU1FSbPn26XXbZZdazZ09bt26dW67/tbxdu3b22muvWenSpe2WW25xt5N33nnHRowYYQMHDrQXXnjB5s+fb0OHDg3f/5AhQ2zRokVuWf/+/d26s2fPLoDqAQAA8k8RK0ArVqywu+++OxzIAl999ZVrgXvllVesZMmSVqVKFfvyyy9dyLv11ltt2rRpVqtWLevatatb/9FHH7UzzzzT5syZY02aNLFJkybZ9ddfb82bN3fLBwwYYN26dbPevXu7v6Xbjxs3zk499VT3o1A5ZcoUa9WqVYFsBwAAktXq1astPT3d4l1GRoalpaVZZmampaSkZFmmhqgTTjjBLNmDXRDE7rzzTtflGlALW82aNV2oCzRo0MDmzZsXXq5u1ECJEiVcQNNyXb9w4ULXwhfQfe/evduWLl3qgt2ePXtcF23kfY8ePdrtrMKFC7wREwCApAl11atVt+07/v9wqURUongJW7psaVyEuwINdtdcc02212/atMnKlSuX5boyZcrYhg0b9rt869atrns3cnmRIkWsVKlSbrmC2zHHHGNFixbNkrR1my1btrhuXQAAcPCppU6hrp21s1RLtUSUbuk2Y8cMV0vSB7uc6ESHyOAluqyTLPa3fMeOHeHL2S1Xi112yyS4/1iaZWNZL7fr+yRZa6fu5Ko7mWun7uSqO79rD+5Doa6iVTzg+ytIquVgPR9iud+4DHbFihVzrWeRFLqKFy8eXh4dwnT5qKOOcsuCy9HL1WWrjZPdMgnuP7fU5Xsw1/dJstZO3cknWWun7uSTH7VrzJov0tLS4mI4V1wGu/Lly7sTKyKpiTPoXtXy6IGWulyjRg3X5apwp8s66UI0pk5BsWzZsq7F7vfff3fXqYs26NpVqFMwjEXt2rX3GkCZHYVJvQByu75PkrV26k6uupO5dupOrrrzu3aNbfdF1apVs5wvcDC2ecIGO81NN3bsWNetGrSizZ07153kECzX5YC6ZhcvXuxOmFBa1pNNy3VihuikCoW46tWru8v6PTjRIrhv3SbWpK0ndCxP6ljX90my1k7dySdZa6fu5JMftfu07VLi5LlQ8G2G2WjcuLFVqFDB+vbt66YiUchbsGCBdejQwS1v3769fffdd+56Ldd6lSpVCgc5nZQxYcIEe//9993tHnroIbvyyitdV6x+2rZt667TMq2jCYo1yTEAAEAii8sWOyXeUaNG2f333+8mIa5cubKNHDnSKlb838BKhbhnnnnGHnnkEXe9pi7R/4UKFXLLL774Ylu7dq3169fPjZ9r2bKlm8MuoCCoYKe57o444gg3N57WAQAASGRxE+yWLVuW5bLC3OTJk3Nc/5xzznE/Oenevbv7yY5a7R5//HH3AwAA4Iu47IoFAABA7Ah2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJ+I62K1fv95uuukmO+2006xFixb2/PPPh5ctXrzYrrjiCqtbt661b9/eFi1alOW2s2bNsvPPP98t79Gjh/3222/hZaFQyIYNG2ZNmza1xo0b25AhQywzM/OQ1gYAAJBUwe6OO+6wkiVL2owZM+y+++6zp59+2t577z3btm2bde/e3Ro2bOiW1a9f3wVAXS8LFiyw+++/33r27Gmvvvqqbd261fr27Ru+34kTJ7rgN2LECBs+fLi99dZb7joAAIBEFrfB7o8//rB58+bZv/71LzvxxBNd61uzZs3syy+/tLffftuKFStmffr0sSpVqrgQd/jhh9vs2bPdbSdPnmwXXXSRtW3b1qpXr+5a5D7++GNbs2aNWz5p0iS77bbbXDBUq12vXr1sypQpBVwxAACAp8GuePHiVqJECdcit3v3bvvxxx/tu+++sxo1atj8+fOtQYMGVqhQIbeu/ld3rYKgaLlCW6BChQpWsWJFd/3GjRtdF2+jRo3Cy3Vfa9eutV9//bUAKgUAAPA82KlFrl+/fq4rVePk1AJ39tlnu3F1mzZtsnLlymVZv0yZMrZhwwb3uwJaTst1W4lcnpqa6v4Pbg8AAJCIilgcW7lypTVv3txuuOEGW758uQ0aNMhOP/102759uxUtWjTLurq8a9cu9/uOHTtyXK5lweXIZRLcPrcyMjJiWi+36/skWWun7uSqO5lrp+7kqju/a/dp+2VkZBy0emK537gNdhpL99prr7mxceqWrV27tutGffbZZ+3444/fK4TpstYLWvuyW66u3cgQp/WC30XLY7Fw4cKDur5PkrV26k4+yVo7dSef/Kg9LS3NfJGWlmaFCxd8R2jcBjtNX1K5cuVwWJOaNWva6NGj3fi59PT0LOvrctC9Wr58+WyXly1b1i0TdclWqlQp/LtoeSwUNlNSUnKVtPUCyO36PknW2qk7uepO5tqpO7nqzu/afZpqrGrVqlavXr2Dus0TOtgppK1atcq1pgWtbDqBQmFMY+7GjRvn5qPTiRP6XydW3HzzzW49LZ87d661a9fOXdbJEvrR9Qp2OpFCy4Ngp991XfS4vP3REzqWJ3Ws6/skWWun7uSTrLVTd/LJj9p92nYpcfJcKPg2wxxoQuLDDjvMHnjgAfvpp5/sww8/dK11nTp1slatWrm56QYPHmwrVqxw/2vcnU6wkI4dO9obb7xh06ZNs6VLl7ppUc4991zXhRss1wTFX3/9tft54oknrHPnzgVcMQAAwIGJ2xa7I4880n3ThEJbhw4drHTp0m5Ou6uuusq10o0ZM8b69+9vU6dOtWrVqtnYsWPdZMaiCYsHDhzoJh/WfHhnnnmmO/Ei0K1bN9u8ebObwFjpWvffpUuXAqwWAADA42Anp5xySo7fCFGnTh2bOXNmjrdVN2zQFRtNYU7fRBH5bRQAAACJLm67YgEAABAbgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOCJuA52u3btsgEDBlijRo3sjDPOsCeffNJCoZBbtnjxYrviiiusbt261r59e1u0aFGW286aNcvOP/98t7xHjx7222+/hZfpPoYNG2ZNmza1xo0b25AhQywzM/OQ1wcAAJA0we7hhx+2L774wiZMmGBPPPGETZ061V599VXbtm2bde/e3Ro2bGgzZsyw+vXr20033eSulwULFtj9999vPXv2dOtv3brV+vbtG77fiRMnuuA3YsQIGz58uL311lvuOgAAgERWxOLUli1bbPr06S5w1alTx13XtWtXmz9/vhUpUsSKFStmffr0sUKFCrkQ98knn9js2bOtXbt2NnnyZLvooousbdu27nZqkWvevLmtWbPGjj/+eJs0aZLddtttLhhKr1697N///rd169atQGsGAADwssVu7ty5dsQRR7iu0oBa6R599FEX7ho0aOBCnej/0047zebNm+cua3kQ2qRChQpWsWJFd/3GjRtt/fr1rns3oPtau3at/frrr4e0RgAAgKQIdmpdO+644+z111+3Vq1a2XnnnWcjR450Y+E2bdpk5cqVy7J+mTJlbMOGDe53BbScluu2Erk8NTXV/R/cHgAAIBHFbVesxsutWrXKXnnlFddKp0DWr18/K1GihG3fvt2KFi2aZX1d1skWsmPHjhyXa1lwOXKZBLfPrYyMjJjWy+36PknW2qk7uepO5tqpO7nqzu/afdp+GRkZB62eWO43boOdxtH99ddf7qQJtdzJunXr7OWXX7bKlSvvFcJ0uXjx4u53jb/LbrlCYWSI03rB76LlsVi4cOFBXd8nyVo7dSefZK2dupNPftSelpZmvkhLS7PChQu+IzRug13ZsmVd8ApCnZx00klufJzG3aWnp2dZX5eD7tXy5ctnu1z3qWWiFsBKlSqFfw/+Zixq165tKSkpuUraegHkdn2fJGvt1J1cdSdz7dSdXHXnd+0+TTVWtWpVq1ev3kHd5gkd7DT/3M6dO+2nn35ygU5+/PFHF/S0bNy4cW4+Op04of+/++47u/nmm8O31ckXOkNWFAb1o+sV7HQihZYHwU6/67rocXn7oyd0LE/qWNf3SbLWTt3JJ1lrp+7kkx+1+7TtUuLkuVDwbYY5OPnkk+3cc891888tXbrUPv30Uxs7dqx17NjRnUyhuekGDx5sK1ascP9r3J2mOBGt88Ybb9i0adPcbTUtiu5LU50EyzVB8ddff+1+1N3buXPnAq4YAADgwMRti50ofA0aNMgFMY1/u/baa61Tp06ulW7MmDHWv39/N2lxtWrVXOgrWbKku50mLB44cKCbfPiPP/6wM888091PQPPVbd682U1grHTdoUMH69KlSwFWCgAA4HmwO/LII93kwtnRpMUzZ87M8bbqhg26YqMpzKklMPLbKAAAABJd3HbFAgAAIDYEOwAAAE/ke7D77bff8vsuAQAAcLCCXY0aNbINcPq+VX31FwAAAOL45Al9Z+uMGTPc75o3rkePHnbYYYdlWUff0RrrJL8AAAA4xMHuggsusF9++cX9PmfOHDe78uGHH55lHU03ovUAAAAQx8FOIU7zvom+/aF169bh71oFAABAgs5jd/nll9uqVats0aJFtnv37r2Wt23bNj8eGwAAAA52sBs/frz7Voijjz56r+5YfSsEwQ4AACBBgt1zzz1nvXv3dl/NBQAAgASe7mTnzp3WsmXL/H80AAAAOLTB7pJLLrGXXnrJTXsCAACABO6K/euvv+y1116zWbNmWaVKlfaaz27SpEn59fgAAABwMIPdiSeeaDfffHNebgoAAIB4CnbBfHYAAABI8GDXt2/ffS5/9NFH8/p4AAAAcChPnoi2Z88e++mnn+ztt9+20qVL58ddAgAA4FC02OXUIqeJi9PS0vJylwAAAIiHFrtAq1at7L333svPuwQAAMChDnbbtm2zqVOn2jHHHJNfdwkAAICD3RVbvXp1952w0YoVK2YPP/xwXu4SAAAABRHsoicgVsjTJMWnnHKKHXHEEQf6mAAAAHCogl3jxo3d/z///LOtXLnSMjMz7aSTTiLUAQAAJFqw27p1q5vL7oMPPrCjjz7aMjIy7O+//7ZGjRrZyJEj7cgjj8z/RwoAAID8P3lC4+g2bNjg5q37+uuv7dtvv7W33nrLnUDB5MQAAAAJFOw+/PBDe+ihh+zkk08OX6fxdf369XOteAAAAEiQYKezXwsX3vumOolC3bIAAABIkGDXokULGzBggK1evTp8nU6kUBftOeeck5+PDwAAAAfz5InevXtbjx497MILL7SjjjrKXffHH3/Y2WefbQ8++GBe7hIAAACHOtitWrXKKlasaC+++KItW7bMTXeirtkTTzzRqlSpcqCPBwAAAAe7KzYUCrmu1osuusi+//57d121atWsdevWNn36dGvTpo099thjbj0AAADEcbDTt01oehPNUxdMUBwYNWqUu37mzJn28ssvH4zHCQAAgPwKdlOnTnXj55o3b57jCRW9evUi2AEAAMR7sFu7dq3VqVNnn+s0bdrU1qxZkx+PCwAAAAcr2JUpU8aFu33Rt1GUKlUq1scAAACAQxnsLrjgAnvmmWds9+7d2S7fs2ePjRgxws4666z8eFwAAAA4WNOd3HLLLdahQwdr166dderUyWrVqmVHHnmkm7/uhx9+sMmTJ9vff/9tQ4YMifUxAAAA4FAGO01ErBMohg0b5qY12b59u7te05so4Gnak1tvvdVSU1Pz43EBAADgYE5QrPFzmsuuX79+7iSJrVu3uutOOOEES0lJifVvAwAAoKC/Uqxo0aJ8ywQAAECinjwBAACA+EawAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8kTDBrnv37nbvvfeGLy9evNiuuOIKq1u3rrVv394WLVqUZf1Zs2bZ+eef75b36NHDfvvtt/CyUChkw4YNs6ZNm1rjxo1tyJAhlpmZeUjrAQAASMpg95///Mc+/vjj8OVt27a5oNewYUObMWOG1a9f32666SZ3vSxYsMDuv/9+69mzp7366qu2detW69u3b/j2EydOdMFvxIgRNnz4cHvrrbfcdQAAAIks7oPdli1bXIta7dq1w9e9/fbbVqxYMevTp49VqVLFhbjDDz/cZs+e7ZZPnjzZLrroImvbtq1Vr17d3V7BcM2aNW75pEmT7LbbbnPBUK12vXr1silTphRYjQAAAEkR7B5//HG77LLL7JRTTglfN3/+fGvQoIEVKlTIXdb/p512ms2bNy+8XKEtUKFCBatYsaK7fuPGjbZ+/Xpr1KhReLnua+3atfbrr78e0toAAACSJth9+eWX9u2339ott9yS5fpNmzZZuXLlslxXpkwZ27Bhg/tdAS2n5bqtRC5PTU11/we3BwAASERFLE7t3LnT+vfvb/369bPixYtnWbZ9+3YrWrRolut0edeuXe73HTt25Lhcy4LLkcskuH1uZWRkxLRebtf3SbLWTt3JVXcy107dyVV3ftfu0/bLyMg4aPXEcr9xG+x0YkOtWrWsWbNmey3T+LroEKbLQQDMaXmJEiWyhDitF/wuWh6LhQsXHtT1fZKstVN38knW2qk7+eRH7WlpaeaLtLQ0K1y44DtCi8TzmbDp6enujNfI8PXOO+9YmzZt3LJIuhx0r5YvXz7b5WXLlnXLRF2ylSpVCv8uWh4LndCRkpKSq6StF0Bu1/dJstZO3clVdzLXTt3JVXd+1+7TVGNVq1a1evXqHdRtntDB7sUXX7Q9e/aEL2veOdEZrN98842NGzfOzUenEyf0/3fffWc333yzW0dz182dO9fatWvnLutkCf3oegU7nUih5UGw0++6Lnpc3v7oCR3LkzrW9X2SrLVTd/JJ1tqpO/nkR+0+bbuUOHkuxG2wO+6447Jc1nQmUrlyZXcixBNPPGGDBw+2q6++2l555RU37k5TnEjHjh2tU6dOLjnrE4XWO/fcc+34448PL1dQPPbYY91l3VfXrl0PeY0AAABJEez25YgjjrAxY8a4kyumTp1q1apVs7Fjx1rJkiXdcnXfDhw40E0+/Mcff9iZZ55pgwYNCt++W7dutnnzZjeBsdJ1hw4drEuXLgVYEQAAQBIFu8ceeyzL5Tp16tjMmTNzXF/dsEFXbDSFOX0TReS3UQAAACS6gj99AwAAAPmCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOCJIgX9AAAAQN6sXr3a0tPTD+nfzMjIsLS0NMvMzLSUlJQDuq8lS5bk2+PC/xDsAABI0FBXvVp1275je0E/FMQRgh0AAAlILXUKde2snaVaqiWi5bbcPrKPCvpheIVgBwBAAlOoq2gVLRGl26HtRk4GnDwBAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ4g2AEAAHiCYAcAAOAJgh0AAIAnCHYAAACeINgBAAB4gmAHAADgCYIdAACAJwh2AAAAniDYAQAAeIJgBwAA4AmCHQAAgCcIdgAAAJ6I62C3ceNGu+2226xx48bWrFkze/TRR23nzp1u2Zo1a6xLly5Wr149a926tX322WdZbvvFF19YmzZtrG7duta5c2e3fqTnn3/e3Wf9+vXtvvvus+3btx/S2gAAAJIm2IVCIRfqFLimTJliTz31lH300Uf29NNPu2U9evSw1NRUmz59ul122WXWs2dPW7dunbut/tfydu3a2WuvvWalS5e2W265xd1O3nnnHRsxYoQNHDjQXnjhBZs/f74NHTq0gCsGAADwNNj9+OOPNm/ePNdK949//MMaNmzogt6sWbPsq6++ci1wCmZVqlSxm266ybXcKeTJtGnTrFatWta1a1d3W93H2rVrbc6cOW75pEmT7Prrr7fmzZtbnTp1bMCAAe62tNoBAIBEFrfBrmzZsjZ+/HjXKhfpr7/+ci1sNWvWtJIlS4avb9CggQuCouUKgoESJUrYqaee6pZnZGTYwoULsyxXKNy9e7ctXbr0kNQGAACQVMHuqKOOcmPgApmZmTZ58mRr2rSpbdq0ycqVK5dl/TJlytiGDRvc7/tavnXrVjdOL3J5kSJFrFSpUuHbAwAAJKIiliA0Bm7x4sVuzJxOfChatGiW5bq8a9cu97u6VHNavmPHjvDlnG6fW2r9i2W93K7vk2StnbqTq+5krp26C67uZNvm8S4jI+Og7ZNY7rdIooQ6neSgEyiqVq1qxYoVsy1btmRZR6GsePHi7nctjw5puqxWQC0LLkcvV5dtLNSlezDX90my1k7dySdZa6fuQy8tLa3A/jay3x+FCxd8R2jcB7tBgwbZyy+/7MLdhRde6K4rX768rVixIst66enp4e5VLdfl6OU1atRwXa4Kd7qsEy9kz549LihqXF8sateubSkpKftdLxjXl9v1fZKstVN3ctWdzLVTd8HVrSFKiB9Vq1Z1Y/YP5vMt4YOdpiR55ZVX7Mknn7RWrVqFr9fcdGPHjnXdqkEr3dy5c90JFMFyXQ6oa1bduJoSRWlaL0Qtb9KkiVuukyo0zq569eoxPT69mGN5Qce6vk+StXbqTj7JWjt1F8zfRvxIiZPXQMG3GeZg5cqVNmrUKPvnP//pAptOiAh+NGFxhQoVrG/fvrZ8+XIX8hYsWGAdOnRwt23fvr1999137not13qVKlUKB7lrrrnGJkyYYO+//7673UMPPWRXXnllzF2xAAAA8SRuW+w++OAD1/T47LPPup9Iy5Ytc6Hv/vvvd5MQV65c2UaOHGkVK1Z0yxXinnnmGXvkkUfc9fp2Cf1fqFAht/ziiy9289r169fPja1r2bKl9e7du0DqBAAA8D7Yde/e3f3kRGFO05/k5JxzznE/eb1/AACARBO3XbEAAACIDcEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAE0UK+gEAAFAQVq9ebenp6Xm6bUZGhqWlpVlmZqalpKRYQViyZEmB/F3EN4IdACApQ131atVt+47tBf1QgHxFsAMAJB211CnUtbN2lmqploiW23L7yD4q6IeBOEOwAwAkLYW6ilbRElG65a0bGX7j5AkAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ESRgn4AAIDEsnr1aktPT3e/Z2RkWFpammVmZlpKSooliiVLlhT0QwAOCoIdACCmUFe9WnXbvmN7QT8UANkg2AEAck0tdQp17aydpVqqJarlttw+so8K+mEA+Y5gBwCImUJdRatoiSrd/teVDPiGkycAAAA8QbADAADwBMEOAADAEwQ7AAAAT3DyBAAU0BxwiYj534D4RrADgEOEOeAAHGwEOwAJI55bu3LzDQxq7Ur0OeCY/w2IbwQ7AAnBp9auRJ4DjvnfgPiWtMFu586dNmDAAHv33XetePHi1rVrV/cDID758I0HtHYBONiSNtgNGTLEFi1aZC+88IKtW7fO7rnnHqtYsaK1atWqoB8akLBdmAfzC+GDQfu0dgFAzpIy2G3bts2mTZtm48aNs1NPPdX9LF++3KZMmUKwg3d86sIEAOxbUga7pUuX2p49e6x+/frh6xo0aGCjR492LQ2FCzO9Hw6stetgtlzFyocB+0I3JgDsX1IGu02bNtkxxxxjRYsWDV+Xmprqxt1t2bLFSpcubfEgns8AjKV1dNWqVXERcPJi/fr11qF9B9uxc4clukTuwhS6MQFg/5Iy2G3fvj1LqJPg8q5du/Z7+1AoFF43N2FFrTexrC+//PKLNW7UOOEDRSErZCH73/ZKVClFUuyCIhfYUXaUJaJ1ts4W2ALbalvtMDvMEtU222aH2+EJXQc1xA8f6qCG+LDVtroadKzPTYbIiyBHBPljX5Iy2BUrVmyvjR9c1hmy+6PWJ1m8eHFMfzfW9d95952Y1gcAAIdeL+vl/l+4cOFB/TtB/tiXpAx25cuXt99//92NsytSpEi4e1ah7qij9t8qo9vUrl3bjcUrVKjQIXjEAAAgWYVCIRfqgsyyL0kZ7GrUqOE2zrx586xhw4buurlz54bD2v5oneiuXAAAgIKWlKd/lihRwtq2bWsPPfSQLViwwN5//3177rnnrHPnzgX90AAAAPKsUCg3I/E8PYFCwU7fPHHEEUdYt27drEuXLgX9sAAAAPIsaYMdAACAb5KyKxYAAMBHBDsAAABPEOwAAAA8QbDLI01o3KZNG/v666/D1y1atMiuuuoq9x20V155pZtOJTvz5893U67o2yUCGuo4bNgwa9q0qTVu3NiGDBmSq4kIE6X2Sy+91KpVq5blR9+lmki156XuOXPm2GWXXWZ169Z1y/U9xQFf627RosVe+1o/I0aMSKi687rPX375ZTvvvPPstNNOcydlrVmzJrwsUWrPS92vv/66XXjhha7uHj16uLlBIz3//PPWrFkzd/v77rvPncAWLzZu3Gi33Xab2yd6jI8++qj7iknR/tOJdfXq1bPWrVvbZ599luW2X3zxhdtWeo1rZoXI/R3vdR9o7YE333zTOnXqtNf18Vz7xgOoe/r06daqVStX1xVXXOGmS4urunXyBGKzY8eOUI8ePUJVq1YNffXVV+669PT0UIMGDUIPPPBAaMWKFaGJEyeG6tWrF1q7dm2W2+7atSvUpk0bd9s1a9aEr58wYULonHPOCX3zzTehL7/8MnTWWWeFxo8fH/Kh9j179oRq164dmjNnTujXX38N/+zevTthas9L3atXrw7VqVMn9Mwzz4R++uknt17z5s1DO3fu9LruzZs3Z9nPL774olv/l19+SZi681r7J598Eqpfv37oww8/DP3444+hnj17hi655JLwfSZC7Xmtu0aNGm5fa3mvXr1Cl112WSgjI8Mtnz17tru9tsv8+fNDrVu3Dg0YMCAUDzIzM0NXXnll6MYbbwylpaW5fXPBBReEHnvsMbdM++/uu+92dY0ePTpUt27dcN36X9tB+1W3vf322937u24X73UfaO0BPY91/XXXXZfl+niuPfMA6v7444/d+/obb7wR+vnnn0NPPfVU6LTTTgtt2LAhbuom2MVo+fLloUsvvdTt+Mg3Pr05n3feeS7EBLp16xYaNmxYltuPGjUqdPXVV+8V7PRmP3369PDl119/3YUAH2rXk7969erugJGdeK89r3U/8sgjWd7stm3b5tZfsmSJ13VH2rp1a6hp06ahqVOnhq+L97oPpPZBgwaFbr311vCypUuXutsr7CZC7Xmtu3v37qE+ffqEl23fvj3UuHFjF/jkmmuuCQ0fPjy8XAdSHRz1mihoOnir1k2bNoWve+utt1zo/uKLL1xw+/vvv8PLrr/++nAtTz/99F6vcQX7YLvFc90HWrvoQ2utWrVcmI0OdvFc+4oDqPuOO+4I9evXL8v9tWzZMvTqq6/GTd10xcZIXWtNmjSxV199Ncv1aro99dRTLSUlJXydup8iuyt++uknmzJlit177717NQmvX7/eGjVqFL6uQYMGtnbtWvv1118t0WtfsWKFVahQwX1Hb7REqD2vdet2LVu2zDIxtibDrl69utd1R5owYYKVLVvW2rdv7y4nQt0HUnupUqXsm2++sZUrV7qvLFT35HHHHWdHH310QtSe17q1vE6dOuFl+nrGE044wS3Xl5fr+zODb/kRdXHt3r07y9CEgqLn5/jx4y01NTXL9X/99ZcbNlOzZk0rWbJkln0W1K3lkXXpNa7tlAh1H2jt8vnnn7vXeOT7nMR77WUPoO4bb7zRbrjhhr3u888//4ybupPyK8UOxDXXXJPt9XqCRO+4DRs2uO+kFbWO9uvXz2699VYrU6ZMlvWCsSjlypXLcn/BfURen4i16yB32GGH2U033eTG6Zx00knWp08fdyBIhNrzWrcOdjrAaRzHt99+a6eccop7Duh/n+sOaFzJ5MmTbeDAgeGv6kuEug+kdo0z+vLLL924HIUgHej1YU6/J0Ltea1b72mR4VTjBhVktXzr1q1u7FJkffpKR4Vg3UdB0/eDazxU5GPX81bjILXPoveLag0e976Wx3vdB1p7MJ5UIsdiSrzXftQB1K3gHumTTz6xn3/+2d02XuqmxS6f6BOLvp5s6tSp7pP6p59+ah988IFL6vLaa6+53zXoONqOHTvc/5HfPxv8rkHMiV67Wir/+OMPN8h07NixVqVKFbv++utd60Ui176/urdt2+YGyquFZty4ca7VUgNy//77b6/rDrz99tvuU2/kp/lErjs3tSvc6I1d+/2VV15x+753797uukSufX91K8jqIP/999+760aPHm2bN292v2dXd3A5HuseOnSoLV682O6880734WRfj3tfyxOt7lhr35dEq31oHutevXq19e3b1y655BIX+OKlboJdPqlataoNGjTInVlTu3Zte+qpp6xjx452+OGHu08AuqyWi0KFCu112+ze3IPf9Yk/kWsXLVMX5Pnnn++e/Poqt0qVKtkbb7yR0LXvr2610ugMUbXiqG6tq0+GH374odd1B9555x13wNcn1kAi152b2vv37+9CkN7o1SL9xBNPuE/qCkGJXPv+6tYH1osvvtiuvfZad3bo8uXL7eyzz3Zf1xgMwYg+sOlyvNWtA/wLL7zg/lfNeuzZPW61xEtOy1VXItWdl9r3JZFqH5rHutVgobOgjz/+eHv44Yfjqm6CXT7SOCJ1uX388cc2Y8YMF+IUYHSqtLokgqkCdGq86H99si1fvry7HDk9QPC7xgIkcu2iA7ve4ANadvLJJ7uumkSvfV916/Gr2zmgA7vGW6ml0ue6gzcyjddSmI+U6HXvr/YffvjBjaEMKPhUrlzZjaNL9Nr3Vbc+xCjUatoHTf+h4Kfa9HxXN5QOeOnp6eH7Uqvfli1b4qpuBdeJEye6A7ymbRHts8jHLbocdLXltFx1JUrdea19XxKl9kF5rFsfXK677jo79thj3Vi9IPTFS90Eu3zy1VdfuWZcvcHpCaAxdequ0EDkCy64wGbPnu0GUutH3ZGi/6+++mr3RKpYsWKWuXD0u66Lh3E3B1K7qMUqmMNM1Gq1bNkyF+4Sufb91a1Bs6ozMuxo3J0Ohj7XLapbb2iRA+olkevOTe26TmNKI/e55qv0fZ9r3i69n6lVQgc3dUkvWbLEzRGm8ZVq5YusWwPR9YEvMgQXJL0/qev8ySefdC2PAbU+KqwHXWyiOnR9sDyyLnXjqUtP1ydC3QdS+74kQu0j8li3nttdu3Z1H9h04khko0W81M3JE/lELTMfffSRvfTSS25Qpna4xpW1bdvWfWqP3PnBmWV6Q9eboKhbQ+Ny9AlA1IWjJ0+i1y7qjhw5cqSblFnrTpo0yZ1BdPnllyd07furW+MI1TWlM6rOOOMM98lOn+bOPfdcr+sOPtEqzESPNUnkunNTu8aRqhX+xBNPdG/8Y8aMca9/vQYSufb91a19rbFGCvIaaP7ggw/aOeec47q2gpMydOKQLisYajiGum/joVtOQXzUqFHWvXt391qNbFFVMNXYWNV2yy23uG2gsYbqkg5aMbUtFGqbN2/u3ue0LYLAG891H2jt+xPPta88gLoff/xx1zgxePBgN45aP6LxxHqtx0Xdh2xiFQ9FzvMkH330UahVq1ZuMsPOnTu7uXKyo/nrouex0/xQmvesYcOGoSZNmoSGDh0anuQy0WtXHc8++2zo3HPPdXMeXXvttaFly5YlZO2x7vP33nsvdOGFF7q6NX+hJsNMhrrHjBnjJgDNTiLVHWvtqk21t2jRwk1aqrneNFF1MuxzTeR65plnutruvffe0J9//pllubbL6aef7iZv7du3b47zWh5qelyqNbufYB5OvWfpNXzxxReHPv/88yy3/+9//+vmMdNcZZrvLHJ/x3Pd+VF7QPO2Rc9jF8+1j8lj3Xqtaj9nd7vIuesKuu5C+ufQxUgAAAAcLIyxAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAAA8QbADgDy466673Ndm6ftBo91www3ue6CZ/x3AoUawA4A8uOeee9x3Huu7YSO9++679s0339jAgQOtUKFCBfb4ACQngh0A5EH58uXt1ltvtYkTJ9qaNWvcdTt27LDHHnvMtdjpS8AB4FAj2AFAHnXq1MkqV65sQ4cOdZfHjx9vhQsXth49etj69evt5ptvtrp161qLFi1sxIgRlpGREb7ttGnTrFWrVlarVi1r0qSJDRgwILz83nvvdT+XXnqpnX766fbzzz8XWI0AEkuRgn4AAJCoihQpYv369XMB7/3337cJEybY8OHDrVixYtazZ0+rXr26zZw50zZt2uTWU9esQt+cOXPs4YcfdoGwZs2atmjRIuvdu7cLcS1btnT3/cYbb9jIkSMtNTXVTjzxxIIuFUCCoMUOAA5Ao0aN7JJLLrHbb7/dmjdvbs2aNbOvvvrK1q1bZ4MGDbKTTz7ZtchpTN6kSZPcbUqWLGmDBw92Ia5SpUqu5U4Bb/ny5eH7rV27tmvpq1OnTgFWByDR0GIHAAdIXa5vvvmma42TlStX2pYtW6xBgwbhdTIzM90YvN9//911vxYvXty17q1YscKWLVtmq1atsrPOOiu8/nHHHVcgtQBIbAQ7ADhA6nqN/H/Pnj2upW7UqFF7rXvkkUfap59+6kJg27ZtXQufftcYu+zuEwBiQVcsAOSzk046yXXFli5d2p1coZ9ffvnFtdBpnJ1OnGjfvr2bEuWKK66wKlWq2OrVq5n3DsABI9gBQD5Tl6q6UnVChLpZv/32W3vwwQetRIkSlpKSYqVKlbLvv//eLdO4Op0BqxMsdu3aVdAPHUCCI9gBQD5TeHv22WfduLorr7zSzXenb6l44IEH3HKdMVumTBm76qqr3Jx36nbt2LGjLVmypKAfOoAEVyhE2z8AAIAXaLEDAADwBMEOAADAEwQ7AAAATxDsAAAAPEGwAwAA8ATBDgAAwBMEOwAAAE8Q7AAAADxBsAMAAPAEwQ4AAMATBDsAAABPEOwAAADMD/8P4go8TJ0oAIEAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.set_style('whitegrid')\n",
    "df['release_year'].hist(color='purple', edgecolor='black')\n",
    "plt.title('Release Date Movie and Show Distribution')\n",
    "plt.xlabel(\"Year\")\n",
    "plt.ylabel(\"Count\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43a839a8",
   "metadata": {},
   "source": [
    "Year 2020 has released the most movies and shows"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "392a90c1",
   "metadata": {},
   "source": [
    "### Which genres are most common in Movies vs TV Shows?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "97594ac0",
   "metadata": {},
   "outputs": [],
   "source": [
    "genre_counts = df.groupby(['type', 'genre'], observed=True).size().reset_index(name='count')\n",
    "\n",
    "genre_counts = genre_counts.sort_values(['type', 'count'], ascending=[True, False])\n",
    "\n",
    "top_genres = genre_counts.groupby('type', observed=True).head(5).reset_index(drop=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "4826b7bb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlwAAAHpCAYAAABX8+LrAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAcYdJREFUeJzt3QV4FOf3PvwT3N3d3b24OxRvKQ7FneJFWty1UFq8QHEp7i2FLxSnxVvcXVIomux73ef/zv5mN5uQBIZkd+/PdS1JVmZnZpfsnfOcecbHZrPZhIiIiIgsE8G6RRMRERERMHARERERWYyBi4iIiMhiDFxEREREFmPgIiIiIrIYAxcRERGRxRi4iIiIiCzGwEVERERkMQYuIiIiIosxcBF5qP79+0vWrFmDvDRr1szSdejdu7fL5926des7H3vnzh2ZMGGC1KxZU/Lnz6+XunXryo8//igvXrwQT3mNypcv/97LwTKwX7/66qtA79OoUSO9z/Tp0+VDwvKwXHezZs2ad/7/wGX9+vX6dcuWLYEua968eZItWza5du1aoPe5efOmfP3111KmTBnJlSuXFCtWTDp06CCHDh2y5D1B4U+ksF4BIrJGp06d5PPPP7f/PHPmTDlz5ox899139utixYpl6TqcO3dOA5NzsEuXLl2Qjzt48KB069ZN4saNK1988YV+4Pn7++v133//vWzfvl2WLFkiUaNGFXd/jZo3b/5BlhUhQgT59ddf5dWrVwH2y40bN+TPP/8UKzRs2FBKlSol7qZs2bKyfPly+8+//fabvrfw/yNx4sT26xGkhg0bJhs2bJBq1aq5XNbatWulSJEikiZNGpe3379/Xz777DNJmjSp9OrVS5InTy6PHj2SlStXSosWLWTq1KlSuXJlC7aSwhMGLiIPhV/+5g+ABAkSSJQoUSRfvnwf5fnxwX/58mX9QAnJc+KDqGfPnhrK5s+fLzFixLDfVqJECalQoYI0btxYFi5cKO3atRN3FtgHdGgUKFBAjhw5Ir///rtUqlTJ4bbNmzdL9uzZ5ezZs/KhJUuWTC/uBv8fcDFcunRJv2I/pUqVyuG++KNh1apV8vTpU/0jwAx/xPz9998yfvz4QJ9rxYoV4uvrq5Vd8x85eJ0QWBm4vAOHFIm83P/+9z+tIhUsWFCKFi2qw1K3b98OMPSCCgmG9PLkySO1atV657AgPoTevn2rH2Ah8fPPP8vDhw9lxIgRDmHLkDdvXg1xzrehWlCjRg0drkH1AkNdfn5+DkM1LVu2lNWrV0uVKlX0fp9++qkGFPO25siRQ5eFcIeqxYULF/S2nTt3Sr169SR37tx6G9bvv//+sz/25cuX8s0330jp0qV12VWrVpW5c+cGua3Ow0f4ftq0aTJ27FgpXry47us2bdrIlStX3rnfUqdOrc/r6nVB4MK+cfbvv//K6NGjpWLFirpdRrAwDB48WLfVvB9h5MiR+l558+aNyyHFD72vUF3Cc+A95fw8uB6hBxDCsSw8L6pueI5nz57J+6pfv75uq6t9i+pWnDhx9D0VmAcPHoiPj0+A/RgxYkT9/4bqlzO8F7FMbEvt2rVlz549DrfjPYEqMPYv/qBBFfno0aN625MnT/R9vGDBAvv98X8a+6pPnz7261A1xuv4ww8/6M8bN27U58L7DkOeaAm4e/duiPYVBY6Bi8iLrVu3Tlq3bq1DHJMmTZIBAwbI8ePH9QMAocesffv2Wl3CkEv69OmlR48eAT4EnIcTAeGlZMmS+sGKYPeuoa1du3bpB0PmzJkDvU+/fv2kadOm9p/xgYFw8Mknn8isWbOkSZMmMnv2bL3O7NSpU/rBjg+qGTNm6Ade165dtXJhwIcienIQKrA/MmbMqB/4nTt3lgwZMujjunTpor09GBK02Wz6uFGjRml4w7rhObCvxo0bpwEvJH766SettiAIIahgnbHM4Khevbp9WNGAZeG1cA5cCD14PbBtX375pQ45I3Sjzwj7EBBIERYwlGv+kEY/E5YXOXLkAOtgxb5CIETA3rRpk8P1CAh4nyBc4HtUmfDaY5lYh19++UWGDx8u7wuhB+9JbJsZ/qDAOuEPkKCGt/EHAPY3+uiwbgiIRvhCYHIeVkY4Qq9i9+7dNdAirOE9a/yfxB8BCLQYKh40aJD2OuI++EMEPWHx4sXTELZ//377Mg8cOKBfUQU14P8iwhnWD2Gtb9++WmnD/x289//4448g+wIpZDikSOSl8MGJX9QIQxMnTnQYmsIHNz4Y8AvYgL+g8SEGqB6g2oUPVDQBu2IMX6HBHcvHL3Z8iODDBb0z6I1xBY3H+BByhg83Z5EiRdIqDcICQiI+fADbhA8d/NyqVSt7eMN9UTkwhvLwIY7ghg8Wc4UCzcz4EAKEBOwnbDO+GjDkiYoZQifuiw86rLcRbFA5wPITJkwoIYFqCbYHYdDYH/jQffz4scSPHz/Ix6LHCKHDPKyI6hYOOEiRIoXDfbEfUDFatmyZ3g7YRuxnPD/6/xDAUqZMqWEGFTdA+EJPEsKYM6v2VfTo0fX1wbZguBmeP3+u4dJ4T2KZGApE4EI/G6qTWKY5TL9vlQsh+NatW/Z9if2MENSgQYMgH4v/I0OGDNE/ahAsAUOL+AMBw+PO73f838T/LYR9QJjD/jtx4oT9jx60ByCcG0OU2K+oUGL5qFLiZ/SkoTKHYIzAlTNnTjl9+rQGNeyrvXv36uuLMIn/m9GiRdNheiwb8H/o5MmT+roi0NH7YYWLyEuhvwofnPglbYYwgg9g56OnELAM+OWLD/S//vpL/3J3BUFmzpw5+gGAD1R8YKInCx+eRgXFFXzYOEMIwIeF8wVQkcM6YDgO9zMuxlAdhkwN6Nkx900ZvUfORz2ah0FRIcIRk87LL1y4sH7YGcvHNqJXp23btrJ48WK5fv26hgEjuIWkmmKEraDW0RUEAVQ2zENfCCnOrzHg9cWHrRG2DBhSQoUM1Q+8zvgZQ3evX7/W21HRQYDC0K4zK/cVAh7CJ95zRiUU64T1AwyB4T2Nyg8CCYICKk8f6khcPA8CPsKnuUKM6hou74IguG/fPl03fI+q8o4dO7TCPGbMGIf7IlgbYQuMnjL8wWC8duXKlXPoB8O6IcCiIoowipCHYVyjoow/KlABw/+/w4cP2wOjsc/xGuE9hvcK/kBCJQx/uKBCybD1YTBwEXkpVJwgUaJEAW7DdcYvd0OSJEkcfkY1An/5ohnYFQwpOR+9huoNKmjGcKMrCAE4hN4MHyb4q924YGjGeTvwl7k5jBkVmXv37tnviw8bM+ODxDnkmfvDjOV/++23AQIf+oOM5WMoDsOsqB5gGAvDYKgSBbWtrjivI6o1rtYxqCqXMayI50avD/qanKHyYz4az2C8H4zXFUEH90U1BAEHR4gaIceZlfsKIQ1H+RnDiviKKpYRSFGVRVDAa4cKHapOqAYhcH4ICEEIksawIvYJ9vO7qlvOry3+UEG1C8EN+7JQoUL6h4i5P825P9H5fYrnDuz/Lf5PYl+jaoVQh2HFixcv6r7H/wn8/0Ngw8EpqHYhuAGCN6pc6AXE+iAUosdu0aJFodxj5IxDikReCsMFgB4dZ6h8OQ9f4cPU/Esej0MlxliOM3zQIWDhr2QzBAHz0WHO8KGGX/yoeuCXv7nyYz6E34DnAAxhuZpuwtUHU0gYy8fwKj7gnRlHrWEYpmPHjnrBsBM+jPHBjx4Y594jKyFcoWKCgIQqDyo/robqsN5Xr151+dqD8fqjXw9N1OjbQvhDEAsscFm5r/DcqFghqGDIF9UyTNdghuoMLvhjAdUk9CKhSRxDowhr7wvhClU5hCP0PCEIYZ2Cgl4thKw6depoH5ZZ2rRpddgbt6EvK0uWLMFaD+zHwP7fml87VLkwlIjXH68jArZRXcT+wRAifjbgDyRcUOlCRQxDlugjRDUT7wF6P6xwEXkp4xeweYgEEHTQK4K/hM0wrGTAX9H46xwfZEa/hzP0Bg0dOtQ+FAU44unYsWMOv+Sd4S9rhDgcwefqCDN8gBmH8AM+DNCjgmUjlBkXVMXQM4MqyvtApQ4fWFiOefn4AEdFBQ3QGNLEkCma7Y2hPWwHhngQKD4mrBdeFwwrGs3trmAICZVEDMmaocEd+9P8AYsqFwIcwhDeF+Yg/DH3FdYDQ5bGAQ/mqRRQMTP6uWLHjq2VPjTqY0jTXOV8H/jjARU1vPexb/H8RsgMDNYT1WEcEIA+PGcYBoXghi3jtUNINf//wP8LvD7Y38b/SQwXInRj6NAIwAjgeH3w/xO9Y8Z9cWQs+tTwfxuVOFS+jIM1PvZ72FOxwkXkpVAxwCSMOBoJlQVULfCBgB4T/AWNZnMz9GKhOoWghiMPMUyBw/ADgw87LMOY3BPDIFg2whT6VgKDD2fcD0doYZ3QDI8hKawv+lPwwYVhMqPKgr/mcZQd5jLCBxDCHMIXfkYFIrDm/ODCByYatTEMhO/xQYQqDyoyeB6sGyoF+Ir1RljBcA4+SDFlQFDTBVgFYQMN3tj+wOZ3Qq8TpuBASEHlBX1Cu3fv1v2Lvh1zkMBwHapmqFoiRIfVvkIoQX8d1hvbaO5hQpDAuiE4YCgMz4vnQNXzfd8DBrwHUY1C7xZCCIbeggNVLPSSYZ/j/wK2AcOD6KXC1A0YTs2UKVOw1wOvD0IUloWhdOxHoxcOfZPmfYJ1RkUYf3wA9n3MmDG1Qocjcc33xfbgDx3830KzPZaF/6+4jd4fAxeRF8MHAH75YloFfPDiAwxDCghizv09mNMI98MvdTQJo0KB/pPA4Jc07oMj7PAhjF/8WDbm9kEFIihYLnplli5dqpUaDA2hUoaeFCx38uTJDo3KqG5gffFBjA8JBEYcAYbteNdzBQcmp8R+wrJxhCV6bFDpwTCmUe3B8NaUKVN0mzG0g0oPhqAQHD82DCviwxQVjsC2H1UM9Oeg8mSEVVSo8DjnviQMAaO6g2E8V/1gH3NfocqF8Oc8rInQgpCAyg3eBwh2eA9gSNHV9BWhhfXE/wNsi6thU1cwJQpCGh6HYIRtRiBFyBo4cGCI+sAAR91iG42pXBCsUZHEEKD5/yReY/wBYq5wofKL+5gb5o3hR7xGeE2MRnlUSrHMwNoGKGR8bMbEKERELmD6APxSx1FhzjNwExFR8LCHi4iIiMhiDFxEREREFuOQIhEREZHFWOEiIiIishgDFxEREZHFGLjII2GkHBMBcsSciIjCAwYu8kiYVBCzpWOWaW/cdpzgN7jn3vMU3rrdwG33vm331u12521n4CKP5o0VLmwzJoD0tm331u0Gbrv3bbu3brc7bzsDFxEREZHFGLiIPBBO6eGNvHW7gdvufbx1u9112zkPF3kkNMyjhytfvnx6zjIiIvIe/jZ/ieATvmpKPHk1ebQVJ/fL7edPw3o1iIjoI0kaK640yVtKwhsGLvJo9577yk3fR2G9GkRE5OXCV72NiIiIyAMxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIii3GmeS9Vvnx5uXnzpn7v4+OjJwLNmjWrdO7cWUqVCn+nRCAiInJnrHB5sYEDB8q+fftkz549snz5cilQoIC0b99e9u/fH9arRkRE5FFY4fJisWPHlsSJE+v3SZMmlb59+8r9+/dl9OjRsmHDhrBePSIiIo/BChc5+Oyzz+Tvv/+Wq1ev6hDj1KlTpWjRotKhQwe9feXKlVK1alXJlSuXXv/tt9+Kn5+f3ta/f38ZP3689OjRQ/LmzSvVq1eXM2fOyOTJk6VQoUJSunRp2bJli/25jh49Ko0bN9b75suXT9q2bSv37t3T2968eSODBg3S58ifP78+/927d8NorxAREb0fBi5ykDFjRv164cIF/frrr7/K0qVLpXfv3nLo0CEZMWKE9OrVS7Zu3apha9WqVbJr1y774xcuXChFihSR9evXS7x48aRFixby8OFDHbJE39jQoUPF399f/v33Xx2+LFGihGzcuFHmzp0r165dkx9//FGXs2TJEjl8+LDMmzdPn+P58+cyatSoMNorRERE74eBiwIMMwICjlHxypAhg2TKlElixIghI0eOlMqVK0uqVKm00pUjRw75559/7I9H5euLL76QtGnTSs2aNeXFixdaqUKQa9asmTx9+lQePHggL1++lE6dOmmTfurUqaVgwYK6XGNZN27ckKhRo0rKlCn1sWPGjJF27dqF0V4hIiJ6P+zhIgfPnj3Tr7FixdKvCDzmMBUtWjSZNm2aVsDOnz+vQ48lS5a03wdBzID7JkqUSL8CAhS8fv1a71enTh1ZsGCBnD171r48NO4bQW/Tpk26bFTMKlasKPXq1ftIe4GIiOjDYoWLHCD0QObMmR1CEuzdu1dDDypUmDoCwcsISIZIkRwzfIQIrt9i6MeqXbu2/PHHH5IzZ049YrJVq1b22/H8u3fv1p4wNPZPmjRJWrduLTab7YNuLxER0cfAChc5WL16tQYgDPM5Q8N8/fr1tQ8L3r59q31XxYoVC/Hz7NixQ+LGjSs//PCD/bpFixbZA9W6deskSpQo2nhfrVo1OXHihFa90A+GqhkREZE7YeDyYmhcxzQQCDmPHz/W5vTNmzdro7oraII/fvy4VsFQuUJYwuMxRBhSWNatW7fkwIEDOryIoxe3b98uuXPntq/brFmzJH78+Ho7pqlIliyZ/kxERORuGLi8GI76wwUzzSdIkEAb4NFThSkcXOnSpYsMGDBAK03o8SpTpoxO64AerJBC1QpHIXbr1k2fH0GrX79+Mn36dA1wTZo0kTt37kifPn200R79Y99//71EjBjxA2w5ERHRx+VjY1MMeSDMDYZhyH0v78g134dhvTpERPSRpIyTQHqVqCnhDZvmiYiIiCzGwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFONM8ebQkMeOIn3BuXyIib5E0VlwJjxi4yKM1yl2cpwMiIvIy/jZ/ieATvgbxwtfaEFlwih9v3OYzZ8543bZ763YDt937tt1btzu42x7ewhaEvzUiovf24sUL8Ubeut3Abfc+3rrd7rrtDFxEREREFmPgIiIiIrIYAxcRERGRxRi4iIiIiCzGwEXkgaJHjy7eyFu3G7jt3sdbt9tdt93HZrNxVkjyODhc+MSJE5IvXz7Ow0VE5MH8w+GcW65w4lPyaCtO7pfbz5+G9WoQEZFFs8o3yVtK3AEDF3m0e8995abvo7BeDSIi8nLhvwZHRERE5OYYuIiIiIgsxsBFREREZDEGLiIiIiKLMXARERERWYyBi4iIiMhiDFxEREREFmPgIiIiIrIYAxcRERGRxTwmcDVr1kymT58erPu+fv1aVqxYIWHl4cOHsmXLFvvPWbNmlYMHD1r+vP3799eLK9h3WI8BAwYEuA2n2yxZsqTe/r7WrFkj5cuXf+/lEBERuROPCVwhsWnTJpk1a1aYPf+ECRNkz5499p/37dsn+fPnl7AWOXJkXS9/f3+H63ES6AcPHnyQ56hevbqsWrXqgyyLiIjIXXhl4ELFJjw9f+LEiSVKlCgS1nLkyCEvXrzQgGW2c+dOyZcv3wd5jmjRokmCBAk+yLKIiIjchUcGLgxbYYhx2rRpUrRoUSlUqJCMHj1agw6G7jBsdvPmTR0iu3Hjhl4/Y8YMHTbDfTt06CC3bt2yLw/3mzp1qi4LtwW1fGPIEj+XKlVKcubMqUNoy5cvtw/drV27Vi/G0Jp5SPHVq1cyfvx4KVOmjIYcPN/t27f1Nqwr7rt9+3apWLGi5M6dW9q3by9Pnjyxr+vKlSulatWqkitXLl23b7/9Vvz8/IK136JGjar7YPfu3QECF57P7M6dO9K9e3cpUqSIPs+IESN0u1Edw3avXr3afl/sl9KlS8svv/wSYEjx77//1n2ZJ08eqVKliixZssR+m6+vr3Tt2lX3b+HChaV3797y7NmzYG0LERFReOKRgQuOHz8uly9flqVLl8rgwYPlp59+kv379+vQ3cCBAyVZsmQ6lJc8eXJZvHixbNiwQSZOnKjBKGHChNK6dWt58+aNfXm//vqrLgsf+kEtH3788Uf57bffNFxt3bpV6tSpI8OHD9dhOSy3WrVqenE1tDZ06FDZsWOHjB07VpYtWyZv376VTp06OQzzYTh00qRJut4nT56U+fPn6/WHDh3S4NOrVy99XoQtPMeuXbuCvd8qVKjgELguXLggL1++1ABnQLBq0aKFVsMWLVokU6ZM0e0dN26cRIgQQQMftsGAihlCIZZthuW2bdtWChYsKOvXr5d+/frJzJkzZd26dXo7Au39+/d1H2P/njt3Tm8nIiJyNx4buFDVQcjJkCGDfPrpp5ItWzYNJxi6ix07tkSMGFGH8vB1zpw50rdvX63UZMyYUYYNGyZPnz6VvXv32pf32Wef6bIyZcoU5PIB348cOVIrVKlTp9YqFcLblStXJGbMmDqs5mpoDc+JKtCQIUOkWLFiuhz0eyHY/e9//7Pfr1u3bloRyps3r9SqVcv+vDFixNDnrVy5sqRKlUqDD4YJ//nnn2DvN1TWsJ5Xr161V7cQlHx8fOz3wX65e/euVuJQcfvkk090nRGMnj9/LjVq1ND1NapR27Zt0+XGihXL4bkQchFue/ToIenSpdPKF/YVwhWgCon9hW3Jnj27Vhnr168fgncBERFR+BBJPBQ+yM0f8Pge1SJnCAgYHuvZs6dWZ8zVFwQPQ8qUKYO9fAy/IXCMGTNGLl26JGfOnNHr3zW0h+dDJQtByhAvXjxJnz69XLx4Ub9C2rRpHZ7XqMShCoUgh8oQKlPnz5/X4IRhwuCKHz++VpxQ5WrVqpUGrq+++srhPlgXBKS4ceParytQoIBu/7Vr1zRoIsyiAR/hC0Ogffr0CfBc2DeoWpkPGMA+QgiG5s2ba3UPgQ4XDDkiYBIREbkbjw1crprQXTXLGyEI1RMj0BjMgQL9TcFd/uTJk7WXql69ejqciGHC4EyF4Pwc5nU0DyniaEJXUHnq3LmzPif6qPA9hhVDChUtDEPiiMLr169r/9TRo0eDXE9jPxpf8VhUthAOHz9+LGXLlg3wGAQ0ozrmCm5DaMO6YMgS98MwMKp+RERE7sRjhxSDYh4eixMnjlar0CuEcIAL+rowXIahvNBA7xX6utDvheCBXidzIDM/vxmGHyNFiuRwlCDCCqpUzmHQFYQ8DLlhSLRhw4Y6PIqKU0iPykTgOnbsmDb2IyhhncywLqjGmZv1sc64X5o0afRnY1gRoQthM3r06AGeB8vBPsaQobHvsRz0hcGCBQvk9OnTUrduXQ3EOBAB1TIiIiJ345WBCx/+6JdCaECVpWXLltr4jWE0XDdo0CANHOjPCg0MA6LJHtWhI0eOaH+Y0WxuPD/6k9AHZYZ+JQQl9IbhqEUMt2EoDg3+JUqUCNbzopkfQ4no28IkpwiSxvMGF4Ifth3N/5UqVQpwO9YF98F24bn++OMPXeeaNWtqgAX0XCVJkkQb+3GAgCu1a9fWoVtUrjBMiWoWetAQgAFDvQiPCGF4XRDe0JNGRETkbrwycKEhHdUU9AOdPXtW2rRpIw0aNNAPfgzHYUqIuXPnOgwphsSoUaN0uajyYAoKNK+jyR3XAZrsUdlB4HCuPuFIveLFi2tjfOPGjXX4DpWe4MzT1aVLFw0raPBH/xUei2UYzxsSqEpheNBV0EOPlXG0YKNGjfSoSFTFEI7MUN3DfTElhCvoP5s9e7aGKex3BN0mTZroVBeAaSfQG9axY0fdZ//9959WHomIiNyNjy2sZwElsgDCIipj+17ekWu+D8N6dYiIyAIp4ySQXiVqijvwygoXERER0cfEwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFPPbk1USQJGYc8RPO7UtE5ImSxgrdGWHCAgMXebRGuYvr6YWIiMgz+dv8JYJP+B+wC/9rSPSep/jxNtjmM2fOeN22e+t2A7fd+7bdW7fb1ba7Q9gC91hLIgqRFy9eiDfy1u0Gbrv38dbtdtdtZ+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iDxQ9enTxRt663d6+7UTugPNwkUfzxjm4sM05cuQQb+Ot2+3O2+4u8ycRfQgMXOTRVpzcL7efPw3r1SAiFzOEN8lbKqxXg+ijYeAij3bvua/c9H0U1qtBRERejrVcIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4P8PTpUxkzZoyUL19e8ubNK9WqVZMFCxaIv79/WK+arFmzRtcLDh48KFmzZg3rVSIiIvroONO8m3v8+LF89tlnkiRJEhk5cqSkSpVKTp48KcOHD5fr16/L4MGDJbzInz+/7Nu3L6xXg4iI6KNj4HJzEydOlChRosjcuXMlatSoel3q1KklWrRo0qlTJ2natKmkT59ewgOsZ+LEicN6NYiIiD46Dim6sdevX8umTZukSZMm9rBlKFeunA4rpkyZUoccUekqXry4FCxYUPr06aPXGcN8GPJbtWqVlChRQgoXLiyzZ8+Ww4cPS9WqVbUq1bdvX/vwpM1mkxkzZkjJkiWlUKFC0qFDB7l165b9ee/evStffvml5MuXT+rWrSvXrl2z3+Y8pHj79m19PIZBsQ7fffed+Pn56W1v3ryRQYMGSdGiRXUdcD8sm4iIyB0xcLkxhJn//vtPcufOHeA2Hx8fKVasmFaVunTpImfPnpVZs2bJ/Pnz5eLFi9K/f3/7fe/duyc7d+6URYsWabCZNGmSjBo1SvvC8P3mzZtl165det/FixfLhg0btLK2fPlySZgwobRu3VoDEnTv3l3D2cqVK6Vt27aycOFCl+uO4Ib1wuPXrl0ro0eP1uViHWHJkiUa+ubNm6dh8Pnz57pORERE7ohDim7M19dXv8aOHTvQ+5w7d04OHTokW7dutQ8tjh8/XqpXry6XLl3SnxGW+vXrp7enSJFCxo0bp1UzVKkge/bs9vvOmTNHhg4dqpUnGDZsmFa79u7dq0OZx48fl19//VWXkzlzZjl16pQ+t7M//vhDK2MIZhEiRJAMGTLoOgwYMEA6d+4sN27c0KodKnTx4sXT8PfkyRML9iIREZH1GLjcGIIIGMODriAoxYkTx6GPK2PGjBI3bly9zQhrCEuA3i9A0DHgOgxfosp0584d6dmzp4Ykw8uXL+XKlSvy6tUrXSeELQOqb64CF6psCFAY4jSgMoZlGQcCYLgUYa5IkSJSsWJFqVevXqj3FRERUVhi4HJjadKk0cB0+vRpyZMnT4DbO3bsKPXr13f5WPRKGf1SECmS41vBHKjMj4GpU6cGaMRHgDtw4IAOFZpFjhzZ5fO/fftWq1ozZ84McBu2KX78+LJ792757bff9IKhzY0bN+pQI4ZLiYiI3Al7uNwYQhKGBhFCUIEyQ1jBJV26dDr0aAwJwoULF+TZs2chPnoRlTL0XN2/f1/Spk2rl+TJk+sQ5eXLlyVLlixabbt69ar9MegdcwXPjSHFBAkS2JeFYcRp06ZpoFq3bp0OTWJOsbFjx+pQ5tGjR+Xhw4ch3k9ERERhjYHLzXXt2lXDU5s2bbRXC4306ItCU3zz5s0lU6ZMUrp0ae2P+uuvv/SC73E0IgJSSLVs2VKmTJmiYQ7DiDiS8NixY1qtwlDlJ598IgMHDtTeMTTio8neFQwVYtgSR0yeP39ejhw5okdSRo8eXSJGjCj//vuvziuGqhnmE0NDfbJkybTyRURE5G44pOjmMK/V0qVLZfr06dK7d2/ti8JQY7du3aRx48Z6H1SIRowYoWEJYaZChQranB4aCHbo5RoyZIgGvVy5cukcYBhShMmTJ2tw+vzzz7WXq1mzZjrbvDOsx/fff68TtDZq1EhixIih01AgDAKa9tEvZkxhgefB/fE4IiIid+Njc266IfIA6Dc7ceKE7Ht5R675chiSKLxJGSeB9CpR84P9X8dR1d70B5m3brc7bzuHFImIiIgsxsBFREREZDEGLiIiIiKLMXARERERWYyBi4iIiMhiDFxEREREFmPgIiIiIrIYAxcRERGRxTjTPHm0JDHjiJ9wbl+i8CZprP93dgoib8HARR6tUe7ibjUTMZE38bf5SwQfDrSQd+A7nTz+FBDeuM1nzpzxum331u12521n2CJvwnc7kQd68eKFeCNv3W5v33Yid8DARURERGQxBi4iIiIiizFwEREREVmMgYuIiIjIYgxcRB4oevTo4o28dbuJKPzjPFzk0bxxDi5sc44cOcTbfIjt5rxQRGQVBi7yaCtO7pfbz5+G9WqQm8x83iRvqbBeDSLyUAxc5NHuPfeVm76Pwno1iIjIy7F2TkRERGQxBi4iIiIiizFwEREREVmMgYuIiIjIYgxcRERERBZj4CIiIiKyGAMXERERkcUYuIiIiIgsxsBFREREZDGvClxr1qyRrFmzysqVK4P9mOvXr8uePXv0+xs3bujj8dUKfn5+MmLECClSpIhUqlRJ9u3bF6zHTZ8+XdfrwIEDwdoH5cuXF6s9e/ZM1q1bZ/nzEBERuQOvClybNm2SNGnSyC+//BLsxwwcOFD++usv/T558uQagvDVCqtWrZLdu3fLTz/9JLVr15avvvpKQ9i7bNy4UbcrPAWcBQsWyOrVq8N6NYiIiMIFrwlcDx8+1ApQ586d5ciRI1q5CqmIESNK4sSJ9asV/vnnH61UZcuWTSpUqCBPnjwRX1/fIB9z+vRpuXbtmnTs2FG2b98uz58/l/DAZrOF9SoQERGFG14TuLZu3SqxY8fWylGSJEkcqlz//fefDBkyRIoWLaqXwYMHy6tXr6R///5y6NAh+e6776RZs2YBhhSfPn2q9y1evLgULFhQ+vTpo9fBwYMHdeju559/llKlSkm+fPn09tevXwe6jnju33//XY4ePSpz5syRYsWKSfz48d9Z3UJAq1Klirx580ZDl9ndu3flyy+/1OevW7euhjNDo0aNZNq0aQ73//zzz2XmzJn6/d9//63bnSdPHl3+kiVLHIYxUYEbOnSoFChQQD755BOZPXu2fdgS+wz7DvsLsC9wvQH7x7jN2K8zZsyQwoULy7Bhw/T6HTt2SPXq1SVv3rzSoEEDXR4REZE7iuBNw4lly5aVCBEi6Ic/ht+MKsygQYM05CBozJs3T7+fMmWKfP3115I/f35p3bq1BgxnXbp0kbNnz8qsWbNk/vz5cvHiRQ1phnv37sm2bds0POHxCENBDfuhbyt37tzSpEkTefToka5DULD+W7ZskXLlyknMmDE19Kxdu9bhPt27dxd/f3/tW2vbtq0sXLjQfhvCDEKNOZydOHFCatSoIS9fvtT7I0iuX79e+vXrp/vHvP7YtqhRo+pztmnTRiZMmCCXL1/W5WKfYd8Ftw8Njh07psOQzZs3l3PnzulzonKH50dQxvpcvXo12MsjIiIKL7wicN2+fVs/zCtWrKg/V65cWYcUEaxQkUL1CxUuhIucOXNqhSVFihRaEYscObLEiBFD4sWL57BMBAJUXMaPH68VIFzwPXqwLl26pPdBxQlhDtUbVLlwOXnypMt1RChCtQiPTZQokT43qluovgUG649tM28X1unmzZv2Icrjx49rI37mzJk1CDVu3Nj++GrVqsmFCxfkypUr+jMCYY4cOSRt2rSyYcMGSZgwofTo0UPSpUunIbVDhw7aX2bAPkEowv1RRcPPp06dkmjRouk+w77DEGxwtWjRQnvR8Hxz587VClytWrV0+QhhpUuXlqVLlwZ7eUREROFFJPGS6hYqMSVLltSfcRRg3LhxtTLz2WefaWM6gpahUKFCegkKglGcOHEkffr09usyZsyoy8VtCEyAsGCIFSuWvH371uXyUAVDWEOFB5UmBAwMR2KIEcFr9OjRLrcrZcqUGpIAfV8Ijhgu7dSpk4YphCCERwMqaAiYkDRpUt1OBK127drpV4QyY/sQKlGlMmA/mfvXUqVK5fAzqmyBbV9wYFsMqBaierd8+XL7dQiwxmtIRETkTrwmcGGIDBUsc3hA8EBvUGhEiRLF5fVYrvnIQuf7BdZMvnnzZmnZsqWkTp1aL6gsjRkzRu8/duxYl8+D9X/8+LE9cBmVMiNwuXo+VJ3MELBwdGT9+vW1CojnBAQnDFEiwAXGeVlBbZ+r9XeGUGy+HUOIderUcbgPqmdERETuxuOHFNFTdObMGR3aQ/+RcZk8ebLOFYWeIFRpUM0x7Ny5UxvMg4LKFo4gNIYPARUlLNNc9QouBAn0bRkQNlCZQoBB87wzHHGJ+6Pp3bxd6CHDECHCU5YsWXTI1Nz3hJ4zMzTDnz9/Xnu8UP0yqkzYBuw7VLFQpcMF/V2LFi0K1vb4+PgECGfmIyjfdZQonh/N9MZz44JqFyp+RERE7iaCN1S3MKyGoUMEEOOCyk6mTJm0VwlVlJEjR+p8W+ixQhgzQg56kRBgMK2EGYYP0VOEHiY8Dhd8j6PssPyQQqUNQ4iodOH5UGnCc2LOr65du2qQc94u9GWhb8u8XV988YVuL8IX1hFVKswlhkCJILl48WKH5SRIkECPjvzhhx+0p8uAJnVUBVHhwvAeJn/FPkJfV3BEjx5dDxowjuhEmEMlDUc+4ghFHJwQFFT7sC/QM4YjKzGvFy7o7yIiInI3XhG40HjtaggQDeT79+/XubkwtUKrVq20soQA0rNnT71Pw4YNZe/evdoU7gxDfRj+QzjAUXoIQJjaIDQQuHBEHnq1EHZQiUI4QjBB4zzCiwFTS+DoQlfDoRiWq1evnvY/YWoLhEf0gGG6h0mTJuk0D86MoxLNgQv9ZpjmAeEPgRQVQhw92b59+2BtD464xPAmlo3giCFS9Lxh3RDccPRkUDCNxbhx4zSEIhyvWLFCJk6cqIGWiIjI3fjYOENluIeXyHmIjoKGHjAMge57eUeu+TpWJ4lcSRkngfQqUVPc+f2OP1Ssmpg5vPLWbffW7Xbnbff4CpcnYNgiIiJybwxcRERERBZj4CIiIiKyGAMXERERkcUYuIiIiIgsxsBFREREZDEGLiIiIiKLMXARERERWcwrTl5N3itJzDjiJ5zbl94taay4Yb0KROTBGLjIozXKXdytZiKmsOVv85cIPiz8E9GHx98s5PGngPDGbT5z5ozXbfuH2G6GLSKyCn+7EHmgFy9eiDfy1u0movCPgYuIiIjIYgxcRERERBZj4CIiIiKyGAMXERERkcUYuIg8UPTo0cUbeet2E1H4x3m4yKN54xxc2OYcOXKIt28359QiovCEgYs82oqT++X286dhvRoUBrPGN8lbKqxXg4jIjoGLPNq9575y0/dRWK8GERF5OdbbiYiIiCzGwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILOYRgatZs2Yyffr0UD8+a9ascvDgQQlv1qxZI+XLl/8gy3r27JmsW7cu0NvxPNgPhw8fDnDb77//rrf1798/zF8rIiIid+QRgYvebcGCBbJ69eog7xM5cmTZvXt3gOt37twpPj4+H2Q9ELZat279QZZFRETkLhi4vITNZnvnfQoVKhQgcOFxuC5fvnwfZD3ixYsnMWPG/CDLIiIichceF7gwDIdhq2nTpknRokU1RIwePdohcHz33XfyySef6O0rV650ePzr169lxIgRehsuvXv3lidPnuhtN27c0KG1DRs2SKlSpXTZuO/bt2/tj9+xY4dUr15d8ubNKw0aNJBDhw7Zb8N6ff/999KmTRvJkyePVKlSRfbu3Wu//e7du/Lll19quKlbt65cu3bNYd3+/vtvXYbx2CVLljhUjr766isZOnSoFChQQLdv9uzZ9n2Cbca6YP0DU7ZsWd3Gixcv2q87ceKExI0bV9KlS+dw319//VXXEeuC7d2+fbt9+BHb/uLFC/t99+3bp+v08uXLAEOKy5Yt0+HM/Pnz623nz5+333bgwAH59NNPJXfu3FKhQgW9LxERkTvyuMAFx48fl8uXL8vSpUtl8ODB8tNPP8n+/fv1tuXLl+vPo0aNcjnMNmnSJDl16pSGFdwPvU/du3d3uA/Cy+TJk/UrgoYRIM6dOyf9+vWTjh07yvr166V27drStm1buXr1qv2xs2bNkho1asjGjRslW7Zsun7+/v56G54H3yME4nELFy60Pw5hBdcVLFhQl43nmTlzpkNf1rZt2yRq1Kiydu1aDXUTJkzQ/YBAhGE8hBqEn8DEiRNHl2+uciFAVqxY0eF+CEJdu3bVMPTLL79Iw4YNpWfPnrrfihcvLtGjR9fgZcA+QqiKFi2aw3LwPNiH2AdYZzx38+bN5enTp+Ln5yc9evSQqlWrypYtW3TffPvtt3LhwoV3vv5EREThjUcGLnxYDx8+XDJkyKChAMHm5MmTetuKFSukRYsWUq5cOcmePbtWqAyoyixevFg/2FG5QTVo3LhxWhkyV1769Omj1a1ixYppEMAyUUGbO3euNGrUSGrVqiVp06bV8FC6dGkNfoYyZcpIvXr1JE2aNBrMbt++Lffv35d//vlHgyLWJ3PmzBqSGjdubH8cqmoJEybUEIJqEwJMhw4dNBSah+sQxPDcqJThZ4QgBJ0YMWJoj1bixImD3HeoJJkD165duwIELlTWUGFr2bKlpE+fXlq1aiWVK1eWefPmSaRIkfR7o+KF1wI9YNgeZ3PmzJH27dvra4FtwralTJlSA+W///6rlcVEiRJJqlSpNLzOnz//netPREQUHkUSD4RgEitWLPvP+N4Y9sNwWefOne23ZcqUScMIXL9+Xd68eSOff/65w/JQdbpy5YrkzJlTf8bwmCFXrlzy6NEjefz4sS4b1RhU0QxYXsmSJe0/m4fmjHXEuqFyg4CUIkUK++0YStu6dat+f+nSJa2goUplQJiJGDGi/WcEE/PP6JUyD3cGBwLX2LFjdZtwefXqla6HGbbTeR9hvYxqISp4nTp10uFZhEjnfWBezvjx47WqaMDzYV9jXyBwDho0SCt5CGX169fX4U0iIiJ345GBK0qUKAGuM/dwOTeQoypjBBj4+eef7SHMHOKMXi5UigzGcCCO4sPjMexXp04dh8eah9LMj3VeH+f1Mt8XwQl9WUOGDAl0u4NadnAhtCGE/vbbb3Lv3r0A1S3AsKUz7AdjXxQuXFj3H4Zx0aOGZbh6TbC/Bg4cqNtlZgTRb775Rpo0aaIVMlwQZBG+UCUkIiJyJx45pBgUDNcZw4uAJnFfX1/9PnXq1FohQrDCsBwu+PBH0/3Dhw/tjzl79qz9ewzZJUmSROLHj6/Da1ie8VhcEBLM/UyByZIli/Yumfu9zM+DZaMfC4HIWDYa2hctWhSs7Q7JtA6ociFwuRpONNblzz//dLgOlSxcDxEiRNDeK2MZqHi5gvvfuXPHYX+hxw3bhWFWDO3iOgy9onqGIVxX01YQERF5bOBCnw16kdDLhKG4kSNHyo8//ijhXdOmTbXvCQ3mOOrv66+/1oAACFdoAEdlBROhYpivb9++GoIQdAzYVoQ2VHCmTp2qVRhAT9PmzZt1+TjCEE35uDgf4edKxowZtdKDig+GDlHRQT+ZAT1MaJxHhQtDcXv27NH1QOUtONDIjooVAmFwAhcqU3hdUa1yhu3E/kNTP4b/sI1orjf3nCFkoaEeQ4QISq6g9wvLQOM/9heGFzEki32BoUMsEwc34DZMyIr9kiNHjmBtLxERfVwoEhw7diysV8OzAheG3NBMjsCF/hyjlwlN4zjqLDxDE323bt20qf6LL76QEiVK6NF5BsymjuCD+6ABHsONCJLm3ig0gKPZu1evXhrQ2rVrp9djOgfsF+wf3AfN9BMnTnQZWlzBkY+olKE/Cn1NmCbBgDCIIycRcDBkid4mBD2sR3BUqlRJh/wQhMzVOlfwWmKfYJoI83YbMO0DthMHA9SsWVOrT1OmTHEYGsS+wLaggd4YsnWGfYSjGzGFB5aDox8xbQYCKoYgMXyIkIWwiYZ6TLOB/U1EROEP+qPxGUWu+dhC2uQjItWqVdOj4fCBjGZpVLswHIeqCyow+OqJUB1C9QfDZOaKF4U/6A/D0OS+l3fkmm/QAZM8T8o4CaRXiZribe93/KHj6o8kT+at2x4etxtHz3fp0kWLMd627ZZVuG7duqXDPs4QuozGciIiIvIOGJG5efOmDBgwQNtFzFMuQYcOHXQkBO06mC4JrTeYXBxzN2JkwyyoCbHdWagCF4aUnE+EjEIZ5mHC/FVERETkPTABeLJkybQPGaNfmIvRGEDDvIr79u2zH0CFthZkCGSGYcOG6ZyMaMF514TYXhm40D+Evh3Mi4S5lnA0GXqEcFQadranwjAikjaHE4mIiP4P5k7E8F7s2LH1tG+Yx9FooMdBYOnTp9dZAoxpjnBAFOa2xJHwmIzcOHVbUBNie+U8XJjCAEepYfZzHDGH8VT0NqG5mScmJiIi8l446ArDhpi4GxUqHH1e3XS2EczTiDPAmA/UQrXrXRNie2XgQkMc5qbCUWNEREREZjjyHGctwXl3MYXSoEGD7Lc5H7mOI+iNuSLfNSG21w0pYj4ndzoygIiIiD4eNL1jUnFMF4XzEqdJk8Z+G643zwmJeS1xn3dNiO2VFS7MA4WTI2MIEWOrzqd6cT61DREREXk2DBXivL+YrQA9XWg1mj9/vvZhOUNTPI5oxBlUcMYU9IIDjnDEhOTo38J5i3G2FgxJBnfOSY8LXJhNHbOzb9y4McBtKAsycFF4kSRmHPGTEE81R24uaSye5JzoY8PZRiZMmKD9VjjSEH1byAnm/i0Derww+ThCGiYRr1Wrll6P+z548EAnxMZXnNvXmBDbKwMXz2dH7qJR7uIc/vZS/jZ/ieDjdaeLJQozOPuJcao7QGDC6f8wXYQzVLJwcQXTQODiaUIVuODZs2d6rkEc3mmerB4VLuxgovAADZjeFriwzZi+BD0R3rTtztvNsEUUNnD+4VOnTmllytVworcKVeDCSYlxgucXL14EuA2BCyewJKKw4+r/pjfw1u0mCk/QEI8+LPRwGUOFFMrAhZMs4yTCOMGzJxyqSURERB9GiRIlAj2qsGjRoh5zqp6QClXNHUcgYHyVYYuIiIjIosCFKfdxniQiIiIismhIMWnSpDqsiLkxMClZ5MiRHW7HLPRERERE9B6BC2ftxrT9RERERGRR4GIFi4iIiCj4Qj1RzdGjR/UoxU8//VRu374tP/74o2zatCm0iyOyREjnobL5+1u2LkRE5L1CVeFCwzzOgdSoUSP57bffdPJTnP27f//+OtyI6fqJwgPfX1eJ7fGdYN03YvwkErdiY8vXiYjoQ0D/tE8En3B99gbjpNS//vqrpEiRwuG2pUuX6pyeXbp0ka5du773ybKxnHr16olHBS6cIwk7CROaLVu2TK9r3bq1JE6cWM9/xMBF4YXfk/vi/+BmWK8GEdEHh0IHAtCSP/fK3WdPLT8/aZO8pUIdDHfv3i1NmzZ1uH7nzp06WfqHsGrVKj0vY3gWKbTT9ufLly/A9Xny5JG7d+9+iPUiIiKiYEDYuun7SMIrnO5vt1PgwukBjx8/Ljly5Pggz5EgQQLxyB4unL177969Aa5fu3at3kZEREQEOMXPoUOHNGQZ0I6EIBYzZkyH+65Zs0aqVaumBRwMDx4+fNg+/IhhQ7MVK1ZI5cqV9XvchscCzu88Y8YMKVmypD5Hhw4d5NatW+KWgQv9W5MmTdKm+Tdv3sisWbP0DOHz58+XPn36fPi1JCIiIreUJUsWnb/z999/t1+3Y8cOqVixosP9EJiGDx8u7du3l3Xr1knx4sWlXbt2OnJWpUoV/YqTYpuXgXDmbPHixbJhwwaZOHGiLF++XBImTKhtT8grbhe4kBi3bt0qGTNm1FSJRvkCBQroRKiffPLJh19LIiIicusq1+7du/X7169fy//+9z+9zmzRokXSrFkzqVOnjmTIkEF69+6tYQ0BCkOGxYoVs5/lBtWygwcPSvXq1QM815w5c6Rv37563kbklGHDhmlOcTUyF24D182bN2XEiBG6sxIlSqTp8vTp03LmzBnZvHmzNswTERERmVWoUEEDD2Y1OHDggAYpVJ7MLl68qEOJZugXx/VQo0YNe+DC1FQ4041xFKTh+fPncufOHenZs6fkz59fLygS4RzQV65cEbdomr9w4YJ8/vnnujN8fX01cCGAde7cWXcaNhBHL2I81XmclYiIiLxXwYIF7UEJRydWqlQpwH2iRo0a4Do/Pz/x///nR8Rjhg4dKv/884/2hLkaTsT9YerUqZI+fXqH2+LGjStuUeFC9QobO2/ePA1bBoyr1q1bVzp27KgNbmhsIyIiIjJPYVGmTBkdVsScXM79W4CA9Oeffzpch5+N4BQ7dmwpVaqUtjShl8vVcGKcOHG0CHT//n2tgOGSPHlyGT9+vFy+fFncosKFNImwFZSGDRtK27ZtP8R6ERERUTDnyHKH56hQoYIedJc6dWq9OGvZsqV8/fXX2neVN29eWb16tZw7d07GjBljvw+GFQcNGqSTqKZLl87l82A5U6ZM0eCFXrCZM2fKsWPHZOTIkeIWgevFixcSP358h+uwEUmSJLH/jKY29HcFF5rjihQpEqwZZrFcHLWA2e3DwsOHDx1KmBg3/umnn7Qpz0qYvR/MbzjjaA68cQPTqlUrrTbizetqn+ENiyM+Zs+eHeA2NCOiHLtt2zZ59OiRvrFr166tR4tEiRLlo24/ERG5hn4ozP4e2glJP8ZM82YlS5bUdXZV3QJUrB48eKAjaqhQZc+eXQs9CGCGcuXK6bQPQR2g16ZNG+3lGjJkiH6e5cqVS+bOnRvmQ4rBDlz40D1//ryW5gzOG4wGepTvrIDzNGL6ibAKXBMmTNAX2Qhc+/btC9MXD29MlFYB57JEdXHlypX21wcz7uJ6NBg67zO84XHAw8CBAwMNeWgwxF8ICNT4CwNHeTx+/FgGDx78EbaOiIjeBdMc2PxtIiE7ZWyohSZsITcYYsaMKX/99VeAIxPNmjdvrpfA4LMNfWAnTpxwuN44AtI4hy6a5nEJT4IduNCrNXr0aO32jxUrVoDbkSbRNI/DOa2AsBOWnJ8fpzEKS9GiRdMLvHr1yl5hNK9XzZo19Q3377//6ti3AUeI4DGu/srAfdHQiEls8dcFpEqVyv7XAipmESKE/i8cIiIibxTsT05MRIYPeFRWFixYoCn12rVr2riGhPrpp59qem3RokWoVgRDZBhiRCkRw1QIdgh4CDqYawPDZzgqEkNZN27ceOdMsrgfhsWwLNwW1PKNIUv8jKpRzpw59UhLTJgG06dP1wCCi3EEJpaP9QKEFzTkoSEQh7Di+VBdAqwr7otKEwJO7ty5dV+igmRAZapq1apa9sS6ffvtt/YjLd4H1gevmTn5A+ZLQ1nWeYZfwHmtcNm/f7/D9Tj6FNtvPu/VkSNH9Hya2CacsgGvjwGH8aKsi/nZsE8RxnGkCaYQwakcEOwAw5rYPxirN+BoWOwTHA2L4Wa8VoULF9Y5WcwzFRMREXlc4IoePbr2BKFq8uOPP+owFapeDRo00OCD7xHEcCRCaOG8SjiKAM+DoSv0COGDH/NoYPgrWbJkOpSHYbPgzCSLIyGwLHxQB7V8wDbhVAMIVzgCApU6zHiL8WQsF0OJuOAEmc5wmCqG6MaOHasn88aQXadOneyHsgKGQzE7P9b75MmTOis/oC8Mc5v16tVLnxdhC8+xa9cueV/ot8KRpca8JYD9g2XjdXQF1UscdTpu3DgNgQihe/bs0RItmg/NgQuhCL1gWF9MKodhV0DfF05gjuFI3Af7B9uN/Y2qWbx48TSsGduPZaKhERCosH8Q0oxxfLxeeCyGNtE3SERE5G5ClI4wdorZW3H6HlS30NODQzDRt4UP5PeFqg5CDj708eGOAIcP3xIlSuiQGJ7DGDLDTLL4IDeattFjhGoXJlYzqlCfffaZLgdQkQtq+dmyZdNZbI2TcqNKhSCJidJQYTGG75xPkImg8csvv2jzOR4PCB5ly5bVmXSNw1lxGiRjQjdUhfC8xj7FkRPG+aAwfIcwhnlGjOveB54LU3b8999/+lxGwCxdunSgj0EARDBC1Qn7CBdMBYL1xHYZsFxj/yN4I2zCxo0bNaBjXyOAo+ERwQn7E0eP4HQNCFqosuE8WVgXI3D98ccfus8QrlExQxUO+wTLQ8WSiIjIHYWqGQcVCYQshBMElw8RtgBVKnN/GL5HtchZcGeSTZkyZbCXj+E+DA3iaEAcjWeEtncN7eH5UMnCIawGVHAQGozZccF8MAGe16jEYRgRYQ/VHIQyVAox74i5OvY+EIgQVo1zWKGKhueIHDlyoI9BjxaGX3FUKB6HAIYDBLB+GAI0pEmTxv49nsPoJcN2Y1jWXO3Ea4TQhWFCBGNjOBaVLhxRefXqVa2Mob/MOBgAjZMIYjg4A+EOITWww4CJiIjCs3DV/WxMOfCuZnnzTLIIBcYFYQKTrwY2a21Qy588ebJW7hASMJxo9G+9i6uZcY11NIemwAIOKnJYZwxdGsNo6Hv6UBCGMTSIIU+EPDTEBzacCAhC33//vf1nnHAUR0D+/PPPDkN/EFjzvKt9YuwL7BdUFHHkCkIWgjOmBsmUKZMO+ZoDF4IWhjNRycRrh6b9fv36vdf+ICIiEm8PXEEx9w5ZMZMshsPQ14V+LxwYgHnHzIHM/PxmmLwNIc18iCqGWhEmnE8r4Ap6nOrXr69Dogg2GH7DcO2HPCoTAQvBBcOJGFZEA3pgMESKPinsWzM8DuHNeUjVFWw3pggx99MhTOGxqP5hWBgBC8PCqJJiuahQYuoPHGyA7wFDmVgOesoQrtFPZu5HIyIichduE7jQw4MwgCE8DAMaM8niCDxch+ZtVF+Mnq2QQhBAk/3169d1mAu9amBM5IrnR0+ReUgN0GOEoIR+JVSH0NiNShl6kFDJCc7zIoyg4oO+LcyBhbATkglk3wWhBs+DKh7CZGDhEdBXhdCHYT7sWxxlif3x1VdfaZAKKqyZ+8aw/qhIYXgRVTUcjNC4cWP7c2Pf4KhHo5qHkIUToKPaZVQiUf1CEEWYxWuMiVhxhCMREZG7cZvAhYZ0VLLwYX727FmdcgCN2vhQxxAgpoR4n5lkR40apcvFaQMwBQWG4dDkjusA016geoYZ152rTxjmQiM4epwQKjCkhuqMqyFMZ126dNFqHRr8EXLwWCzDeN4PBduFZWL/BQVDn1h3BB+ESOyH7t27a3UK+zc4c3ChRw3VK1TqjKM9MV0IttWAYUNUwIwTmuIr9qsxnAh4XgQy9G9h/6PxH1VMIiIid+NjC+sZRYksgF4xVMbSXj4g/vevBesxkRKllAQNu4unbLsxXOstvHW7gdvufduO7UbLRe5cucTnI01GbfP3D9FzYcQGIxmBWbBggY5WYfTC1QFRxtRTzudoxrajZxtzSmJkCSMqaFNB0cLoUcb1OPDKPNN9WAv9pFlEREQUZtA/jAD0dOdS8Xt8z9Lnihg/icSt2DhEj8GZSdCOAps3b9bzIprnssSIFHp60ZuL2QHMMEk2eqFdHeSFHmscPY+pk5YsWaIjQ5ijE6NNGKVBUAuPGLiIiIjcGMLW2wf/d6aP8ALTBRmnlYvtNJemAW0rrgIXqldoNTGfv9mAo9lfvnypLUVGVRMtRwhpK1asCLeBy216uIiIiMiz1KpVS08RaJwOz4Ahw8CmMEIvMQIX5qw0QzUNlS8znKkEvcGYCxL92eYD0nCgHI6CR782DigzjoLHUKd5iqn169frKehwUJ0xFyjm0EQFLiQYuIiIiChM5M2bV88mYp7yxwhgqH65gjkaUfnCKeRwkBnO1YvwhYO7nCti6A/DAV+4D0Kccd5eVMlwrl4ckIWzxWC2AUymjufG5NyYccA45y/OiGKehxI/43nME5oHBwMXERERhZkaNWro5Nzm4USEnvjx47u8P3q2MCE2Gu4xfRCmHcL5nVGtMp9tBnC/LFmy6FREmE0AQQrQ+4WhRywDUx6h4R49YegzQwM+hj6Nc/46n4IOc1qaj6gPLgYuIiIiCjM1a9aUo0ePysOHD985nGiefghzXmJYcMOGDdKjRw+dKxPTM5k5n4LOGFLEHJHG+Y0NGHY0TsmHgIZz/uIsMLgg0BmBy3xGlJBg0zwRERGFmcyZM+sFk2Rnz55dz6tboUKFIM/QgnCGqUAAFSxccA5fTCGBxxucpwoxZsIK7BR0xmnoUGHDfJIY8sTzYHJuhDFcUEXDeYpDihUuIiIiClM1a9aUXbt2aegqX768nt0lMH///bc2spvPV2yc9g8TjqP69S4YRnRuusdZX4xT8qFPDM+D0+IhbOFsLTiTzYwZM/ToSZzuLqRY4SKPFjFeYolg8wvefeMnsXx9iIg+tI/xu8vq56hRo4aexxdnKMGEqUFp1qyZTqiK4cMvv/xSkiRJIhcuXJBJkyZJkyZNgnWWF/Ruoel+4cKFUqZMGfntt9+0jwwN9oD+sWzZsulw5fz58/U6BK3ly5frUGZoMHCRR4tTrkGIZp8O6UzKRERhBecVxu+skE5IGlpW/n5MmTKlBhycQu9d5yFGX9Y333yjRzbilHE4mjBFihQ6Kz1O+xccGCocN26cNtzjlHGobOH8zKhsGYyjFY1eL1S6li1bFqr+LeCpfcijT/eRO3fuYP2140m8+VQn3rjdwG33vm331u12523nn/JEREREFmPgIiIiIrIYAxcRERGRxRi4iIiIiCzGwEVERERkMQYuIiIiIosxcJFHC+yQYcwnQ0RE9LFw4lPyaL6/rhLb4zsBZkz+WBMFEhERAQMXeTS/J/fF/8HNsF4NIiLychxSJCIiIrIYAxcRERGRxRi4iIiIiCzGwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDVzjWv39/yZo1a6CXAwcO6NcrV664fHyVKlVk9uzZAa4/ePCgw3Jy5MghxYsXl759+8qDBw8+wpYRERF5F57aJxz7+uuv5auvvtLvN2/eLPPmzZNVq1bZb48bN64kTpxYtm/fLu3atXN47JkzZ+Tq1atSs2bNQJe/b98+/fr27Vu5fv26jBs3Tlq0aCErV66UGDFiWLZdRERE3oYVrnAsduzYGqhwwfcRI0a0/4xLlChRpGrVqhq4nG3ZskUKFiwoyZMnD3T5xnJwnyJFisiPP/4o9+/fl2XLllm8ZURERN6FgcvN1apVS06dOiW3b992uH7r1q1BVrdcSZAggVSsWFF27NihP69Zs0Y+//xz6dy5s4a39evXy7Nnz2TAgAHyySefSK5cuTTw7dy5074MDFEi7FWrVk3y5s0rvXr10upZ8+bN9ecvvvhC7t69q/e12Wwya9YsKV++vC6rZMmS8t1339mXde7cOX1+PK5UqVIOtxEREbkTBi43hzCSKlUqhyqXEcAQhkIqU6ZMcvHiRfvPx48f1+tWrFihgWjkyJFy+fJlHd7cuHGjFCpUSIc+X79+bX/MtGnTZMyYMfLDDz/oejVu3FgvqJyhgmb0la1bt04WLlyoy0RARLCbPn26nD59Wm9HT1n27Nn1eXCfOXPmyJ49e95zjxEREX18DFweoEaNGvaqFKDChHAUP378EC8LQ5fPnz+3/+zj4yMdO3aUjBkzagWscOHCMmzYMA1C6dKlk9atW8uTJ0/k4cOH9se0bNlSg2CxYsX0fmjIR8UL31euXFkDG2Aoc/To0VotQ2hEKMMQ5z///KO337x5U+LFiycpU6aU0qVLy/z587XBn4iIyN2wad4DYOgQ/VcIPQkTJtRqUc+ePUO1LAwZxooVy/4zlhctWjT7z3Xq1NEhRFS8Ll26ZK9G+fn52e+TOnVq+/d4LAKT+WejGoZA9ueff8rEiRO1qnb27FmtgPn7++vt7du3l0mTJsny5culbNmy8umnn2ogIyIicjescHmAzJkz6wVB6K+//pJHjx5JhQoVQrWs8+fP67IMUaNGdbgdw3xjx46VOHHiaEUKw4bO0NxvFiGC67cZjoZENezVq1da+VqwYIEkS5bMfjuOvETlrm3bttoHZhxBSURE5G5Y4fKgKteuXbt0GA5N6NGjRw/xMjA0iNDWo0ePQKtf6KdCdStPnjx6ndFThQb4kFq6dKn2bX355Zf6s6+vr1bpsCyEsPHjx2vYatWqlV6GDBki27Ztk4YNG4b4uYiIiMISK1weAn1chw4d0iZ1HLkYHBi+wwUN9phEFf1Y6KsKLNBgGgoEOTzHjRs3ZO/evdrPBeam+eBCjxmeFz1daPTHMOibN290WaisHTt2TIYPH65DlydPnpQjR46wh4uIiNwSK1weAn1S2bJl0/BSokSJYD0GjfUQOXJkHcorV66cNsg7DyOaAxeqThhSXLRokTa64/5TpkzR/is01ofEwIED9YLeLPSKobEegQ7LgsmTJ2uga9CggUSKFEmPuuzUqVOInoOIiCg88LGFZiyIKJxDE/+JEyck7eUD4n//msNtkRKllAQNu4unb3u+fPkC9NN5Mm/dbuC2e9+2e+t2u/O2c0iRiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMM82TR4sYL7FEsPk5Xhc/SZitDxEReScGLvJocco1cDkTsc3fX3wisMBLREQfBz9xyONPAeEKwxYREX1M/NQhIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMgYs8WmBzcBEREX1MnPiUPJrvr6vE9viOwyzzcSs2DtN1IiIi78PARR7N78l98X9wM6xXg4iIvByHFImIiIgsxsBFREREZDEGLiIiIiKLMXARERERWYyBi4iIiMhiDFxEREREFmPgIiIiIrIYAxcRERGRxRi4iIiIiCzGwBWEp0+fypgxY6R8+fKSN29eqVatmixYsED8gzgX35o1a/T+VsNzZM2aNdDLlClTpEyZMmKz2QI89s6dO5ItWzb566+/XC77f//7n3z++ee6zQULFpQvv/xSTp06Zb99+vTp0qxZM0u3j4iIyJPw1D6BePz4sXz22WeSJEkSGTlypKRKlUpOnjwpw4cPl+vXr8vgwYNdPq569epStmxZy9dv1apV4ufnp99j/eDrr792CIvff/+9hioEJ7OtW7dKmjRpJE+ePAGWi2DVqVMn6du3r4wdO1ZevXolixcvlubNm8v69et1PxAREVHIMHAFYuLEiRIlShSZO3euRI0aVa9LnTq1RIsWTQNJ06ZNJX369AEeh9txsVqCBAkcnhMSJ05svw7fo9K1bdu2AIFry5YtUqNGDZfL3bBhg5QoUUKaNGliv+7bb7+VgwcPyubNm6Vdu3YWbA0REZFn45CiC69fv5ZNmzZp6DDClqFcuXI6rJgyZUr9GaFm6tSpUrRoUenQoYPDkCJCCr5HNQohpnDhwjJ79mw5fPiwVK1aVfLnz6+VJGOIEsN/M2bMkJIlS0qhQoV0ebdu3Qr1dtSsWVN27NjhcB2W9+eff+ptrkSIEEHOnz8vDx8+tF/n4+Mj8+bNk0aNGtmve/PmjQaxAgUKSPHixWX+/Pn227A9c+bMkQoVKmgVDcOPWCZ07NhRK2eGQYMG6T417Nu3T4dCAQGvSpUqkjt3bq0c7ty5M9T7goiIKCwxcLlw7do1+e+///SD3hnCR7FixbT6Zfj1119l6dKl0rt37wD3v3fvngaFRYsWaYCaNGmSjBo1SnvD8D1Cxa5du/S+GLpDhQnVteXLl0vChAmldevWGm5CA1UsDH+eO3fOYTgxe/bskjFjRpePadCggTx69EhDEMIR1hv7AwEzXrx49vsdP35cIkeOLOvWrdOqF7bn4sWLehtCIwLawIEDZe3atfpY9IFhnyJMIogaED5v376tfWVG/xjug8CHMNq+fXtd5/r160uvXr3kyZMnodoXREREYYmBywVfX1/9Gjt27GDdH71eGTJkkEyZMgW4DWGpX79+ejsqZqj+4Gu+fPk01CD8XLp0Se+LqhBCBqplCETDhg3TXqy9e/eGajsQdFBF2759u8NwYq1atQJ9DJ535cqVUrlyZQ1DI0aMkEqVKkn37t3lxYsX9vslTZpUBgwYoL1gLVu2lDhx4mgVC1U6BEfcHxUuLA99bxEjRtQeMIQpBMB///1X7t+/rwEKQ57Hjh3T5R44cEBKlSold+/e1X2XLFky3Q4Ez5kzZwaoOBIREbkD9nC5YFRyEHaCwxheDAx6v8y9Vub74zoMYT5//lyrPD179tRhPcPLly/lypUrEloYOkT1rVu3bnLz5k05ffq0fPfdd0E+BsFxwoQJ8vbtW61kYXh1xYoV2heGIUBA8zyqfQaEUzTYozJlhCgDKmG5cuXSChiOfkyRIoUcOXJEAxwCYbp06eTo0aNaObxw4YIOUWJ5OPigVatW2iuH8NawYUOJHj16qPcFERFRWGHgcgFVG3zgI5y4OpIPQ23oS0IwgHdVXSJFctzN5kBlMI44RD+YczN+3LhxJbQwlQWGMC9fvqxDl5jmAdWpwKC/6tNPP9VpI7De6DvDJVasWDp0akDFyhmqW4HtC2yf0auGfrZDhw5pQEMPGLYX1as//vhDh3FRLYMffvhBj7LEeqMX7eeff9YLqoJERETuhEOKLiBooEl7yZIlWn0y2717t14wXcSHhJCBni0Ms6VNm1YvyZMnl/Hjx2tYep+jGVE5QmhBL1lQw4lG0/rq1atdrp/5yMjAIKgmSpRITpw4Yb8OQ4MIr0aQxJAhAheGEXFwAELg33//rUdU4jZANQzhD4EXVT9U2bA/Qju8SkREFJZY4QpE165ddQirTZs2+j16idDsjQCEOalc9Wu9L/RCYcJSBC/0fKHqg1BizLMVWghZmN4Cze846i8omPICzemoVOFxGA7EOqC/bPTo0cHejmnTpmkoRXDEkZmoZiHEAgIgQhSCLYYacQACqooIXGiuNwIehkIR4LAeGGrEkGiOHDnea18QERGFBQauQKBfCR/4mFUdRx+iLwmhAL1QjRs3tuQ5Ee7QyzVkyBB59uyZhhEEpfcZUoSKFSvqMjGU965lYQgSAQhHGWL7UZ3C1BcYlkQfVXCgwR3rj8lh8RV9Wjja0aiQYXgSQ4foATOO9kSlC/sY22zsf+x79JLNmjVLQyiCIJruiYiI3I2PzdW5X4jcHHrGMKyZ9vIB8b9/zX59pEQpJUHD7uIN244jYV312nkqb91u4LZ737Z763a787azh4uIiIjIYgxcRERERBZj4CIiIiKyGAMXERERkcUYuIiIiIgsxsBFREREZDEGLiIiIiKLceJT8mgR4yWWCDa///s5/oc9JRMREVFwMHCRR4tTrkGAifFs/v7i4+IE4kRERFbhpw55/IzEzhi2iIjoY+MnDxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMgYuIiIjIYgxcRERERBZj4CKPZp70FBOeEhERhQXONE8ezffXVWJ7fEdP6RO3YuOwXh0iIvJSDFzk0fye3Bf/BzfDejWIiMjLcUiRiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMgesj6N+/v2TNmjXQy4EDB/TrlStXXD6+SpUqMnv27ECXf+zYMWnfvr0ULVpUChcuLK1atZLjx49LeNGsWTOZPn26fV/gQkRE5E0YuD6Cr7/+Wvbt26eXgQMHSrJkyew/41KwYEFJnDixbN++PcBjz5w5I1evXpWaNWu6XPa2bdukRYsWki1bNvnpp59k2bJlkiVLFmnevLkcPXpUwuO+wIWIiMib8NQ+H0Hs2LH1YnyPEyojYJlVrVpVA1e7du0crt+yZYsGsuTJkwdY7rNnz2TIkCHSsWNH6dSpk/36AQMGyK1bt2T8+PEawMITYz8QERF5E1a4wolatWrJqVOn5Pbt2w7Xb926NdDq1u7duzV0oZrlrF+/fjJixAj7zxhibNy4seTLl0/Kly8vS5cutd+GIT6Esx49ekjevHmlevXqWlmbPHmyFCpUSEqXLq3Bz4B17NChg94Xy/ruu+/Ez8/PfvuOHTt0GBTPNWzYMIfbnIcUcV88H5bVoEEDOXTokP22c+fOyeeff663lSpVSp+HiIjIHTFwhRMIFalSpXIYVjQCGKpfriCQZMiQQWLFihXgNiwrU6ZM+v3Fixd12BH9XWvWrJGuXbvK2LFjNewYFi5cKEWKFJH169dLvHjx9P4PHz6U5cuXa6gaOnSo+Pv7i81mky5dukjChAll7dq1Mnr0aNmwYYPMmjVLl3PhwgUNbgh3q1evlrdv3wY6tIn1RzBEhQ7PW7t2bWnbtq0OoULfvn0le/bssnHjRhk5cqTMmTNH9uzZ8557moiI6ONj4ApHatSo4RCCUFUqWbKkxI8f3+X9//33X5dhy9mKFSskR44c0qtXLw1odevWlaZNm2qAMeTKlUu++OILSZs2rVbUXrx4IYMGDZKMGTNq0/vTp0/lwYMH8scff+hw5fDhw3VZaNRHaEL/GCBkoSrWsmVLfezgwYMlSZIkLtdr7ty50qhRI63u4XlRqUM1zai+3bx5U8NfypQp9fr58+frdhAREbkb9nCFIwg6P/74o1aWUEHCcGLPnj0DvT/CiK+v7zuXiwpXnjx5HK7Lnz+/Q38XKmKGaNGiSaJEifQrRI0aVb++fv1al/XkyRPtKzOg8vXy5Ut5/Pix3o6qlCFy5MgOPzuvF0IlqmiGN2/eaMgEHHk5adIkvb1s2bLy6aefBuh9IyIicgcMXOFI5syZ9bJz504NKY8ePZIKFSoEev+cOXPKvHnztI/LudJ15MgRWbBggfZmGYHJDCHJ3FsVKZLjWyFCBNfFTwwRorI1c+bMQBviMexohtDlCp4fQ4h16tRxuN4IejiAoFq1aro/0K+GYU5U1ho2bOhyeUREROEVhxTDYZVr165dGjLQOxU9evRA74tGcoScxYsXB7gNPVl37tzRx6dPn17+/PNPh9vRRI/rQwqPwZBiggQJdBgQlxs3bsi0adPEx8dHA+PJkycdgh16tQJbFh5rLAcXVLN+//13efXqlTb9R4kSRecVW7RokQ4/YhoMIiIid8PAFQ77uHCkHprn0dsUlJgxY+q8XphUdMqUKTpEd/bsWe2b+u2337QHC9CbhesxPHf58mVtdv/555+lSZMmIV4/DPehp6pPnz5y/vx5raTh+RDsMN0FQhGa/b///nu5dOmSNucjoLmCPq/Nmzdr/9e1a9e0IodLunTptCqHCV1R0cJyEOLwXOzhIiIid8TAFc4gzGASU/RDlShR4p33x5F9M2bMkMOHD+sUChh2Q8BZsmSJTssAKVKkkB9++EH27t2rIQ5hCFMz1K9fP8Trh1CFx6NyhXCFIx7LlCljD3eoUuH2TZs26VDh/fv39XZXsH7jxo3T8IepIdDcP3HiRD2aEjAtBZr3MV1EmzZttBnfPN8YERGRu/CxOTfcEHkA9IedOHFC0l4+IP73r0mkRCklQcPu4k3bjkCLgOwtvHW7gdvufdvurdvtztvOChcRERGRxRi4iIiIiCzGwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishhPXk0eLWK8xBLB5icR4ycJ61UhIiIvxsBFHi1OuQb2mYht/v7iE4FFXSIi+vj46UMefwoIA8MWERGFFX4CEREREVmMgYuIiIjIYgxcRERERBZj4CIiIiKyGAMXERERkcUYuIiIiIgsxsBFHs08BxcREVFY4cSn5NF8f10lEcRf4lZsHNarQkREXoyBizya35P7YrP93+SnREREYYFDikREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMgYuIiIjIYgxcRERERBZj4HIha9asDpdixYrJoEGD5Pnz54E+5uDBg3pfw9mzZ+XYsWMubwvuMoKyZs2aAOtpvowZM0by5s0rK1ascPl4bE/btm1d3vbs2TMZOXKklC5dWnLlyiWVK1eW7777Tl6/fm2/D54D60tERETvxlP7BGL69OmSP39+8ff3l9u3b8uQIUNk3Lhx8u2337q8P+67b98++8+dO3eWLl26SIECBQLc9iFUr15dSpUqpd9j/Ro2bCgrV66U5MmT63UxYsTQ67dv3y6NGjVyeOzbt29lx44dMnDgQJfL7t+/vzx58kSmTJkiSZIkkXPnzsmwYcPk8ePHMnjw4A+6HURERN6AFa5AxI0bVxInTixJkyaVfPnySfv27WXLli2B3j9KlCh6/5DeFlrRokXTZeKSIEECvQ5fjetixowpNWvWlD/++EP+/fdfh8ceOHBAXr16JRUrVgywXNx3586d8vXXX2tYTJUqld7vq6++klWrVmkAJSIiopBh4Aqm6NGjO/xcvnx5GT9+vJQsWVLq1KmjwcYYDmzWrJncvHlTBgwYoNUi56HCn376ScqVKye5c+eWevXqyZEjRxyWvXTpUq1eoTKGZZiH8kKiTJkyGsx2797tcD2CI54focyZj4+PXvbv3+9wPYYV165dq7cZsN61atXS7WjatKlus+HixYvSpk0bDW3YFgxJIqydOXNGcuTIYQ+Bd+/e1X2zevVq+2M///xzrdb5+vpK165dpVChQlK4cGHp3bu3DncSERG5GwauYHj06JEsWrRIateu7XD9hg0bZO7cudovZQ4iGI5MliyZDtmhUmSGwIGhyaFDh2rwQZjo0aOHQ+Vo27ZtulyElK1btzqEkZBAZa1SpUo6rGh48+aN7Nq1S6tfrsSKFUvq1q2r61i1alUZPXq07NmzRyJGjCgZMmRw2E6EIvSCofL19OlTmTBhgn1/ffHFFzociftgWxcvXqxBM3v27BIvXjx7yDx06JAu0+h3Q6A6efKkhrRp06bJ/fv3NYDisRjanDlzZqj2BRERUVhiD1cg0FCOkGGz2eTFixcaEr755huH+yCAGZUrcwM57ovHxo4dWy9mqAIhYKRIkUKH6xC2UG0yBy4ElPTp00uWLFmkePHiGjRCCxWojh07yn///ad9XUblCg3xgRkxYoQGIwS9BQsW6CVRokTaSF+2bFn7/bDcokWL6vcNGjSQZcuW6fcbN27UiuDw4cMlUqRIkjFjRg1OM2bMkJYtW+o2IWhhuw8fPqzrYgQuVAqx7Qis2FeowmE/YXlTp04N9X4gIiIKS6xwBRE61q1bpxcECQwdNm7cWB4+fGi/T8qUKUO8XCwHQQpBCJWkefPmaeUIwcSQJk0a+/cIbKEdUgQEIizj999/159RMatSpYpEjhw50MdEiBBBh0Wx7Xgc9gV62rp166ZDgIGtJ/rCjOHEnDlzOmwThkcRujBMiH1gBFRUulq1aiVXr17Vyhj6y4yDAZo3b65B7JNPPtFwh8pXunTpQr0viIiIwgoDVyDQLJ82bVr9gEdYwNAaKl3mxvmoUaOGeLmo1GCYbeHChVKkSBGd3gF9XOYgg+qYGapsoYVlYWgQRyViOBEN8YENJwKC0Pfff++wH3AE5M8//+ww9GcEM1dc7Rejgufn5yclSpSQ8+fPa8i6c+eO7odMmTLJ8ePHHQIXghaGM1Hxw/AojhTt169fqPcFERFRWGHgCiaECwQfBIb3gVDxww8/6NxeaIhHxQmVoaNHj4pVELAQXDCciGFFNKAHBr1Y6JNCNcoMj0N4M46IDAqGBE+fPq0Bz7zdeCyGW3EUJQLWnDlz9AhQLBe9bJs2bdKpLPA9YCgTy0ElEMOJCL3mfjQiIiJ3wcAVRPBA6MDlypUrOg8VwhaOTgwOBJRLly7pfFZmOGoQvUyoct24cUNDBvqrgjvhaWgg1CDoTJ48WefvMje+O0NfFXquMMyHoxuxjhj2w7QQCFJBhTUDhksxDIqKFIYXUVXDgQQYkjWeG1UuHPWIoxgBIWvz5s1a7UI1C1D9wn4/ceKEvgY4mABHOBIREbkbNs0HAtMRmIcBMeP67NmzJXXq1MF6PMIFjtpDUEA/lAHN6Gg+RxUJYQLN85heAiHnwYMHYpUaNWrIrFmzZNSoUUHeD71dqCzhCEE0vSNwon8Lc3Hh58CGEZ2PdET1CtuJKTNQ2WrRooXOZWbAsCGOxCxYsKD+jK+oIBrDidC9e3edPsJo+kfYw74iIiJyNz6292kQIgqnUI1EZSzt5QMSweYnCRp2F2/bdmO41lt463YDt937tt1bt9udt51DikREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIiizFwEREREVmMgYuIiIjIYpxpnjxaxHiJJYL8vxNnExERhRUGLvJocco10JmIbf7+4hOM0xIRERFZgZ9A5PGngACGLSIiCkv8FCIiIiKyGIcUySMZ52RHhcuocnkLY3u53d6D2+592+6t2x1W2x4hQgTx8fF5r2X42IxPJiIP8vr1azl58mRYrwYREXmAfPnyaT/w+2DgIo/k7+8vb9++/SB/lRARkXeLwAoXERERUfjHpnkiIiIiizFwEREREVmMgYuIiIjIYgxcRERERBZj4CIiIiKyGAMXERERkcUYuIiIiIgsxsBFHufVq1cycOBAKVSokJQsWVLmzZsnnmLHjh2SNWtWh0u3bt30tjNnzkjDhg0lb968Ur9+fTl16pTDYzdu3CgVK1bU2zt37iyPHj0SdzhjQM2aNeXgwYP2665fvy4tW7bUmZ+rV68u+/btc3jM/v379THYzubNm+v9zRYsWCClSpWS/Pnz6/vkxYsX4i7bPmLEiACv/+LFi4P1GmPKxQkTJkixYsWkSJEiMm7cOJ0gODy5e/euvp+xfniNRo8erf+fPf11D2q7Pf01v3r1qrRp00Zfl7Jly8qcOXPst3nca46JT4k8ybBhw2y1atWynTp1yrZ9+3Zb/vz5bVu2bLF5gpkzZ9rat29vu3fvnv3y9OlT2/Pnz20lSpSwjRkzxnbhwgXb8OHDbcWLF9fr4c8//7TlyZPHtnbtWtvZs2dtTZs2tbVr184Wnr18+dLWuXNnW5YsWWx//PGHXufv76+v7VdffaXbOWvWLFvevHltN2/e1NvxNV++fLa5c+fa/v77b1v37t1tNWvW1MfB1q1bbQULFrTt3r1b90n16tVt3377rc0dth1atmxp++GHHxxe///++y9YrzH2SZkyZWyHDx+2HThwwFayZEnbnDlzbOEFXqNGjRrZvvzyS33tsJ6VKlXS97Qnv+5Bbbenv+Z+fn62ypUr6+t6+fJl22+//WYrUKCAbf369R75mjNwkUdBwMidO7fDh9SMGTP0F5EnwC+fiRMnBrh+5cqVtvLly9t/2eArfmmvXr1af+7Tp4+tX79+9vvfunXLljVrVtu1a9ds4dE///xjq127tv7CNYeO/fv36y9ZI0hCixYtbNOmTdPvp0yZ4vBa44MJgdt4/BdffGG/L+CDCB9YxgdYeN52KFWqlG3v3r0uH/eu1xgfvMb7AdatW2crV66cLbzAhyq29/79+/brNmzYoCHBk1/3oLbb01/zu3fvalD6999/7dfhD42hQ4d65GvOIUXyKOfOndNzKKKEbChYsKD8+eef4a6UHhoXL16UdOnSBbge24ftNM71ha8FChSQEydO2G/HEKshefLkkiJFCr0+PDp06JAULVpUli9f7nA91jdHjhwSI0YM+3XY7sC2M3r06JIzZ0693c/PT09obr4dQxVv3rzR90143/Znz57p0JOr1/9drzEed/v2bSlcuLDDfrt586bcu3dPwoPEiRPrcFKiRIkCbLcnv+5Bbbenv+ZJkiSRKVOmSKxYsXT48+jRo3L48GEd/vTE1zxSmD0zkQXu378v8ePHlyhRotivwy8y9EM8efJEEiRIIO4Kv5AuX76sfQw//PCD/lKpWrWq9n5guzNlyuRw/4QJE8o///yj3+MXLH65Od9+584dCY+++OILl9djO4PajqBu9/X11feB+fZIkSJJvHjxwtV+CGzbEbYRpGfNmiW///67rnerVq2kbt2673yNsV/AfLvxAY/bnR8XFuLEiaP9Ngb8gYReJfQfefLrHtR2e/prbla+fHm5deuWlCtXTqpUqSKjRo3yuNecgYs8CpoizWELjJ/RhOzO8MvI2D78VXjjxg1tqH358mWg221sM+4T1O3u4l3bGdTt2AfGz4E9Pjy7dOmSfvhmyJBBmjZtqpWAwYMHa3WgUqVKQb7GrrY9vP+/GD9+vB4IsmrVKm1+9pbX3bzdp0+f9prXfNq0afLgwQP55ptv9KABT/y/zsBFHiVq1KgB/kMZP0eLFk3cWcqUKfWItbhx4+ov4ezZs+tfw3369NESvKvtNrY5sP2CMrw7wXagUhnS7UQVAbcZP7vjfqhTp47+9Y+/0iFbtmxy5coVWbp0qX74BvUamz9onfdDeNx2hI6FCxfK5MmTJUuWLF7zujtvd+bMmb3mNc+dO7d+RWWqd+/eeqS181GF7v6as4eLPErSpEnl8ePH2sdlQOkZ/0nxH9Hd4Rev0acFGTNm1F9Q6APBX4dm+NkoqWO/uLodj3MngW1HcLYT+w6/iM23432CD3J32A943Y0PXgMqH+jVede24zYwhpnM34e3bR8+fLjMnz9fwweGlrzldXe13Z7+mj948EB27tzpcB1aI9Br9T6/08Lra87ARR4FVR+M1RuNlYBGTPz1FCGCe7/d9+7dq83U5r/6zp49q79c0Ex6/Phx7fMCfD127JjOTwP4iv1gQDMtLsbt7gLri2EWY8gAsF2BbSf2FYZncD1ef7wPzLfjfYL3CyoH4d3UqVN1TiIzNADjA/hdrzE+nNBMbb4d3+O68NTL891338myZctk0qRJUqNGDa953QPbbk9/zW/cuCFdunSxB0jA/IHotcXvNI97zcPs+EgiiwwePNhWo0YNnXtlx44dOq/Ltm3bbO4Oh07jEPFevXrZLl68qHPW4NDxH3/8UW8rVqyYzr+FaQXwFfNyGYdUHzt2zJYzZ07bihUr7PP1YD4vd2CeGuHt27c6n06PHj107h3MT4RDx425ea5fv67TguB6Y24eTK9gTJexceNGfT/gfYH3B94n2FfusO1Y3xw5cug8SlevXrUtWbLElitXLn1tg/MaY5/g/YLl4YLv582bZwsvMD1C9uzZbZMnT3aYcwoXT37dg9puT3/N3759a6tXr56tdevW+nsLv9Mwf+CCBQs88jVn4CKPg3lW+vbtq/858Qtm/vz5Nk+BXyyYCBHbhkA1ffp0+y8Y/FKpU6eO/hJq0KCB7fTp0w6PxXw8mJcHj8VcN48ePbK5A+e5qK5cuWJr0qSJfvDgl+j//vc/h/vjlzYmU8ScO5i3x3muMfyC/uSTT3RSxAEDBugko+6y7fjwwIcKXuOqVasG+EMiqNcYH2CjRo2yFSpUyFa0aFHb+PHj7e+d8ACvC7bX1cWTX/d3bbcnv+Zw584dXW+EI/xO+/777+3r6GmvuQ/+Cbv6GhEREZHnc++mFiIiIiI3wMBFREREZDEGLiIiIiKLMXARERERWYyBi4iIiMhiDFxEREREFmPgIiIiIrIYAxcRERGRxRi4iIjc2NOnT2XMmDFSvnx5PY9ctWrVZMGCBeLv72/5cz979kzWrVtn+fMQeYJIYb0CREQUOo8fP5bPPvtMT0Y8cuRISZUqlZw8eVKGDx8u169fl8GDB1v6/Ah2Bw8elDp16lj6PESegIGLiMhNTZw4UaJEiSJz586VqFGj6nWpU6eWaNGiSadOnaRp06aSPn16y56fZ4YjCj6eS5GIyA29fv1aihYtKn379pXGjRs73IZf66g8FShQQF68eCETJkyQXbt2yatXr3TocdCgQRI3bly9T/PmzeX8+fP2x/bv31+/Yphy+vTpcuXKFYkVK5Zs2LBBQ13r1q2lbdu2smbNGhkwYID9ceZlEFFA7OEiInJD165dk//++09y584d4DYfHx8pVqyYVr+6dOkiZ8+elVmzZsn8+fPl4sWL9lAVHNu2bdOgtXbtWmnTpo2Gt8uXL0v16tU1fOXPn1/27dv3gbeOyPNwSJGIyA35+vrq19ixYwd6n3PnzsmhQ4dk69at9qHF8ePHa1i6dOlSsJ4nXrx40q9fP4kYMaJ8+eWXMnv2bDl16pQuL0aMGBI5cmRJnDjxB9oqIs/FChcRkRtCEDKOUgwMQlWcOHEc+rgyZsyow4nBDVxoxEfYMsSMGVPevn37XutO5I0YuIiI3FCaNGm0unX69GmXt3fs2FGHFF3x8/PTC4YenTmHKVSwnLH1lyjkGLiIiNxQpEiRdGhwyZIl2kBvtnv3br2kS5dOhx7N1awLFy7o/FmoehlhCj8bbty4Eex1cBXYiMg1Bi4iIjfVtWtXDUtoZkevFhrpV65cqU3xOPowU6ZMUrp0ae3B+uuvv/SC7wsXLixZsmSRzJkz6xQSaKjHvF1z5syRM2fOBPv5o0ePLvfu3QtRSCPyVgxcRERuCs3qS5cu1bm3evfuLTVr1pSFCxdKt27d7Ecijh07Vm9v2bKlBjOErBkzZuhtmO4Bk6Ru2rRJH4sm+yZNmgT7+StVqqQz2teoUUMePnxo2XYSeQLOw0VERERkMVa4iIiIiCzGwEVERERkMQYuIiIiIosxcBERERFZjIGLiIiIyGIMXEREREQWY+AiIiIishgDFxEREZHFGLiIiIiILMbARURERGQxBi4iIiIisdb/B7mVzFkzERRmAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 606.375x500 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.catplot(x='count', y='genre', data=top_genres, kind='bar', hue='type', palette='Set2')\n",
    "plt.xlabel(\"Count\")\n",
    "plt.ylabel(\"Genre\")\n",
    "plt.title(\"Top 5 Genres in Movies vs TV Shows\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f57a5cdc",
   "metadata": {},
   "source": [
    "While both categories are genre-rich, Movies on Netflix emphasize Dramas and International content, whereas TV Shows lean heavily into Crime, Reality, and Kids content — highlighting differences in viewer preferences across formats."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "58a7d0fc",
   "metadata": {},
   "source": [
    "## Conclusion"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "30ee82b1",
   "metadata": {},
   "source": [
    "1. Movies dominate Netflix’s catalog compared to TV Shows, showing a strong preference for standalone storytelling formats.\n",
    "\n",
    "2. Drama and International content are the most common genres, reflecting Netflix’s global user base and focus on emotionally engaging narratives.\n",
    "\n",
    "3. United States and India contribute the highest number of titles, emphasizing Netflix’s dual focus on Western and South Asian markets.\n",
    "\n",
    "4. Content releases peaked in 2019–2020, reflecting Netflix’s aggressive expansion before and during the COVID-19 pandemic.\n",
    "\n",
    "5. TV Shows are concentrated around genres like Crime, Reality, and Kids, while Movies lean toward Dramas, Comedies, and Documentaries."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

{'cells': [{'cell_type': 'code',
   'execution_count': 1,
   'id': '8ad80af0',
   'metadata': {},
   'outputs': [],
   'source': ['import pandas as pd\n',
    'import numpy as np\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns']},
  {'cell_type': 'code',
   'execution_count': 2,
   'id': '29f1d272',
   'metadata': {},
   'outputs': [],
   'source': ["df = pd.read_csv('netflix_titles.csv', lineterminator='\\n')"]},
  {'cell_type': 'code',
   'execution_count': 3,
   'id': 'f343efbc',
   'metadata': {},
   'outputs': [{'data': {'text/html': ['<div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>show_id</th>\n',
       '      <th>type</th>\n',
       '      <th>title</th>\n',
       '      <th>director</th>\n',
       '      <th>cast</th>\n',
       '      <th>country</th>\n',
       '      <th>date_added</th>\n',
       '      <th>release_year</th>\n',
       '      <th>rating</th>\n',
       '      <th>duration</th>\n',
       '      <th>listed_in</th>\n',
       '      <th>description</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>0</th>\n',
       '      <td>s1</td>\n',
       '      <td>Movie</td>\n',
       '      <td>Dick Johnson Is Dead</td>\n',
       '      <td>Kirsten Johnson</td>\n',
       '      <td>NaN</td>\n',
       '      <td>United States</td>\n',
       '      <td>September 25, 2021</td>\n',
       '      <td>2020</td>\n',
       '      <td>PG-13</td>\n',
       '      <td>90 min</td>\n',
       '      <td>Documentaries</td>\n',
       '      <td>As her father nears the end of his life, filmm...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>1</th>\n',
       '      <td>s2</td>\n',
       '      <td>TV Show</td>\n',
       '      <td>Blood &amp; Water</td>\n',
       '      <td>NaN</td>\n',
       '      <td>Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...</td>\n',
       '      <td>South Africa</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>2 Seasons</td>\n',
       '      <td>International TV Shows, TV Dramas, TV Mysteries</td>\n',
       '      <td>After crossing paths at a party, a Cape Town t...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>2</th>\n',
       '      <td>s3</td>\n',
       '      <td>TV Show</td>\n',
       '      <td>Ganglands</td>\n',
       '      <td>Julien Leclercq</td>\n',
       '      <td>Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...</td>\n',
       '      <td>NaN</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>1 Season</td>\n',
       '      <td>Crime TV Shows, International TV Shows, TV Act...</td>\n',
       '      <td>To protect his family from a powerful drug lor...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>3</th>\n',
       '      <td>s4</td>\n',
       '      <td>TV Show</td>\n',
       '      <td>Jailbirds New Orleans</td>\n',
       '      <td>NaN</td>\n',
       '      <td>NaN</td>\n',
       '      <td>NaN</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>1 Season</td>\n',
       '      <td>Docuseries, Reality TV</td>\n',
       '      <td>Feuds, flirtations and toilet talk go down amo...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>4</th>\n',
       '      <td>s5</td>\n',
       '      <td>TV Show</td>\n',
       '      <td>Kota Factory</td>\n',
       '      <td>NaN</td>\n',
       '      <td>Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...</td>\n',
       '      <td>India</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>2 Seasons</td>\n',
       '      <td>International TV Shows, Romantic TV Shows, TV ...</td>\n',
       '      <td>In a city of coaching centers known to train I...</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>'],
      'text/plain': ['  show_id     type                  title         director  \\\n',
       '0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   \n',
       '1      s2  TV Show          Blood & Water              NaN   \n',
       '2      s3  TV Show              Ganglands  Julien Leclercq   \n',
       '3      s4  TV Show  Jailbirds New Orleans              NaN   \n',
       '4      s5  TV Show           Kota Factory              NaN   \n',
       '\n',
       '                                                cast        country  \\\n',
       '0                                                NaN  United States   \n',
       '1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   \n',
       '2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   \n',
       '3                                                NaN            NaN   \n',
       '4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   \n',
       '\n',
       '           date_added  release_year rating   duration  \\\n',
       '0  September 25, 2021          2020  PG-13     90 min   \n',
       '1  September 24, 2021          2021  TV-MA  2 Seasons   \n',
       '2  September 24, 2021          2021  TV-MA   1 Season   \n',
       '3  September 24, 2021          2021  TV-MA   1 Season   \n',
       '4  September 24, 2021          2021  TV-MA  2 Seasons   \n',
       '\n',
       '                                           listed_in  \\\n',
       '0                                      Documentaries   \n',
       '1    International TV Shows, TV Dramas, TV Mysteries   \n',
       '2  Crime TV Shows, International TV Shows, TV Act...   \n',
       '3                             Docuseries, Reality TV   \n',
       '4  International TV Shows, Romantic TV Shows, TV ...   \n',
       '\n',
       '                                         description  \n',
       '0  As her father nears the end of his life, filmm...  \n',
       '1  After crossing paths at a party, a Cape Town t...  \n',
       '2  To protect his family from a powerful drug lor...  \n',
       '3  Feuds, flirtations and toilet talk go down amo...  \n',
       '4  In a city of coaching centers known to train I...  ']},
     'execution_count': 3,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['df.head()']},
  {'cell_type': 'code',
   'execution_count': 4,
   'id': 'd8daab33',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ["<class 'pandas.core.frame.DataFrame'>\n",
      'RangeIndex: 8807 entries, 0 to 8806\n',
      'Data columns (total 12 columns):\n',
      ' #   Column        Non-Null Count  Dtype \n',
      '---  ------        --------------  ----- \n',
      ' 0   show_id       8807 non-null   object\n',
      ' 1   type          8807 non-null   object\n',
      ' 2   title         8807 non-null   object\n',
      ' 3   director      6173 non-null   object\n',
      ' 4   cast          7982 non-null   object\n',
      ' 5   country       7976 non-null   object\n',
      ' 6   date_added    8797 non-null   object\n',
      ' 7   release_year  8807 non-null   int64 \n',
      ' 8   rating        8803 non-null   object\n',
      ' 9   duration      8804 non-null   object\n',
      ' 10  listed_in     8807 non-null   object\n',
      ' 11  description   8807 non-null   object\n',
      'dtypes: int64(1), object(11)\n',
      'memory usage: 825.8+ KB\n']}],
   'source': ['df.info()']},
  {'cell_type': 'code',
   'execution_count': 5,
   'id': 'a6abcef0',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['0                                        Documentaries\n',
       '1      International TV Shows, TV Dramas, TV Mysteries\n',
       '2    Crime TV Shows, International TV Shows, TV Act...\n',
       '3                               Docuseries, Reality TV\n',
       '4    International TV Shows, Romantic TV Shows, TV ...\n',
       'Name: listed_in, dtype: object']},
     'execution_count': 5,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ["df['listed_in'].head()"]},
  {'cell_type': 'code',
   'execution_count': 6,
   'id': '2f19ff32',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['np.int64(0)']},
     'execution_count': 6,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['df.duplicated().sum()']},
  {'cell_type': 'code',
   'execution_count': 7,
   'id': '9dd4519e',
   'metadata': {},
   'outputs': [{'data': {'text/html': ['<div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>release_year</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>count</th>\n',
       '      <td>8807.000000</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>mean</th>\n',
       '      <td>2014.180198</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>std</th>\n',
       '      <td>8.819312</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>min</th>\n',
       '      <td>1925.000000</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>25%</th>\n',
       '      <td>2013.000000</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>50%</th>\n',
       '      <td>2017.000000</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>75%</th>\n',
       '      <td>2019.000000</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>max</th>\n',
       '      <td>2021.000000</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>'],
      'text/plain': ['       release_year\n',
       'count   8807.000000\n',
       'mean    2014.180198\n',
       'std        8.819312\n',
       'min     1925.000000\n',
       '25%     2013.000000\n',
       '50%     2017.000000\n',
       '75%     2019.000000\n',
       'max     2021.000000']},
     'execution_count': 7,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['df.describe()']},
  {'cell_type': 'code',
   'execution_count': 8,
   'id': '7771c2a7',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['show_id         0\n',
       'type            0\n',
       'title           0\n',
       'director        0\n',
       'cast            0\n',
       'country         0\n',
       'date_added      0\n',
       'release_year    0\n',
       'rating          0\n',
       'duration        0\n',
       'listed_in       0\n',
       'description     0\n',
       'dtype: int64']},
     'execution_count': 8,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['df.dropna(inplace=True)\n', 'df.isna().sum()']},
  {'cell_type': 'code',
   'execution_count': 9,
   'id': '049ba45f',
   'metadata': {},
   'outputs': [],
   'source': ["df.rename(columns={'listed_in':'genre'}, inplace=True)"]},
  {'cell_type': 'code',
   'execution_count': 10,
   'id': '6ddfd7e7',
   'metadata': {},
   'outputs': [{'data': {'text/html': ['<div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>show_id</th>\n',
       '      <th>type</th>\n',
       '      <th>title</th>\n',
       '      <th>director</th>\n',
       '      <th>cast</th>\n',
       '      <th>country</th>\n',
       '      <th>date_added</th>\n',
       '      <th>release_year</th>\n',
       '      <th>rating</th>\n',
       '      <th>duration</th>\n',
       '      <th>genre</th>\n',
       '      <th>description</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>7</th>\n',
       '      <td>s8</td>\n',
       '      <td>Movie</td>\n',
       '      <td>Sankofa</td>\n',
       '      <td>Haile Gerima</td>\n',
       '      <td>Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...</td>\n',
       '      <td>United States, Ghana, Burkina Faso, United Kin...</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>1993</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>125 min</td>\n',
       '      <td>Dramas, Independent Movies, International Movies</td>\n',
       '      <td>On a photo shoot in Ghana, an American model s...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>8</th>\n',
       '      <td>s9</td>\n',
       '      <td>TV Show</td>\n',
       '      <td>The Great British Baking Show</td>\n',
       '      <td>Andy Devonshire</td>\n',
       '      <td>Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...</td>\n',
       '      <td>United Kingdom</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-14</td>\n',
       '      <td>9 Seasons</td>\n',
       '      <td>British TV Shows, Reality TV</td>\n',
       '      <td>A talented batch of amateur bakers face off in...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>9</th>\n',
       '      <td>s10</td>\n',
       '      <td>Movie</td>\n',
       '      <td>The Starling</td>\n',
       '      <td>Theodore Melfi</td>\n',
       "      <td>Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...</td>\n",
       '      <td>United States</td>\n',
       '      <td>September 24, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>PG-13</td>\n',
       '      <td>104 min</td>\n',
       '      <td>Comedies, Dramas</td>\n',
       '      <td>A woman adjusting to life after a loss contend...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>12</th>\n',
       '      <td>s13</td>\n',
       '      <td>Movie</td>\n',
       '      <td>Je Suis Karl</td>\n',
       '      <td>Christian Schwochow</td>\n',
       '      <td>Luna Wedler, Jannis Niewöhner, Milan Peschel, ...</td>\n',
       '      <td>Germany, Czech Republic</td>\n',
       '      <td>September 23, 2021</td>\n',
       '      <td>2021</td>\n',
       '      <td>TV-MA</td>\n',
       '      <td>127 min</td>\n',
       '      <td>Dramas, International Movies</td>\n',
       '      <td>After most of her family is murdered in a terr...</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>24</th>\n',
       '      <td>s25</td>\n',
       '      <td>Movie</td>\n',
       '      <td>Jeans</td>\n',
       '      <td>S. Shankar</td>\n',
       '      <td>Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...</td>\n',
       '      <td>India</td>\n',
       '      <td>September 21, 2021</td>\n',
       '      <td>1998</td>\n',
       '      <td>TV-14</td>\n',
       '      <td>166 min</td>\n',
       '      <td>Comedies, International Movies, Romantic Movies</td>\n',
       '      <td>When the father of the man she loves insists t...</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>'],
      'text/plain': ['   show_id     type                          title             director  \\\n',
       '7       s8    Movie                        Sankofa         Haile Gerima   \n',
       '8       s9  TV Show  The Great British Baking Show      Andy Devonshire   \n',
       '9      s10    Movie                   The Starling       Theodore Melfi   \n',
       '12     s13    Movie                   Je Suis Karl  Christian Schwochow   \n',
       '24     s25    Movie                          Jeans           S. Shankar   \n',
       '\n',
       '                                                 cast  \\\n',
       '7   Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   \n',
       '8   Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   \n',
       "9   Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   \n",
       '12  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   \n',
       '24  Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...   \n',
       '\n',
       '                                              country          date_added  \\\n',
       '7   United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   \n',
       '8                                      United Kingdom  September 24, 2021   \n',
       '9                                       United States  September 24, 2021   \n',
       '12                            Germany, Czech Republic  September 23, 2021   \n',
       '24                                              India  September 21, 2021   \n',
       '\n',
       '    release_year rating   duration  \\\n',
       '7           1993  TV-MA    125 min   \n',
       '8           2021  TV-14  9 Seasons   \n',
       '9           2021  PG-13    104 min   \n',
       '12          2021  TV-MA    127 min   \n',
       '24          1998  TV-14    166 min   \n',
       '\n',
       '                                               genre  \\\n',
       '7   Dramas, Independent Movies, International Movies   \n',
       '8                       British TV Shows, Reality TV   \n',
       '9                                   Comedies, Dramas   \n',
       '12                      Dramas, International Movies   \n',
       '24   Comedies, International Movies, Romantic Movies   \n',
       '\n',
       '                                          description  \n',
       '7   On a photo shoot in Ghana, an American model s...  \n',
       '8   A talented batch of amateur bakers face off in...  \n',
       '9   A woman adjusting to life after a loss contend...  \n',
       '12  After most of her family is murdered in a terr...  \n',
       '24  When the father of the man she loves insists t...  ']},
     'execution_count': 10,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['df.head()']},
  {'cell_type': 'markdown',
   'id': '5e42992e',
   'metadata': {},
   'source': ['Splitting multiple genres into separate rows']},
  {'cell_type': 'code',
   'execution_count': 11,
   'id': '4dd26140',
   'metadata': {},
   'outputs': [],
   'source': ["df['genre'] = df['genre'].str.split(', ')\n",
    "df = df.explode('genre')\n",
    'df.reset_index(drop=True, inplace=True)']},
  {'cell_type': 'code',
   'execution_count': 12,
   'id': '48699d48',
   'metadata': {},
   'outputs': [{'data': {'text/html': ['<div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',